// 题库依据《营养学基础》教材第 65-113 页整理。每题只设置一个主考点。
window.QUESTION_BANK = [
  {id:"m-p-01",category:"磷",type:"single",stem:"正常成人血清无机磷的参考范围是",options:["0.20-0.50 mmol/L","0.87-1.45 mmol/L","1.80-2.50 mmol/L","2.80-3.45 mmol/L"],answer:[1],explanation:"血清无机磷水平可用于评价磷营养状况，正常成人范围为 0.87-1.45 mmol/L。",source:"教材第65页"},
  {id:"m-p-02",category:"磷",type:"multiple",stem:"关于膳食磷，下列说法正确的是",options:["动物性和植物性食物中都含有磷","谷类中的磷主要以植酸磷形式存在","谷类植酸磷与钙结合后不易吸收","成人磷的 RNI 为 720 mg/d"],answer:[0,1,2,3],explanation:"教材指出磷广泛存在于动植物食物中；谷类磷多为植酸磷，与钙结合后吸收较差。成人 RNI 为 720 mg/d。",source:"教材第65页"},
  {id:"m-mg-01",category:"镁",type:"single",stem:"正常成人摄入的镁，约有多少在小肠吸收",options:["5%-10%","30%-50%","60%-70%","80%-95%"],answer:[1],explanation:"镁在小肠的吸收率约为 30%-50%，摄入量较低时吸收率会提高。",source:"教材第66页"},
  {id:"m-mg-02",category:"镁",type:"single",stem:"血清镁低于何值可诊断为低镁血症",options:["0.30 mmol/L","0.50 mmol/L","0.70 mmol/L","1.20 mmol/L"],answer:[2],explanation:"血清镁低于 0.7 mmol/L 即可诊断为低镁血症。",source:"教材第66页"},
  {id:"m-mg-03",category:"镁",type:"multiple",stem:"镁缺乏可能出现的表现包括",options:["肌肉震颤和手足搐搦","低钾血症和低钙血症","反射亢进和共济失调","膝腱反射减弱、肌麻痹"],answer:[0,1,2],explanation:"镁缺乏常导致神经肌肉兴奋性亢进、低钾和低钙；膝腱反射减弱、肌麻痹主要见于镁过量。",source:"教材第66页"},
  {id:"m-mg-04",category:"镁",type:"single",stem:"成人膳食镁的 RNI 是",options:["120 mg/d","220 mg/d","330 mg/d","600 mg/d"],answer:[2],explanation:"中国营养学会推荐成人膳食镁 RNI 为 330 mg/d，2013 版暂不制定镁的 UL。",source:"教材第67页"},
  {id:"m-mg-05",category:"镁",type:"multiple",stem:"关于镁的食物来源，正确的是",options:["绿叶蔬菜含镁较丰富","糙粮和坚果含镁较丰富","硬水中的镁通常高于软水","精加工食物的镁含量通常最低"],answer:[0,1,2,3],explanation:"绿叶蔬菜、糙粮、坚果和硬水都是镁的来源；精加工会使食物镁含量降低。",source:"教材第67页"},
  {id:"m-fe-01",category:"铁",type:"single",stem:"人体内铁的主要功能性储存形式是",options:["血红蛋白中的铁","肌红蛋白中的铁","铁蛋白和含铁血黄素","运铁蛋白受体中的铁"],answer:[2],explanation:"剩余的 25%-30% 铁为储存铁，主要以铁蛋白和含铁血黄素形式储存在肝、脾和骨髓。",source:"教材第67页"},
  {id:"m-fe-02",category:"铁",type:"single",stem:"食物中的铁主要在哪一部位吸收",options:["胃底和胃体","十二指肠和空肠上端","回肠末端","结肠"],answer:[1],explanation:"铁的吸收主要发生在十二指肠和空肠上端。",source:"教材第68页"},
  {id:"m-fe-03",category:"铁",type:"multiple",stem:"关于血红素铁和非血红素铁，正确的是",options:["血红素铁主要来自动物性食物","非血红素铁常以 Fe3+ 形式存在","非血红素铁需还原为 Fe2+ 后吸收","血红素铁受膳食因素影响相对较小"],answer:[0,1,2,3],explanation:"血红素铁吸收率较高且受膳食因素影响较小；非血红素铁通常须先还原为 Fe2+，受膳食因素影响较大。",source:"教材第68页"},
  {id:"m-fe-04",category:"铁",type:"single",stem:"血红素铁的有效吸收率约为",options:["1%-5%","2%-20%","15%-35%","50%-80%"],answer:[2],explanation:"教材给出的血红素铁有效吸收率为 15%-35%，非血红素铁为 2%-20%。",source:"教材第68页"},
  {id:"m-fe-05",category:"铁",type:"single",stem:"维生素 C 促进非血红素铁吸收的关键作用是",options:["把 Fe2+ 氧化为 Fe3+","把 Fe3+ 还原为 Fe2+","抑制胃酸分泌","促进铁以离子形式自由通过细胞"],answer:[1],explanation:"非血红素铁需先还原为二价铁，维生素 C 是这一过程的重要促进因子。",source:"教材第68页"},
  {id:"m-fe-06",category:"铁",type:"single",stem:"缺铁性贫血的典型红细胞指标组合是",options:["高 MCV、高 RDW","低 MCV、低 RDW","低 MCV、高 RDW","高 MCV、正常 RDW"],answer:[2],explanation:"缺铁性贫血通常表现为 MCV <80 fL、RDW >15%，即红细胞体积偏小且大小不均。",source:"教材第70页"},
  {id:"m-fe-07",category:"铁",type:"multiple",stem:"关于铁营养评价，正确的是",options:["血清铁蛋白可反映体内铁储存","sTfR 不受感染或炎症影响，早期缺铁即可升高","血红蛋白是缺铁的晚期指标","成年人的运铁蛋白饱和度低于 16% 提示缺铁"],answer:[0,1,2,3],explanation:"这四项均为教材列出的铁评价要点。血清铁本身受进食、生理状态和溶血等影响，临床价值相对有限。",source:"教材第69-70页"},
  {id:"m-fe-08",category:"铁",type:"single",stem:"体内铁过量时最主要的靶器官是",options:["肝脏","甲状腺","骨骼肌","皮肤"],answer:[0],explanation:"铁过量可引起肝纤维化和肝细胞瘤，肝脏是主要受损靶器官。",source:"教材第69页"},
  {id:"m-zn-01",category:"锌",type:"single",stem:"锌参与维持下列哪类酶的活性",options:["RNA 和 DNA 聚合酶","胃蛋白酶","凝血因子","胆汁酸合成酶"],answer:[0],explanation:"锌是维持 RNA 聚合酶、DNA 聚合酶和反转录酶活性所必需的微量元素。",source:"教材第71页"},
  {id:"m-zn-02",category:"锌",type:"multiple",stem:"锌缺乏可能导致",options:["食欲减退和异食癖","儿童生长发育停滞","成人性功能减退","免疫力降低"],answer:[0,1,2,3],explanation:"锌参与蛋白质合成、细胞生长分化和免疫功能，缺乏可出现这些表现。",source:"教材第71-72页"},
  {id:"m-zn-03",category:"锌",type:"single",stem:"下列食物中，锌含量最高的是",options:["生蚝","苹果","精白米","牛奶"],answer:[0],explanation:"教材表 1-22 中生蚝含锌量约 71.20 mg/100g，是列举食物中很高的来源。",source:"教材第73页"},
  {id:"m-se-01",category:"硒",type:"single",stem:"缺硒与下列哪种疾病的发生关系最密切",options:["克山病","脚气病","夜盲症","坏血病"],answer:[0],explanation:"我国研究首先证实缺硒是克山病的重要原因，克山病主要表现为心肌病变。",source:"教材第74页"},
  {id:"m-se-02",category:"硒",type:"single",stem:"硒营养评价中，红细胞 GSH-Px 活性主要反映",options:["硒在体内的活性形式","近期蛋白质摄入量","体内铁储存量","尿碘排出量"],answer:[0],explanation:"谷胱甘肽过氧化物酶是含硒酶，测定其活性可直接反映硒营养状况，但在正常硒水平以上会饱和。",source:"教材第74页"},
  {id:"m-se-03",category:"硒",type:"multiple",stem:"关于硒摄入与来源，正确的是",options:["成人硒 RNI 为 60 μg/d","成人硒 UL 为 400 μg/d","海产品和动物内脏是良好来源","植物性食物的硒含量受土壤硒水平影响"],answer:[0,1,2,3],explanation:"教材列出的硒 RNI、UL、主要食物来源和地域差异均是考点。",source:"教材第75页"},
  {id:"m-cr-01",category:"铬、碘与其他矿物质",type:"single",stem:"铬作为葡萄糖耐量因子的重要组成成分，主要作用是",options:["增强胰岛素作用","抑制甲状腺素合成","促进维生素 C 排出","直接合成血红蛋白"],answer:[0],explanation:"铬是葡萄糖耐量因子的重要组成成分，在糖代谢中可增强胰岛素作用。",source:"教材第75页"},
  {id:"m-cr-02",category:"铬、碘与其他矿物质",type:"single",stem:"关于铬的价态，正确的是",options:["三价铬主要存在于天然食物，毒性较低","六价铬是人体必需的主要形式","三价铬主要来自工业污染，毒性最大","膳食铬过量中毒已有明确普遍报道"],answer:[0],explanation:"天然食物和生物体中主要是低毒的三价铬；六价铬主要来自工业生产，毒性较大。",source:"教材第76页"},
  {id:"m-i-01",category:"铬、碘与其他矿物质",type:"single",stem:"成人体内的碘约有多少存在于甲状腺组织",options:["5%-10%","20%-30%","40%-50%","70%-80%"],answer:[3],explanation:"成人体内含碘约 15-20 mg，其中 70%-80% 存在于甲状腺组织。",source:"教材第76页"},
  {id:"m-i-02",category:"铬、碘与其他矿物质",type:"single",stem:"两分子 DIT 偶联生成的是",options:["MIT","T3","T4","TSH"],answer:[2],explanation:"两分子二碘酪氨酸（DIT）偶联生成四碘甲腺原氨酸 T4；MIT 与 DIT 偶联生成 T3。",source:"教材第77页"},
  {id:"m-i-03",category:"铬、碘与其他矿物质",type:"multiple",stem:"关于碘缺乏和碘评价，正确的是",options:["碘缺乏的典型症状是甲状腺肿大","胎儿和婴幼儿缺碘可影响智力发育","尿碘可评价近期碘摄入","儿童尿碘中位数低于 100 μg/L 提示人群碘营养不良"],answer:[0,1,2,3],explanation:"碘缺乏可导致甲状腺代偿性肿大；孕期和儿童期缺碘会影响神经发育；尿碘是近期摄入评价指标。",source:"教材第77-78页"},
  {id:"m-i-04",category:"铬、碘与其他矿物质",type:"single",stem:"中国营养学会推荐成人碘的 RNI 和 UL 分别是",options:["60 μg/d 和 400 μg/d","100 μg/d 和 200 μg/d","120 μg/d 和 600 μg/d","200 μg/d 和 1000 μg/d"],answer:[2],explanation:"成人碘 RNI 为 120 μg/d，UL 为 600 μg/d。海带、海藻、鱼虾和贝类是常见富碘食物。",source:"教材第78页"},
  {id:"m-cu-01",category:"铬、碘与其他矿物质",type:"single",stem:"铜蓝蛋白在铁代谢中的关键作用是",options:["催化 Fe2+ 氧化为 Fe3+","催化 Fe3+ 还原为 Fe2+","阻断铁吸收","把铁直接转化为血红素"],answer:[0],explanation:"铜蓝蛋白可催化二价铁氧化为三价铁，有助于运铁蛋白形成并促进铁吸收和转运。",source:"教材第78页"},
  {id:"m-cu-02",category:"铬、碘与其他矿物质",type:"multiple",stem:"铜的生理功能包括",options:["维持正常造血","维护中枢神经系统完整性","促进骨骼、血管和皮肤健康","作为 SOD 的重要组成成分参与抗氧化"],answer:[0,1,2,3],explanation:"铜参与造血、神经髓鞘和递质合成、胶原交联以及 SOD 抗氧化。",source:"教材第78页"},
  {id:"m-mn-01",category:"铬、碘与其他矿物质",type:"single",stem:"锰的吸收率一般约为",options:["2%-15%","20%-35%","50%-65%","75%-90%"],answer:[0],explanation:"锰在小肠吸收率较低，约为 2%-15%；摄入高时吸收率下降。",source:"教材第80页"},
  {id:"m-f-01",category:"铬、碘与其他矿物质",type:"single",stem:"氟预防龋齿的主要机制是",options:["形成抗酸性的氟磷灰石保护层","促进牙菌斑产酸","抑制钙磷利用","使牙釉质完全脱矿"],answer:[0],explanation:"氟可与牙釉质羟磷灰石作用形成抗酸性的氟磷灰石保护层，减少酸性损伤。",source:"教材第80页"},
  {id:"v-general-01",category:"维生素总论",type:"multiple",stem:"关于脂溶性维生素，正确的是",options:["包括维生素 A、D、E、K","吸收与肠道脂类密切相关","通常易储存于体内而不易排出","摄入过多更易蓄积产生毒性"],answer:[0,1,2,3],explanation:"脂溶性维生素与脂类共存、依赖脂类吸收，易在体内储存，因此过量蓄积风险较高。",source:"教材第83页"},
  {id:"v-general-02",category:"维生素总论",type:"single",stem:"下列哪种维生素虽然属于水溶性维生素，却较易储存于体内",options:["维生素 B1","维生素 B2","维生素 B12","维生素 C"],answer:[2],explanation:"水溶性维生素通常易随尿排出，但维生素 B12 是重要例外，体内储存能力较强。",source:"教材第83页"},
  {id:"v-general-03",category:"维生素总论",type:"single",stem:"维生素缺乏由膳食供给不足或生物利用率过低直接引起，称为",options:["原发性维生素缺乏","继发性维生素缺乏","临床过量","亚临床中毒"],answer:[0],explanation:"原发性缺乏来自膳食供给不足或生物利用率过低；吸收、利用障碍或需要量增加导致继发性缺乏。",source:"教材第83-84页"},
  {id:"v-a-01",category:"维生素 A",type:"single",stem:"下列哪一种类胡萝卜素不具有维生素 A 活性",options:["β-胡萝卜素","α-胡萝卜素","β-隐黄素","番茄红素"],answer:[3],explanation:"番茄红素、叶黄素和玉米黄素等不能分解形成维生素 A；β-胡萝卜素是重要的维生素 A 原。",source:"教材第84页"},
  {id:"v-a-02",category:"维生素 A",type:"single",stem:"膳食中视黄醇的吸收率约为",options:["5%以下","20%-50%","70%-90%","接近100%"],answer:[2],explanation:"教材给出的视黄醇吸收率约为 70%-90%，类胡萝卜素约为 20%-50%且随摄入增加而下降。",source:"教材第85页"},
  {id:"v-a-03",category:"维生素 A",type:"single",stem:"肝脏储存维生素 A 的主要细胞是",options:["肝星状细胞","胰岛 β 细胞","肾小管细胞","甲状腺滤泡细胞"],answer:[0],explanation:"视黄醇主要以棕榈酸视黄酯形式储存在肝星状细胞（约 80%-95%）和肝主细胞。",source:"教材第86页"},
  {id:"v-a-04",category:"维生素 A",type:"single",stem:"维生素 A 缺乏最早出现的视觉表现是",options:["失明","眼干燥症","暗适应能力下降","角膜溃疡"],answer:[2],explanation:"维生素 A 缺乏最早是暗适应能力下降，随后可发展为夜盲、眼干燥症甚至失明。",source:"教材第88页"},
  {id:"v-a-05",category:"维生素 A",type:"single",stem:"儿童维生素 A 缺乏的重要临床诊断体征是",options:["毕脱氏斑","肋骨串珠","地图舌","反甲"],answer:[0],explanation:"毕脱氏斑表现为角膜两侧和结膜外侧的泡沫样白斑，是儿童维生素 A 缺乏的重要体征。",source:"教材第88页"},
  {id:"v-a-06",category:"维生素 A",type:"multiple",stem:"关于维生素 A 过量，正确的是",options:["长期摄入 RNI 10 倍以上可发生慢性中毒","孕早期大剂量摄入会增加出生缺陷风险","普通食物一般不易造成维生素 A 过量","类胡萝卜素过量通常不会产生同样的毒性"],answer:[0,1,2,3],explanation:"维生素 A 浓缩制剂是过量的常见来源；类胡萝卜素转化慢且吸收会下降，通常只导致可逆的高胡萝卜素血症。",source:"教材第88页"},
  {id:"v-a-07",category:"维生素 A",type:"single",stem:"血清维生素 A 低于下列哪一值可提示缺乏或边缘性缺乏",options:["0.10 μmol/L","0.70 μmol/L","1.50 μmol/L","3.00 μmol/L"],answer:[2],explanation:"成人血清维生素 A 正常范围为 1.5-3 μmol/L，低于相应界值可结合其他资料判断缺乏。",source:"教材第88-89页"},
  {id:"v-d-01",category:"维生素 D",type:"single",stem:"维生素 D 在血液中的主要存在形式，也是评价其营养状况的首选指标是",options:["1,25-(OH)2-D3","25-(OH)-D3","维生素 D 结合蛋白","24,25-(OH)2-D3"],answer:[1],explanation:"25-(OH)-D3 半衰期约 3 周、受调节影响较小，可反映数周至数月的储存状况。",source:"教材第93页"},
  {id:"v-d-02",category:"维生素 D",type:"single",stem:"维生素 D 的活性形式是",options:["维生素 D2","维生素 D3","25-(OH)-D3","1,25-(OH)2-D3"],answer:[3],explanation:"1,25-(OH)2-D3 是维生素 D 的活性形式，作用于肠、肾、骨等靶器官。",source:"教材第91页"},
  {id:"v-d-03",category:"维生素 D",type:"multiple",stem:"活性维生素 D 的作用包括",options:["促进小肠钙吸收","促进肾小管钙、磷重吸收","低血钙时动员骨钙磷入血","调节血钙平衡"],answer:[0,1,2,3],explanation:"活性维生素 D 通过肠、肾、骨等器官参与钙磷代谢和血钙稳态。",source:"教材第92页"},
  {id:"v-d-04",category:"维生素 D",type:"single",stem:"婴儿维生素 D 缺乏主要导致",options:["骨质疏松症","佝偻病","坏血病","脚气病"],answer:[1],explanation:"婴儿缺乏维生素 D 可发生佝偻病；成人尤其是孕妇、乳母和老人可发生骨质软化或骨质疏松。",source:"教材第92页"},
  {id:"v-d-05",category:"维生素 D",type:"single",stem:"维生素 D 的廉价有效来源是",options:["经常晒太阳","大量饮用牛奶","只吃蔬菜水果","服用高剂量补充剂"],answer:[0],explanation:"经常接触阳光可促进皮肤合成维生素 D，成年人通常不会因此发生缺乏。",source:"教材第93页"},
  {id:"v-e-01",category:"维生素 E",type:"single",stem:"维生素 E 中生物活性最高、常作为代表的是",options:["α-生育酚","β-生育酚","γ-生育三烯酚","δ-生育三烯酚"],answer:[0],explanation:"维生素 E 包括四种生育酚和四种生育三烯酚，其中 α-生育酚生物活性最高。",source:"教材第93页"},
  {id:"v-e-02",category:"维生素 E",type:"single",stem:"维生素 E 在体内主要储存在",options:["脂肪细胞","红骨髓","甲状腺滤泡","肾小球"],answer:[0],explanation:"大部分维生素 E 以非酯化形式储存在脂肪细胞，少量储存在肝、肺、心脏、肌肉等组织。",source:"教材第94页"},
  {id:"v-e-03",category:"维生素 E",type:"multiple",stem:"关于维生素 E，正确的是",options:["是重要的脂质抗氧化剂","可与维生素 C、谷胱甘肽等协同再生","缺乏可出现溶血性贫血和肌无力","大剂量可干扰维生素 K 的吸收和利用"],answer:[0,1,2,3],explanation:"维生素 E 参与抗氧化系统；缺乏可损伤红细胞和神经肌肉；大剂量时可能影响维生素 K。",source:"教材第94-95页"},
  {id:"v-e-04",category:"维生素 E",type:"single",stem:"红细胞溶血试验中，维生素 E 缺乏通常表现为溶血百分比",options:["小于 10%","10%-20%","大于 20%","等于 0%"],answer:[2],explanation:"红细胞溶血试验中，正常 <10%，偏低 10%-20%，缺乏 >20%。",source:"教材第95页"},
  {id:"v-b1-01",category:"维生素 B1",type:"single",stem:"维生素 B1 的主要活性形式是",options:["FMN","FAD","TPP","PLP"],answer:[2],explanation:"焦磷酸硫胺素（TPP）是维生素 B1 的主要活性形式，参与 α-酮酸氧化脱羧和转酮醇反应。",source:"教材第96-97页"},
  {id:"v-b1-02",category:"维生素 B1",type:"multiple",stem:"TPP 参与的关键反应包括",options:["α-酮酸氧化脱羧","磷酸戊糖途径的转酮醇反应","丙酮酸转化为乙酰辅酶 A","直接催化脂肪酸水解"],answer:[0,1,2],explanation:"TPP 参与 α-酮酸氧化脱羧及磷酸戊糖途径转酮醇反应，不直接催化脂肪酸水解。",source:"教材第97页"},
  {id:"v-b1-03",category:"维生素 B1",type:"single",stem:"湿性脚气病的主要表现是",options:["多发性周围神经炎","水肿和心脏症状","夜盲和眼干燥","皮炎、腹泻和痴呆"],answer:[1],explanation:"湿性脚气病以水肿和心血管症状为主；干性脚气病以多发性周围神经炎为主。",source:"教材第97页"},
  {id:"v-b1-04",category:"维生素 B1",type:"single",stem:"维生素 B1 尿负荷试验中，4 小时尿排出量低于多少提示缺乏",options:["40 μg","100 μg","200 μg","400 μg"],answer:[1],explanation:"口服 5 mg 后收集 4 小时尿液，排出维生素 B1 <100 μg（约摄入量 2%）提示缺乏。",source:"教材第97-98页"},
  {id:"v-b1-05",category:"维生素 B1",type:"single",stem:"维生素 B1 在日常膳食中的主要来源是",options:["谷类食物","纯牛奶","柑橘类水果","精炼植物油"],answer:[0],explanation:"维生素 B1 主要来自谷类，且多存在于表皮和胚芽，过度碾磨会造成损失。",source:"教材第98页"},
  {id:"v-b2-01",category:"维生素 B2",type:"single",stem:"维生素 B2 在体内主要以哪两种辅酶形式发挥作用",options:["TPP 和 TTP","FMN 和 FAD","PLP 和 PMP","NAD 和 NADP"],answer:[1],explanation:"核黄素在体内形成 FMN 和 FAD，参与多种氧化还原反应和能量代谢。",source:"教材第99页"},
  {id:"v-b2-02",category:"维生素 B2",type:"single",stem:"维生素 B2 缺乏的典型综合征主要累及",options:["眼、口腔和皮肤","骨、肾和肌肉","胃、肝和胰腺","脑、心和肺"],answer:[0],explanation:"核黄素缺乏主要表现为眼、口腔和皮肤的炎症反应，常称口腔生殖系统综合征。",source:"教材第99-100页"},
  {id:"v-b2-03",category:"维生素 B2",type:"single",stem:"EGRAC 小于何值通常提示核黄素营养状况正常",options:["0.8","1.2","1.4","2.0"],answer:[1],explanation:"红细胞谷胱甘肽还原酶活性系数 EGRAC <1.2 为正常，1.2-1.4 为不足，>1.4 为缺乏。",source:"教材第100页"},
  {id:"v-b2-04",category:"维生素 B2",type:"multiple",stem:"会增加维生素 B2 需要量或造成损失的情况包括",options:["能量需要量增加","生长加速或创伤修复","碱性环境和光照","食物加工时加碱"],answer:[0,1,2,3],explanation:"B2 需要量与能量代谢相关；其在碱性环境中易被热和紫外线破坏。",source:"教材第100页"},
  {id:"v-niacin-01",category:"烟酸",type:"single",stem:"烟酸缺乏症的经典“三 D”是",options:["皮炎、腹泻、痴呆","头痛、脱发、贫血","夜盲、干眼、失明","水肿、心悸、麻木"],answer:[0],explanation:"烟酸缺乏可出现 dermatitis、diarrhea、dementia，即皮炎、腹泻和痴呆。",source:"教材第101页"},
  {id:"v-niacin-02",category:"烟酸",type:"single",stem:"平均约多少色氨酸可转化为 1 mg 烟酸",options:["6 mg","20 mg","60 mg","600 mg"],answer:[2],explanation:"平均约 60 mg 色氨酸可转化为 1 mg 烟酸，因此烟酸摄入以烟酸当量表示。",source:"教材第102页"},
  {id:"v-niacin-03",category:"烟酸",type:"single",stem:"烟酸当量的计算式是",options:["烟酸 + 60×色氨酸","烟酸 + 色氨酸/60","烟酸 - 色氨酸/60","烟酸 × 色氨酸"],answer:[1],explanation:"烟酸当量（mg NE）= 烟酸（mg）+ 色氨酸（mg）/60。",source:"教材第102页"},
  {id:"v-niacin-04",category:"烟酸",type:"multiple",stem:"烟酸的生理作用包括",options:["构成 NAD 和 NADP 参与氢的传递","降低血胆固醇水平","参与葡萄糖耐量因子组成","参与物质和能量代谢"],answer:[0,1,2,3],explanation:"烟酸以烟酰胺形式参与 NAD/NADP、物质能量代谢、胆固醇调节及葡萄糖耐量因子。",source:"教材第101页"},
  {id:"v-pan-01",category:"泛酸",type:"single",stem:"泛酸的主要生理作用是构成",options:["辅酶 A 和酰基载体蛋白","视紫红质和 RBP","血红蛋白和肌红蛋白","甲状腺素和降钙素"],answer:[0],explanation:"泛酸构成辅酶 A 和酰基载体蛋白，并参与糖、脂肪和蛋白质代谢。",source:"教材第103页"},
  {id:"v-pan-02",category:"泛酸",type:"single",stem:"成人全血泛酸浓度低于何值可提示摄入不足或缺乏",options:["0.1 mg/L","1 mg/L","5 mg/L","10 mg/L"],answer:[1],explanation:"正常全血泛酸约 2 mg/L，低于 1 mg/L 可认为摄入不足或缺乏。",source:"教材第103页"},
  {id:"v-b6-01",category:"维生素 B6",type:"single",stem:"维生素 B6 在体内的主要活性形式是",options:["PLP","TPP","FAD","NADP"],answer:[0],explanation:"磷酸吡哆醛（PLP）是维生素 B6 在体内的主要活性形式。",source:"教材第104页"},
  {id:"v-b6-02",category:"维生素 B6",type:"multiple",stem:"维生素 B6 参与的过程包括",options:["氨基酸转氨和脱氨","烟酸合成","血红素合成","神经递质合成"],answer:[0,1,2,3],explanation:"PLP 参与氨基酸、脂肪、烟酸、血红素、抗体、神经递质及同型半胱氨酸代谢。",source:"教材第104页"},
  {id:"v-b6-03",category:"维生素 B6",type:"single",stem:"长期大剂量服用维生素 B6（约 500 mg/d）可能导致",options:["神经毒性和光敏感性","严重碘缺乏","佝偻病","坏血病"],answer:[0],explanation:"食物来源的 B6 通常安全，但大剂量补充可导致神经毒性和光敏感性反应。",source:"教材第105页"},
  {id:"v-biotin-01",category:"生物素",type:"single",stem:"生蛋清导致生物素吸收受阻的主要原因是含有",options:["抗生物素蛋白","胰蛋白酶抑制剂","植酸","单宁"],answer:[0],explanation:"生蛋清中的抗生物素蛋白可结合生物素，使其不能在肠道吸收；加热可破坏该蛋白。",source:"教材第106页"},
  {id:"v-biotin-02",category:"生物素",type:"multiple",stem:"关于生物素，正确的是",options:["是多种羧化酶的辅酶","参与糖、脂肪、蛋白质和核酸代谢","成人 AI 为 40 μg/d","目前未见明确生物素毒性反应报道"],answer:[0,1,2,3],explanation:"生物素参与多种羧化反应；成人 AI 为 40 μg/d，毒性很低。",source:"教材第106页"},
  {id:"v-folate-01",category:"叶酸",type:"single",stem:"叶酸在体内具有生理功能的主要形式是",options:["叶酸多谷氨酸","二氢叶酸","四氢叶酸","叶酸钠盐"],answer:[2],explanation:"天然叶酸多为还原形式，但只有四氢叶酸具有主要生理功能。",source:"教材第107页"},
  {id:"v-folate-02",category:"叶酸",type:"single",stem:"叶酸最重要的代谢功能是作为何种基团的载体",options:["一碳单位","硫酸根","磷酸根","脂肪酸"],answer:[0],explanation:"四氢叶酸携带甲酰基、亚甲基和甲基等一碳基团，参与核苷酸合成和甲基化反应。",source:"教材第107页"},
  {id:"v-folate-03",category:"叶酸",type:"single",stem:"孕早期叶酸缺乏最需要警惕的胎儿结局是",options:["神经管畸形","氟斑牙","佝偻病","克山病"],answer:[0],explanation:"孕早期叶酸缺乏可导致胎儿神经管畸形，主要表现为脊柱裂和无脑畸形。",source:"教材第108页"},
  {id:"v-folate-04",category:"叶酸",type:"multiple",stem:"关于膳食叶酸当量 DFE，正确的是",options:["DFE = 膳食叶酸 + 1.7 × 叶酸补充剂","成人叶酸 RNI 为 400 μg DFE/d","孕妇叶酸 RNI 为 600 μg DFE/d","叶酸 UL 为 1000 μg DFE/d"],answer:[0,1,2,3],explanation:"DFE 公式和成人、孕妇 RNI 以及 UL 均为教材给出的参考值。",source:"教材第108页"},
  {id:"v-b12-01",category:"维生素 B12",type:"single",stem:"维生素 B12 吸收必须依赖胃黏膜分泌的",options:["内因子","胆盐","胰脂酶","运铁蛋白"],answer:[0],explanation:"B12 从食物释放后需与胃黏膜分泌的内因子结合，复合物在回肠被吸收。",source:"教材第109页"},
  {id:"v-b12-02",category:"维生素 B12",type:"single",stem:"维生素 B12 的主要转运蛋白是",options:["TC I","TC II","RBP","DBP"],answer:[1],explanation:"TC II 是维生素 B12 的主要转运蛋白，将其运至肝、肾、骨髓等组织。",source:"教材第109页"},
  {id:"v-b12-03",category:"维生素 B12",type:"multiple",stem:"维生素 B12 缺乏可能导致",options:["巨幼红细胞贫血","进行性脱髓鞘和神经系统损害","高同型半胱氨酸血症","甲基丙二酸增高"],answer:[0,1,2,3],explanation:"B12 参与核酸合成、同型半胱氨酸甲基化和甲基丙二酸代谢，缺乏可同时造成造血和神经损害。",source:"教材第110页"},
  {id:"v-b12-04",category:"维生素 B12",type:"single",stem:"维生素 B12 的主要膳食来源是",options:["动物性食品","精制谷物","新鲜水果","植物油"],answer:[0],explanation:"B12 主要来自肉类、动物内脏、鱼、禽和蛋类，植物性食品基本不含。",source:"教材第111页"},
  {id:"v-c-01",category:"维生素 C",type:"single",stem:"天然维生素 C 中具有生物活性的是",options:["L 型","D 型","两者均无","只有合成型"],answer:[0],explanation:"天然维生素 C 有 L 型和 D 型，L 型具有生物活性，D 型无生物活性。",source:"教材第111页"},
  {id:"v-c-02",category:"维生素 C",type:"single",stem:"维生素 C 促进铁吸收的机制是",options:["把 Fe3+ 还原成 Fe2+","把 Fe2+ 氧化成 Fe3+","抑制小肠主动转运","促进植酸与铁结合"],answer:[0],explanation:"维生素 C 可将难以吸收利用的三价铁还原成二价铁，促进肠道吸收。",source:"教材第112页"},
  {id:"v-c-03",category:"维生素 C",type:"multiple",stem:"维生素 C 的生理功能包括",options:["抗氧化和清除自由基","参与胶原蛋白羟基化","促进铁、钙和叶酸利用","参与去甲肾上腺素等神经递质合成"],answer:[0,1,2,3],explanation:"维生素 C 既是抗氧化剂，也是胶原羟化过程辅助因子，并参与多种营养素利用和神经递质合成。",source:"教材第112页"},
  {id:"v-c-04",category:"维生素 C",type:"single",stem:"维生素 C 缺乏的主要疾病是",options:["坏血病","佝偻病","脚气病","糙皮病"],answer:[0],explanation:"体内维生素 C 储存低于约 300 mg 可出现缺乏症状，主要引起坏血病。",source:"教材第112页"},
  {id:"v-c-05",category:"维生素 C",type:"single",stem:"血浆维生素 C 浓度低于何值可视为缺乏",options:["4 mg/L","3.9 mg/L","2 mg/L","0.5 mg/L"],answer:[2],explanation:"血浆维生素 C ≥4 mg/L 为正常，2.0-3.9 mg/L 为不足，<2 mg/L 为缺乏。",source:"教材第113页"},

  {id:"add-p-01",category:"磷",type:"single",stem:"膳食钙磷比例理论上维持在何值较为理想",options:["1:3","1:1","2:1","4:1"],answer:[2],explanation:"教材指出膳食钙磷比例维持在 2:1 之间较好，不宜低于 0.5。",source:"教材第65页"},
  {id:"add-p-02",category:"磷",type:"single",stem:"中国营养学会推荐成人膳食磷的 UL 是",options:["720 mg/d","1200 mg/d","2000 mg/d","3500 mg/d"],answer:[3],explanation:"成人膳食磷的 RNI 为 720 mg/d，UL 为 3500 mg/d。",source:"教材第65页"},
  {id:"add-p-03",category:"磷",type:"single",stem:"磷摄入过量可能引起的非骨性后果是",options:["非骨组织钙化","视紫红质减少","胶原蛋白合成增加","甲状腺素分泌增加"],answer:[0],explanation:"过量磷可能造成非骨组织钙化，并可引起低血钙和神经肌肉兴奋性增强。",source:"教材第65页"},
  {id:"add-p-04",category:"磷",type:"multiple",stem:"容易出现磷缺乏的情况包括",options:["早产儿仅喂磷含量较低的母乳","长期大量使用抗酸药","肾小管重吸收障碍","长期禁食"],answer:[0,1,2,3],explanation:"这些情况均被教材列为磷缺乏的特殊原因。",source:"教材第65页"},

  {id:"add-mg-01",category:"镁",type:"single",stem:"正常成人体内镁主要分布在何处",options:["细胞外液","细胞内，尤其骨骼和组织细胞内","血浆白蛋白","胆汁"],answer:[1],explanation:"镁主要分布在细胞内，60%-65% 存在于骨骼，细胞外液中的镁不超过 1%。",source:"教材第65页"},
  {id:"add-mg-02",category:"镁",type:"single",stem:"镁参与体内大约多少种酶促反应",options:["30 多种","100 多种","300 多种","1000 多种"],answer:[2],explanation:"教材指出镁作为多种酶的激活剂，参与体内 300 多种酶促反应。",source:"教材第65页"},
  {id:"add-mg-03",category:"镁",type:"multiple",stem:"镁的生理作用包括",options:["激活 Na-K-ATP 酶","促进骨骼生长","碱性镁盐可中和胃酸","硫酸镁可松弛奥狄括约肌"],answer:[0,1,2,3],explanation:"镁既参与酶反应和骨骼功能，也影响胃肠道功能与胆汁排空。",source:"教材第65-66页"},
  {id:"add-mg-04",category:"镁",type:"single",stem:"镁的主要排泄途径是",options:["肾脏","皮肤汗液","肺呼气","乳汁"],answer:[0],explanation:"肾脏是镁排泄的主要途径，汗液和粪便排出的量较少。",source:"教材第66页"},
  {id:"add-mg-05",category:"镁",type:"single",stem:"24 小时尿镁排出量低于多少可诊断为镁缺乏症",options:["0.5 mmol","1.0 mmol","1.5 mmol","3.0 mmol"],answer:[2],explanation:"半定量尿负荷实验中，24 小时尿镁低于 1.5 mmol 可诊断为镁缺乏症。",source:"教材第66页"},
  {id:"add-mg-06",category:"镁",type:"multiple",stem:"镁过量更容易发生于",options:["肾功能不全者","接受镁剂治疗者","正常健康人摄入普通食物时","糖尿病酮症早期脱水者"],answer:[0,1,3],explanation:"肾功能不全、镁剂治疗以及糖尿病酮症早期均可能使血清镁升高；普通食物摄入通常不易导致镁中毒。",source:"教材第66页"},

  {id:"add-fe-01",category:"铁",type:"single",stem:"人体内铁总量约为",options:["3-4 mg/kg 体重","30-40 mg/kg 体重","300-400 mg/kg 体重","1-2 g/kg 体重"],answer:[1],explanation:"正常人体内含铁总量约为 30-40 mg/kg 体重。",source:"教材第67页"},
  {id:"add-fe-02",category:"铁",type:"single",stem:"人体铁中约有多少存在于血红蛋白",options:["5%-10%","25%-30%","65%-70%","90%-95%"],answer:[2],explanation:"约 65%-70% 的铁存在于血红蛋白，3% 在肌红蛋白，25%-30% 为储存铁。",source:"教材第67页"},
  {id:"add-fe-03",category:"铁",type:"single",stem:"运铁蛋白主要结合并转运哪种形式的铁",options:["Fe2+","Fe3+","游离铁原子","血红素铁颗粒"],answer:[1],explanation:"运铁蛋白是可逆结合 Fe3+ 的糖蛋白，负责将铁转运到需要铁的组织。",source:"教材第68页"},
  {id:"add-fe-04",category:"铁",type:"multiple",stem:"可促进铁吸收的膳食因素包括",options:["维生素 C","组氨酸、赖氨酸等氨基酸","蛋白质类食物","柠檬酸和乳酸"],answer:[0,1,2,3],explanation:"这些因素可通过还原、螯合成可溶性单体或促进胃酸分泌等方式促进铁吸收。",source:"教材第68页"},
  {id:"add-fe-05",category:"铁",type:"multiple",stem:"可阻碍铁吸收的因素包括",options:["植酸和单宁","多酚物质","过量铅、铬、锰","EDTA 等金属络合物"],answer:[0,1,2,3],explanation:"这些非营养素成分或矿物质可与铁结合或影响其吸收。",source:"教材第68页"},
  {id:"add-fe-06",category:"铁",type:"single",stem:"缺铁的第一阶段铁减少期首先表现为",options:["血红蛋白下降并出现贫血","储存铁减少、血清铁蛋白下降且无临床症状","血清铁升高、铁结合力下降","红细胞容积升高"],answer:[1],explanation:"第一阶段是铁减少期，储存铁减少、血清铁蛋白下降，但尚无临床症状。",source:"教材第69页"},
  {id:"add-fe-07",category:"铁",type:"single",stem:"缺铁第二阶段红细胞生成缺铁期的变化是",options:["血清铁降低、铁结合力上升","血清铁升高、铁结合力下降","血红蛋白先明显升高","血清铁蛋白恢复正常"],answer:[0],explanation:"第二阶段除血清铁蛋白下降外，还出现血清铁降低、铁结合力上升和游离原卟啉升高。",source:"教材第69页"},
  {id:"add-fe-08",category:"铁",type:"single",stem:"成年女性每天铁的生理性流失量约为",options:["0.15 mg","1.5 mg","15 mg","150 mg"],answer:[1],explanation:"女性因生理原因失铁较多，每天铁的流失约为 1.5 mg。",source:"教材第68页"},
  {id:"add-fe-09",category:"铁",type:"single",stem:"血清铁蛋白最适合反映机体的哪一方面",options:["近期铁摄入","体内铁储存","肠道铁吸收瞬时速度","红细胞平均体积"],answer:[1],explanation:"血清铁蛋白反映人体内铁储存，是诊断隐性缺铁性贫血较可靠的指标。",source:"教材第69页"},
  {id:"add-fe-10",category:"铁",type:"single",stem:"成年男性运铁蛋白饱和度低于多少通常认为存在铁缺乏",options:["5%","10%","16%","30%"],answer:[2],explanation:"一般成年人运铁蛋白饱和度低于 16% 认为是铁缺乏。",source:"教材第70页"},

  {id:"add-zn-01",category:"锌",type:"single",stem:"锌缺乏对儿童生长的直接影响主要是",options:["促进细胞分裂","造成生长发育停滞","使骨钙化过快","提高食欲"],answer:[1],explanation:"锌参与蛋白质合成、细胞生长分裂和分化，缺乏可导致儿童生长发育停滞。",source:"教材第71-72页"},
  {id:"add-zn-02",category:"锌",type:"single",stem:"成人摄入多少以上的锌可能观察到毒性症状",options:["40-80 mg","400-800 mg","4-8 g","40-80 g"],answer:[2],explanation:"教材指出成人摄入 4-8 g 以上锌可出现发热、腹泻、恶心、呕吐和嗜睡等毒性表现。",source:"教材第72页"},
  {id:"add-zn-03",category:"锌",type:"multiple",stem:"锌过量可能造成的影响包括",options:["干扰铜和铁的吸收利用","损害中性粒细胞和巨噬细胞功能","抑制细胞杀伤能力","损害免疫功能"],answer:[0,1,2,3],explanation:"锌过量不仅影响其他微量元素利用，还会损害吞噬细胞和免疫功能。",source:"教材第72页"},
  {id:"add-zn-04",category:"锌",type:"single",stem:"下列哪项可用于评价锌营养状况",options:["血清锌浓度和发锌浓度等指标综合判断","只看一次尿糖","只测血清钙","只测血红蛋白"],answer:[0],explanation:"教材的锌营养评价强调结合膳食调查、临床表现、血清锌、发锌和锌负荷试验等综合判断。",source:"教材第72页"},

  {id:"add-se-01",category:"硒",type:"single",stem:"缺硒导致克山病时，主要受损的器官是",options:["心脏","肝脏","甲状腺","小肠"],answer:[0],explanation:"克山病是以多发性灶状坏死为主要病变的心肌病，伴心脏扩大、心功能不全和心律失常。",source:"教材第74页"},
  {id:"add-se-02",category:"硒",type:"single",stem:"慢性硒中毒的典型表现不包括",options:["头发和指甲脱落","皮肤损伤","肢端麻木和抽搐","夜盲症"],answer:[3],explanation:"硒中毒可表现为脱发、脱甲、皮肤和神经系统异常，夜盲症属于维生素 A 缺乏表现。",source:"教材第74页"},
  {id:"add-se-03",category:"硒",type:"single",stem:"硒摄入量增加时，GSH-Px 活性在血硒达到何值后趋于饱和",options:["0.127 μmol/L","1.27 μmol/L","12.7 μmol/L","127 μmol/L"],answer:[1],explanation:"血硒达到 1.27 μmol/L（0.1 mg/L）时，GSH-Px 活性达饱和。",source:"教材第74页"},
  {id:"add-se-04",category:"硒",type:"single",stem:"膳食硒摄入量在不同地区差异较大，最重要的环境原因是",options:["土壤硒含量不同","空气湿度不同","日照时长不同","饮水温度不同"],answer:[0],explanation:"尤其是植物性食物的硒含量与地表土壤硒水平密切相关。",source:"教材第75页"},

  {id:"add-cr-01",category:"铬、碘与其他矿物质",type:"single",stem:"铬进入血液后主要与哪种蛋白结合运输",options:["运铁蛋白","视黄醇结合蛋白","内因子","胶原蛋白"],answer:[0],explanation:"铬进入血液后主要与运铁蛋白结合，部分与白蛋白结合。",source:"教材第75页"},
  {id:"add-cr-02",category:"铬、碘与其他矿物质",type:"single",stem:"摄入体内的铬约有多少以上从尿中排出",options:["25%","50%","75%","95%"],answer:[3],explanation:"摄入的铬约 95% 以上从尿中排出，少量从胆汁、毛发和皮肤排出。",source:"教材第75页"},
  {id:"add-cr-03",category:"铬、碘与其他矿物质",type:"single",stem:"目前成人膳食铬的参考摄入量形式和数值是",options:["RNI 30 μg/d","AI 30 μg/d","RNI 300 μg/d","UL 30 μg/d"],answer:[1],explanation:"目前资料不足以制定 UL，中国营养学会推荐成人铬 AI 为 30 μg/d。",source:"教材第76页"},
  {id:"add-cr-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"铬营养评价的特点包括",options:["目前缺乏可靠的评价指标","尿铬只适宜评价接受补铬者","血铬浓度很低且难检测","评价时需结合摄入调查、病史和临床表现"],answer:[0,1,2,3],explanation:"铬的营养评价较困难，不能仅依赖单一血、尿或发铬指标。",source:"教材第76页"},

  {id:"add-i-01",category:"铬、碘与其他矿物质",type:"single",stem:"在 TSH 刺激下，碘参与甲状腺激素合成时首先形成",options:["MIT 和 DIT","T3 和 T4 直接进入血液","TSH 和 PTH","尿碘和血碘"],answer:[0],explanation:"碘化酪氨酸残基形成一碘酪氨酸（MIT）和二碘酪氨酸（DIT），随后发生偶联。",source:"教材第77页"},
  {id:"add-i-02",category:"铬、碘与其他矿物质",type:"single",stem:"人体摄入的碘约有多少经尿排出",options:["10%","30%","60%","90%"],answer:[3],explanation:"体内碘主要经肾脏排泄，约 90% 随尿排出，10% 由粪便排出。",source:"教材第77页"},
  {id:"add-i-03",category:"铬、碘与其他矿物质",type:"single",stem:"长期大量摄入十字花科植物中的抗甲状腺素因子，可能导致",options:["碘缺乏和甲状腺肿","铁过量","坏血病","维生素 E 中毒"],answer:[0],explanation:"萝卜、甘蓝、花菜等十字花科植物中的相关成分可干扰甲状腺对碘的吸收利用。",source:"教材第77页"},
  {id:"add-i-04",category:"铬、碘与其他矿物质",type:"single",stem:"甲状腺肿大率超过多少可提示人群碘营养不良",options:["1%","5%","15%","25%"],answer:[1],explanation:"长期碘缺乏或过量均可增加甲状腺肿大率，甲状腺肿大率 >5% 提示人群碘营养不良。",source:"教材第78页"},
  {id:"add-i-05",category:"铬、碘与其他矿物质",type:"multiple",stem:"关于碘的食物来源，正确的是",options:["海产品含碘通常高于陆地食物","陆地动物性食物通常高于植物性食物","海带和海藻是富碘食物","鱼虾和贝类是常见来源"],answer:[0,1,2,3],explanation:"海产品、特别是海带、海藻、鱼虾和贝类，是教材列出的主要富碘食物。",source:"教材第78页"},

  {id:"add-cu-01",category:"铬、碘与其他矿物质",type:"single",stem:"铜主要在小肠的哪个部位吸收",options:["十二指肠","回肠末端","结肠","胃底"],answer:[0],explanation:"铜主要在十二指肠吸收，小肠末端和胃也可吸收少量。",source:"教材第78页"},
  {id:"add-cu-02",category:"铬、碘与其他矿物质",type:"single",stem:"铜的吸收率与摄入量的关系是",options:["正相关，摄入越多吸收越高","负相关，摄入越多吸收率越低","完全无关","只受年龄影响"],answer:[1],explanation:"铜吸收率与摄入量成负相关，教材给出的波动范围为 12%-75%。",source:"教材第78页"},
  {id:"add-cu-03",category:"铬、碘与其他矿物质",type:"single",stem:"出生后头两个月新生儿体内铜浓度约为成人的",options:["相同水平","1.5-2 倍","6-10 倍","20-30 倍"],answer:[2],explanation:"为满足婴儿期需要，出生后头两个月新生儿铜浓度约为成人的 6-10 倍。",source:"教材第78页"},
  {id:"add-cu-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"铜缺乏可能影响的功能包括",options:["铁转运和造血","神经髓鞘形成","胶原蛋白和弹性蛋白交联","抗氧化防御"],answer:[0,1,2,3],explanation:"铜通过铜蓝蛋白、含铜氧化酶、赖氨酰氧化酶和 SOD 等参与这些功能。",source:"教材第78页"},

  {id:"add-mn-01",category:"铬、碘与其他矿物质",type:"single",stem:"下列哪种膳食成分可促进锰吸收",options:["植酸盐","高铁摄入","膳食纤维","以上都不能"],answer:[2],explanation:"膳食纤维、钙和磷浓度增高可促进锰吸收，植酸盐和铁浓度增高则抑制吸收。",source:"教材第80页"},
  {id:"add-mn-02",category:"铬、碘与其他矿物质",type:"single",stem:"体内锰有多少以上主要由肠道排出",options:["10%","30%","60%","90%"],answer:[3],explanation:"锰除少量吸收利用外，90% 以上由肠道排出。",source:"教材第80页"},
  {id:"add-mn-03",category:"铬、碘与其他矿物质",type:"single",stem:"成人锰的 AI 和 UL 分别是",options:["4.5 mg/d 和 11 mg/d","11 mg/d 和 4.5 mg/d","0.45 mg/d 和 1.1 mg/d","45 mg/d 和 110 mg/d"],answer:[0],explanation:"中国营养学会推荐成人锰 AI 为 4.5 mg/d，UL 为 11 mg/d。",source:"教材第80页"},
  {id:"add-mn-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"锰摄入过量可能损害",options:["中枢神经系统","生殖内分泌功能","视紫红质合成","肠道吸收铁的全部功能"],answer:[0,1],explanation:"锰过量主要损害中枢神经系统，并可引起生殖内分泌功能紊乱。",source:"教材第80页"},

  {id:"add-f-01",category:"铬、碘与其他矿物质",type:"single",stem:"膳食氟约有多少由胃肠道迅速吸收入血",options:["10%-20%","30%-40%","50%-60%","75%-90%"],answer:[3],explanation:"膳食氟约 75%-90% 由胃肠道迅速吸收入血。",source:"教材第80页"},
  {id:"add-f-02",category:"铬、碘与其他矿物质",type:"single",stem:"氟的主要排泄器官是",options:["肾脏","肺脏","皮肤","肝脏"],answer:[0],explanation:"肾脏是无机氟的主要排泄途径，每天摄入氟约有 50% 从肾脏排出。",source:"教材第80页"},
  {id:"add-f-03",category:"铬、碘与其他矿物质",type:"single",stem:"慢性氟中毒对牙齿的典型危害是",options:["氟斑牙","毕脱氏斑","地图舌","反甲"],answer:[0],explanation:"慢性氟中毒可出现氟斑牙，表现为牙齿失去光泽、出现斑点、凹陷剥落和变脆。",source:"教材第80页"},
  {id:"add-f-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"慢性氟中毒的骨骼表现可能包括",options:["腰腿及关节疼痛","脊柱畸形","骨软化","骨质疏松"],answer:[0,1,2,3],explanation:"高氟地区长期摄入高氟饮水可发生氟骨症，出现这些骨骼表现。",source:"教材第80页"},

  {id:"add-vg-01",category:"维生素总论",type:"single",stem:"下列哪种维生素可由肠道细菌合成，但合成量不能完全满足需要",options:["维生素 K","维生素 A","维生素 E","维生素 C"],answer:[0],explanation:"维生素 K 和生物素可由肠道细菌合成，但不能完全替代食物来源。",source:"教材第83页"},
  {id:"add-vg-02",category:"维生素总论",type:"multiple",stem:"维生素缺乏的常见原因包括",options:["摄入不足","吸收利用降低","需要量相对增高","食物加工、烹调或储藏造成损失"],answer:[0,1,2,3],explanation:"维生素缺乏既可能来自摄入和食物处理，也可能来自吸收利用障碍或生理需要量增加。",source:"教材第83页"},
  {id:"add-vg-03",category:"维生素总论",type:"single",stem:"维生素缺乏从轻到重的一般发展顺序是",options:["临床症状→储存下降→生化异常","储存下降→生化和功能异常→组织病理改变及临床体征","食物中断→立即出现严重症状","生化异常→储存增加→临床恢复"],answer:[1],explanation:"教材强调维生素缺乏是渐进过程，先是组织储存降低，再出现生化和功能异常，最后出现病理和临床体征。",source:"教材第84页"},
  {id:"add-vg-04",category:"维生素总论",type:"single",stem:"轻度维生素缺乏但尚无明显临床症状的状态称为",options:["临床缺乏","亚临床缺乏或边缘缺乏","急性中毒","遗传性缺乏"],answer:[1],explanation:"亚临床缺乏常不出现明显症状，但可降低劳动效率和疾病抵抗力。",source:"教材第84页"},

  {id:"add-a-01",category:"维生素 A",type:"multiple",stem:"维生素 A 的活性形式包括",options:["视黄醇","视黄醛","视黄酸","视黄基棕榈酸酯"],answer:[0,1,2],explanation:"机体内维生素 A 的活性形式包括视黄醇、视黄醛和视黄酸；视黄基酯主要是储存形式。",source:"教材第84页"},
  {id:"add-a-02",category:"维生素 A",type:"single",stem:"约多少膳食 β-胡萝卜素可产生 1 mg 视黄醇活性",options:["1 mg","6 mg","12 mg","24 mg"],answer:[2],explanation:"教材提示约 12 mg 膳食 β-胡萝卜素可产生 1 mg 视黄醇活性，其他维生素 A 原类胡萝卜素约需 24 mg。",source:"教材第85页"},
  {id:"add-a-03",category:"维生素 A",type:"single",stem:"维生素 A 在小肠吸收时需要与脂肪酸等形成何种结构",options:["胶团","血红素","尿素循环","氟磷灰石"],answer:[0],explanation:"胆汁、胰脂酶和肠脂酶参与释放维生素 A，游离视黄醇和类胡萝卜素与脂溶性成分形成胶团后被吸收。",source:"教材第85页"},
  {id:"add-a-04",category:"维生素 A",type:"single",stem:"视黄醇与 RBP 结合后，在血浆中还会与哪种蛋白形成复合体",options:["转甲状腺素蛋白 TTR","运铁蛋白 Tf","维生素 D 结合蛋白 DBP","内因子 IF"],answer:[0],explanation:"视黄醇与 RBP 按 1:1 结合，并在血浆中与 TTR 形成视黄醇-RBP-TTR 复合体。",source:"教材第86页"},
  {id:"add-a-05",category:"维生素 A",type:"single",stem:"维生素 A 参与暗视觉的关键感光物质是",options:["视紫红质","血红蛋白","氟磷灰石","谷胱甘肽过氧化物酶"],answer:[0],explanation:"11-顺式视黄醛与视蛋白结合形成视紫红质，对暗视觉十分重要。",source:"教材第86页"},
  {id:"add-a-06",category:"维生素 A",type:"multiple",stem:"维生素 A 的生理功能包括",options:["维持视觉","调节细胞生长和分化","维护上皮组织屏障","增强免疫功能"],answer:[0,1,2,3],explanation:"维生素 A 通过视紫红质、RAR/RXR 受体、上皮组织和免疫调节发挥这些作用。",source:"教材第86-87页"},
  {id:"add-a-07",category:"维生素 A",type:"single",stem:"维生素 A 在体内主要通过哪条途径排泄",options:["代谢产物经胆汁入粪便","原形经肺呼出","全部经汗液排出","全部经尿液排出"],answer:[0],explanation:"约 70% 的维生素 A 代谢产物经胆汁进入粪便排泄，约 30% 由肾脏排泄。",source:"教材第86页"},
  {id:"add-a-08",category:"维生素 A",type:"single",stem:"评价人群维生素 A 缺乏程度常用的血清视黄醇界值是",options:["<0.07 μmol/L","<0.70 μmol/L","<7.0 μmol/L","<70 μmol/L"],answer:[1],explanation:"6-72 月龄婴幼儿、儿童及孕妇血清视黄醇 <0.70 μmol/L 的比例可用于评价人群缺乏程度。",source:"教材第89页"},

  {id:"add-d-01",category:"维生素 D",type:"single",stem:"食物维生素 D 在小肠的吸收率大约为",options:["5%-10%","20%-30%","50%-80%","90%-100%"],answer:[2],explanation:"食物中约 50%-80% 的维生素 D 在小肠吸收。",source:"教材第91页"},
  {id:"add-d-02",category:"维生素 D",type:"single",stem:"维生素 D3 在肝脏首先被转化为",options:["25-(OH)-D3","1,25-(OH)2-D3","24,25-(OH)2-D3","胆钙化醇结合蛋白"],answer:[0],explanation:"肝脏 D3-25-羟化酶将维生素 D3 转化为 25-(OH)-D3，随后在肾脏进一步活化。",source:"教材第91页"},
  {id:"add-d-03",category:"维生素 D",type:"multiple",stem:"可刺激肾脏 25-(OH)-D3-1α-羟化酶活性的因素包括",options:["甲状旁腺素升高","血钙降低","活性维生素 D 浓度降低","低磷膳食摄入"],answer:[0,1,2,3],explanation:"PTH、低钙、低活性维生素 D 和低磷膳食可刺激该羟化酶，促进活性维生素 D 生成。",source:"教材第91页"},
  {id:"add-d-04",category:"维生素 D",type:"single",stem:"血中 25-(OH)-D3 低于多少可认为维生素 D 严重缺乏",options:["<5 ng/ml","<10 ng/ml","<20 ng/ml","<30 ng/ml"],answer:[1],explanation:"教材给出的分级为 <10 ng/ml 严重缺乏，<20 ng/ml 缺乏，21-29 ng/ml 不足，≥30 ng/ml 充足。",source:"教材第93页"},
  {id:"add-d-05",category:"维生素 D",type:"single",stem:"维生素 D 的单位换算正确的是",options:["1 IU=0.025 μg","1 IU=0.25 μg","1 μg=4 IU","1 μg=400 IU"],answer:[0],explanation:"1 IU 维生素 D = 0.025 μg，即 1 μg = 40 IU。",source:"教材第93页"},
  {id:"add-d-06",category:"维生素 D",type:"single",stem:"11 岁及以上人群维生素 D 的 UL 是",options:["20 μg/d","30 μg/d","45 μg/d","50 μg/d"],answer:[3],explanation:"11 岁及以上人群（包括孕妇、乳母）的 UL 为 50 μg/d。",source:"教材第93页"},
  {id:"add-d-07",category:"维生素 D",type:"multiple",stem:"维生素 D 中毒可能出现",options:["血清钙、磷升高","软组织转移性钙化","肾结石","多尿、烦渴和恶心呕吐"],answer:[0,1,2,3],explanation:"维生素 D 过量会导致高钙高磷及相关胃肠、泌尿和软组织钙化表现。",source:"教材第93页"},

  {id:"add-e-01",category:"维生素 E",type:"single",stem:"维生素 E 的吸收需要胆汁帮助形成",options:["胶团","胆红素","内因子复合物","含铁血黄素"],answer:[0],explanation:"生育酚与脂类消化产物在胆汁作用下形成胶团，被动扩散吸收。",source:"教材第94页"},
  {id:"add-e-02",category:"维生素 E",type:"single",stem:"维生素 E 在血液中主要由哪类脂蛋白运输",options:["LDL","HDL 以外的乳酸","纤维蛋白原","运铁蛋白"],answer:[0],explanation:"维生素 E 可由多种脂蛋白运输，其中主要由 LDL 运输，并保护 LDL 免受氧化。",source:"教材第94页"},
  {id:"add-e-03",category:"维生素 E",type:"single",stem:"维生素 E 的吸收率与摄入量增加的关系是",options:["吸收率随摄入量增加而降低","吸收率随摄入量增加而无限升高","完全不受摄入量影响","只在儿童中降低"],answer:[0],explanation:"维生素 E 一般吸收率为 20%-50%，最高约 80%，摄入量增加时吸收率降低。",source:"教材第94页"},
  {id:"add-e-04",category:"维生素 E",type:"single",stem:"维生素 E 缺乏在人群中较常见于",options:["低体重早产儿和脂肪吸收障碍者","所有健康成年人","只吃水果者但无吸收障碍","短期高脂膳食者"],answer:[0],explanation:"维生素 E 缺乏在人类较少见，低体重早产儿、脂蛋白缺乏和脂肪吸收障碍者风险较高。",source:"教材第95页"},
  {id:"add-e-05",category:"维生素 E",type:"single",stem:"成人维生素 E 的 AI 是",options:["7 mg α-TE/d","14 mg α-TE/d","17 mg α-TE/d","40 mg α-TE/d"],answer:[1],explanation:"我国成人（包括孕妇）维生素 E AI 为 14 mg α-TE/d，乳母为 17 mg α-TE/d。",source:"教材第95页"},
  {id:"add-e-06",category:"维生素 E",type:"multiple",stem:"维生素 E 含量较丰富的食物包括",options:["植物油","麦胚和谷类胚芽","坚果和种子","豆类"],answer:[0,1,2,3],explanation:"植物油、麦胚、坚果、种子、豆类和谷类胚芽是维生素 E 的主要食物来源。",source:"教材第96页"},

  {id:"add-b1-01",category:"维生素 B1",type:"single",stem:"维生素 B1 在低浓度时主要通过何种方式吸收",options:["主动转运","简单扩散","吞噬作用","胆汁排泄"],answer:[0],explanation:"B1 浓度低（≤2 μmol/L）时主要主动转运，需要 Na+ 并消耗 ATP；浓度高时可被动扩散。",source:"教材第96页"},
  {id:"add-b1-02",category:"维生素 B1",type:"single",stem:"成人体内维生素 B1 约有多少分布在肌肉中",options:["10%","25%","50%","80%"],answer:[2],explanation:"成人体内维生素 B1 总量约 25-30 mg，约 50% 分布在肌肉中。",source:"教材第96页"},
  {id:"add-b1-03",category:"维生素 B1",type:"single",stem:"维生素 B1 的生物半衰期约为",options:["9-18 小时","9-18 天","9-18 周","9-18 个月"],answer:[1],explanation:"维生素 B1 在体内的生物半衰期为 9-18 天，缺乏膳食 1-2 周后组织含量即可下降。",source:"教材第96页"},
  {id:"add-b1-04",category:"维生素 B1",type:"single",stem:"成人干性脚气病主要表现为",options:["多发性周围神经炎","严重水肿和心衰","皮炎腹泻痴呆","牙龈出血"],answer:[0],explanation:"干性脚气病以多发性周围神经炎为主；湿性脚气病以水肿和心脏症状为主。",source:"教材第97页"},
  {id:"add-b1-05",category:"维生素 B1",type:"single",stem:"婴儿脚气病多发生于哪个年龄阶段",options:["出生后 1-2 周","2-5 月龄","1-2 岁","学龄期"],answer:[1],explanation:"婴儿脚气病多发生于 2-5 月龄，常与乳母维生素 B1 缺乏有关。",source:"教材第97页"},
  {id:"add-b1-06",category:"维生素 B1",type:"single",stem:"红细胞转酮醇酶 TPP 效应越高，通常说明",options:["维生素 B1 越充足","维生素 B1 缺乏越严重","铁储存越多","叶酸吸收越好"],answer:[1],explanation:"加入 TPP 前后转酮醇酶活性差异越大，说明体内酶对 TPP 越依赖，维生素 B1 缺乏越严重。",source:"教材第98页"},
  {id:"add-b1-07",category:"维生素 B1",type:"multiple",stem:"导致食物中维生素 B1 损失的操作包括",options:["米面碾磨过于精细","过分淘米","烹调中加碱","高温烹调"],answer:[0,1,2,3],explanation:"B1 多存在于谷类表皮和胚芽，易溶于水且在碱性和高温条件下损失。",source:"教材第98页"},

  {id:"add-b2-01",category:"维生素 B2",type:"single",stem:"动物来源的维生素 B2 与植物来源相比通常",options:["更容易吸收","更难吸收","完全不能吸收","只在肝脏吸收"],answer:[0],explanation:"教材指出动物来源的维生素 B2 比植物来源的维生素 B2 更容易吸收。",source:"教材第99页"},
  {id:"add-b2-02",category:"维生素 B2",type:"single",stem:"血浆中运输维生素 B2、FMN 和 FAD 的主要蛋白是",options:["白蛋白","运铁蛋白","RBP","TTR"],answer:[0],explanation:"血浆白蛋白、免疫球蛋白和纤维蛋白原可运输 B2，白蛋白是主要运输载体。",source:"教材第99页"},
  {id:"add-b2-03",category:"维生素 B2",type:"single",stem:"维生素 B2 缺乏时典型的舌部表现是",options:["地图舌","草莓舌伴牙龈出血","蓝舌","舌乳头完全增生"],answer:[0],explanation:"B2 缺乏可出现舌炎、舌乳头萎缩，典型表现为地图舌。",source:"教材第100页"},
  {id:"add-b2-04",category:"维生素 B2",type:"single",stem:"口服 5 mg 维生素 B2 后，4 小时尿排出量低于多少提示缺乏",options:["40 μg","200 μg","400 μg","800 μg"],answer:[2],explanation:"B2 尿负荷试验中，4 小时尿排出量 ≤400 μg 为缺乏，400-799 μg 为不足。",source:"教材第100页"},
  {id:"add-b2-05",category:"维生素 B2",type:"single",stem:"维生素 B2 含量较丰富的动物性食物是",options:["动物肝脏、肾脏和心脏","精制植物油","苹果和梨","白砂糖"],answer:[0],explanation:"动物肝、肾、心、乳汁和蛋类含 B2 较丰富，绿色蔬菜和豆类也是植物来源。",source:"教材第100页"},
  {id:"add-b2-06",category:"维生素 B2",type:"multiple",stem:"影响维生素 B2 吸收或稳定性的因素包括",options:["抗酸制剂干扰释放","酒精干扰消化吸收","碱性环境易破坏","光照可造成损失"],answer:[0,1,2,3],explanation:"B2 的释放和吸收受胃酸、胆盐、抗酸制剂和酒精影响，游离 B2 对光敏感，碱性环境中易受破坏。",source:"教材第99-100页"},

  {id:"add-niacin-01",category:"烟酸",type:"single",stem:"烟酸和烟酰胺在体内的生理活性关系是",options:["二者具有相同生理活性","只有烟酸有活性","只有烟酰胺有活性","二者均无活性"],answer:[0],explanation:"烟酸在体内易转变为烟酰胺，两者总称维生素 PP，具有相同生理活性。",source:"教材第101页"},
  {id:"add-niacin-02",category:"烟酸",type:"single",stem:"烟酸在体内构成的主要辅酶是",options:["NAD 和 NADP","FMN 和 FAD","TPP 和 TTP","PLP 和 PMP"],answer:[0],explanation:"烟酸以烟酰胺形式构成辅酶 I（NAD）和辅酶 II（NADP），参与氢的传递。",source:"教材第101页"},
  {id:"add-niacin-03",category:"烟酸",type:"single",stem:"烟酸是维生素中较稳定的一种，通常烹调损失较小，但容易随什么流失",options:["水","脂肪","蛋白质","矿物质沉淀"],answer:[0],explanation:"烟酸对酸、碱、光、氧和加热较稳定，一般烹调损失小，但可随水流失。",source:"教材第101页"},
  {id:"add-niacin-04",category:"烟酸",type:"single",stem:"尿中 2-吡啶酮/N-甲基烟酰胺比值低于多少提示潜在烟酸缺乏",options:["0.3","1.3","2.0","4.0"],answer:[1],explanation:"该比值 1.3-4.0 为正常，低于 1.3 表示有潜在性缺乏。",source:"教材第102页"},
  {id:"add-niacin-05",category:"烟酸",type:"single",stem:"成年男性烟酸的 RNI 是",options:["5 mg NE/d","12 mg NE/d","15 mg NE/d","35 mg NE/d"],answer:[2],explanation:"成年男性烟酸 RNI 为 15 mg NE/d，女性为 12 mg NE/d，UL 为 35 mg NE/d。",source:"教材第102页"},
  {id:"add-niacin-06",category:"烟酸",type:"multiple",stem:"烟酸过量可能产生的副作用包括",options:["皮肤发红","恶心呕吐","高尿酸血症","糖耐量异常"],answer:[0,1,2,3],explanation:"大剂量烟酸可能出现皮肤潮红、胃肠道反应、高尿酸血症和糖耐量异常，长期更大剂量可损伤肝脏。",source:"教材第101页"},

  {id:"add-pan-01",category:"泛酸",type:"single",stem:"低浓度泛酸主要通过何种方式吸收",options:["主动转运","简单扩散","吞噬作用","肾小管重吸收"],answer:[0],explanation:"泛酸在低浓度时主动转运，高浓度时以简单扩散吸收。",source:"教材第102页"},
  {id:"add-pan-02",category:"泛酸",type:"single",stem:"正常膳食成年人尿中泛酸排出量约为",options:["0.2-0.7 mg/d","2-7 mg/d","20-70 mg/d","200-700 mg/d"],answer:[1],explanation:"正常膳食成年人尿中泛酸排出量约 2-7 mg/d，低于 1 mg/d 可提示不足或缺乏。",source:"教材第103页"},
  {id:"add-pan-03",category:"泛酸",type:"single",stem:"泛酸又被称为抗应激维生素的原因是",options:["可减少应激反应中的能量消耗","可直接降低体温","可阻断所有神经冲动","可提高尿钙排出"],answer:[0],explanation:"应激反应伴随大量能量消耗，泛酸参与辅酶 A 代谢并可减少应激时的能量消耗。",source:"教材第103页"},
  {id:"add-pan-04",category:"泛酸",type:"single",stem:"泛酸 AI 的人群差异正确的是",options:["成人 5.0、孕妇 6.0、乳母 7.0 mg/d","成人 7.0、孕妇 6.0、乳母 5.0 mg/d","三者均为 1.0 mg/d","三者均无 AI"],answer:[0],explanation:"2013 版成人 AI 为 5.0 mg/d，孕妇 6.0 mg/d，乳母 7.0 mg/d。",source:"教材第103页"},

  {id:"add-b6-01",category:"维生素 B6",type:"single",stem:"维生素 B6 在肝脏中可转化为多种磷酸化形式，其中主要活性形式是",options:["PLP","PNP","PMP","三者均无活性"],answer:[0],explanation:"维生素 B6 包括吡哆醇、吡哆醛和吡哆胺，PLP 是体内主要活性形式。",source:"教材第104页"},
  {id:"add-b6-02",category:"维生素 B6",type:"single",stem:"维生素 B6 的主要储存部位是",options:["肌肉组织","皮肤角质层","甲状腺","胃腔"],answer:[0],explanation:"组织中维生素 B6 以 PLP 形式储存，肌肉约占储存量的 75%-80%。",source:"教材第104页"},
  {id:"add-b6-03",category:"维生素 B6",type:"single",stem:"异烟肼可诱发维生素 B6 缺乏的原因是",options:["与 PLP 形成复合物","促进 B6 从尿中完全排出","抑制维生素 C 合成","使 B6 转化为维生素 D"],answer:[0],explanation:"异烟肼、环丝氨酸等药物可与 PLP 形成复合物，诱发 B6 缺乏。",source:"教材第104页"},
  {id:"add-b6-04",category:"维生素 B6",type:"single",stem:"色氨酸负荷试验中，维生素 B6 缺乏时尿中哪种物质增加",options:["黄尿酸","甲基丙二酸","FIGLU","尿碘"],answer:[0],explanation:"B6 缺乏时色氨酸代谢受影响，尿中黄尿酸增加，可计算黄尿酸指数评价营养状况。",source:"教材第105页"},
  {id:"add-b6-05",category:"维生素 B6",type:"single",stem:"成人维生素 B6 的 RNI 是",options:["0.4 mg/d","1.4 mg/d","2.4 mg/d","14 mg/d"],answer:[1],explanation:"2013 版成人 B6 RNI 为 1.4 mg/d，妊娠期为 2.4 mg/d。",source:"教材第105页"},
  {id:"add-b6-06",category:"维生素 B6",type:"multiple",stem:"维生素 B6 含量较高的食物包括",options:["鸡肉和鱼肉等白色肉类","肝脏","豆类和坚果","香蕉和卷心菜"],answer:[0,1,2,3],explanation:"白色肉类最丰富，肝脏、豆类、坚果、蛋黄以及部分水果蔬菜也是来源。",source:"教材第105页"},

  {id:"add-biotin-01",category:"生物素",type:"single",stem:"生物素在低浓度时主要以何种方式吸收",options:["主动转运","简单扩散","胆汁乳化","肾小球滤过"],answer:[0],explanation:"生物素在低浓度时主动转运，高浓度时以简单扩散吸收，主要吸收部位是小肠近端。",source:"教材第106页"},
  {id:"add-biotin-02",category:"生物素",type:"single",stem:"长期服用抗生素可能导致生物素缺乏的原因是",options:["抑制肠道细菌合成生物素","破坏肝脏储存蛋白","增加视黄醇排出","促进铁吸收过快"],answer:[0],explanation:"抗生素可抑制肠道细菌合成生物素，当膳食摄入不足时可能导致缺乏。",source:"教材第106页"},
  {id:"add-biotin-03",category:"生物素",type:"single",stem:"生物素缺乏时尿中哪种代谢物会增加",options:["3-羟基异戊酸","甲基丙二酸","2-吡啶酮","尿素"],answer:[0],explanation:"生物素缺乏时尿 3-羟基异戊酸排出量增加，正常成人约 77-195 μmol/24h。",source:"教材第106页"},
  {id:"add-biotin-04",category:"生物素",type:"single",stem:"生物素的成人 AI 是",options:["4 μg/d","40 μg/d","400 μg/d","4 mg/d"],answer:[1],explanation:"2013 版中国居民膳食营养素参考摄入量中，生物素成人 AI 为 40 μg/d。",source:"教材第106页"},
  {id:"add-biotin-05",category:"生物素",type:"multiple",stem:"生物素缺乏的风险因素包括",options:["长期生吃蛋清","长期全静脉营养未补生物素","长期服用苯妥因等抗惊厥药","母乳中生物素不足的婴儿"],answer:[0,1,2,3],explanation:"这些情况可分别通过抗生物素蛋白、缺少肠道来源或药物影响造成生物素缺乏。",source:"教材第106页"},

  {id:"add-folate-01",category:"叶酸",type:"single",stem:"叶酸在小肠吸收前，需要被水解为哪种形式",options:["单谷氨酸叶酸","多谷氨酸叶酸","视黄酸","甲基丙二酸"],answer:[0],explanation:"膳食多谷氨酸叶酸需经空肠刷状缘 γ-谷氨酰水解酶水解为单谷氨酸叶酸后吸收。",source:"教材第107页"},
  {id:"add-folate-02",category:"叶酸",type:"multiple",stem:"可影响叶酸吸收的因素包括",options:["维生素 C 和葡萄糖可促进吸收","锌缺乏可降低叶酸结合酶活性","酒精可抑制吸收","口服避孕药和抗惊厥药物可抑制吸收"],answer:[0,1,2,3],explanation:"这些因素均会影响叶酸的吸收或利用。",source:"教材第107页"},
  {id:"add-folate-03",category:"叶酸",type:"single",stem:"正常成人体内叶酸约有多少储存在肝脏",options:["5%","25%","50%","90%"],answer:[2],explanation:"正常成人叶酸储存量约 5-10 mg，其中约 50% 储存在肝脏。",source:"教材第107页"},
  {id:"add-folate-04",category:"叶酸",type:"single",stem:"红细胞叶酸含量主要反映",options:["近期膳食叶酸摄入","组织细胞内的长期叶酸储存","当日尿量","维生素 B12 的吸收"],answer:[1],explanation:"血清叶酸偏向反映近期摄入，红细胞叶酸反映组织细胞储存和长期营养状况。",source:"教材第108页"},
  {id:"add-folate-05",category:"叶酸",type:"single",stem:"血清总叶酸低于何值可判断为缺乏",options:["1 ng/ml","3 ng/ml","6 ng/ml","16 ng/ml"],answer:[1],explanation:"血清总叶酸 <3 ng/ml 为缺乏，3-6 ng/ml 为不足，>6 ng/ml 为正常。",source:"教材第108页"},
  {id:"add-folate-06",category:"叶酸",type:"single",stem:"叶酸缺乏时，组氨酸负荷试验中尿 FIGLU 排出量会",options:["减少至零","增加","保持不变且与 B12 无关","转化为尿碘"],answer:[1],explanation:"叶酸缺乏时 FIGLU 不能顺利转化为谷氨酸，尿中排出量增加，但 B12 缺乏也可导致增加。",source:"教材第108页"},
  {id:"add-folate-07",category:"叶酸",type:"multiple",stem:"大剂量叶酸可能带来的问题包括",options:["影响锌吸收并导致锌缺乏","掩盖维生素 B12 缺乏","干扰抗惊厥药物作用","可能增加胎儿发育异常风险"],answer:[0,1,2,3],explanation:"叶酸大剂量并非完全无风险，教材列出了这些潜在问题。",source:"教材第108页"},

  {id:"add-b12-01",category:"维生素 B12",type:"single",stem:"维生素 B12 的两种活性辅酶形式是",options:["甲基 B12 和辅酶 B12","TPP 和 TTP","FMN 和 FAD","NAD 和 NADP"],answer:[0],explanation:"B12 以甲基钴胺素和 5-脱氧腺苷钴胺素两种辅酶形式参与体内反应。",source:"教材第109页"},
  {id:"add-b12-02",category:"维生素 B12",type:"single",stem:"维生素 B12-内因子复合物主要在哪个部位被吸收",options:["胃","十二指肠","回肠","结肠"],answer:[2],explanation:"B12 与内因子结合后，复合物在回肠黏膜受体处被吸收。",source:"教材第109页"},
  {id:"add-b12-03",category:"维生素 B12",type:"single",stem:"人体内维生素 B12 主要储存于",options:["肝脏","皮肤","骨骼肌","肺脏"],answer:[0],explanation:"体内 B12 储存量约 2-3 mg，主要储存在肝脏，肝肠循环有利于重复利用。",source:"教材第109页"},
  {id:"add-b12-04",category:"维生素 B12",type:"single",stem:"血清维生素 B12 浓度通常反映",options:["体内储存状况","当日膳食纤维摄入","近期尿碘","骨密度"],answer:[0],explanation:"血清 B12 浓度是反映体内储存的指标，教材给出的正常范围为 120-180 pmol/L。",source:"教材第110页"},
  {id:"add-b12-05",category:"维生素 B12",type:"single",stem:"holoTC II 主要反映维生素 B12 的哪种状态",options:["负平衡的早期状态","严重中毒","骨骼储存","维生素 C 吸收"],answer:[0],explanation:"血清全钴胺传递蛋白 II（holoTC II）是 B12 负平衡的早期指标。",source:"教材第110页"},
  {id:"add-b12-06",category:"维生素 B12",type:"single",stem:"维生素 B12 缺乏时，下列哪两种物质会升高",options:["同型半胱氨酸和甲基丙二酸","尿碘和血钙","血清铁和视黄醇","FIGLU 和尿素"],answer:[0],explanation:"B12 缺乏时同型半胱氨酸和甲基丙二酸含量均可升高。",source:"教材第110页"},
  {id:"add-b12-07",category:"维生素 B12",type:"single",stem:"成人维生素 B12 的 RNI 是",options:["0.24 μg/d","2.4 μg/d","24 μg/d","240 μg/d"],answer:[1],explanation:"成人 B12 RNI 为 2.4 μg/d，孕妇 2.9 μg/d，乳母 3.2 μg/d。",source:"教材第110页"},

  {id:"add-c-01",category:"维生素 C",type:"single",stem:"维生素 C 主要在小肠以何种方式吸收",options:["主动转运","被动滤过","胆汁乳化后吞噬","胃内扩散"],answer:[0],explanation:"维生素 C 主要通过主动转运由小肠上段吸收。",source:"教材第111页"},
  {id:"add-c-02",category:"维生素 C",type:"single",stem:"下列哪种动物与人一样不能在体内合成维生素 C",options:["豚鼠","牛","羊","鸡"],answer:[0],explanation:"人、猴和豚鼠体内不能利用葡萄糖合成维生素 C，需要由食物供给。",source:"教材第111页"},
  {id:"add-c-03",category:"维生素 C",type:"single",stem:"正常成人体内维生素 C 的储存量约为",options:["12-20 mg","120-200 mg","1.2-2.0 g","12-20 g"],answer:[2],explanation:"正常成人体内可储存维生素 C 约 1.2-2.0 g，最高约 3.0 g。",source:"教材第111页"},
  {id:"add-c-04",category:"维生素 C",type:"single",stem:"维生素 C 在体内含量最高的组织是",options:["垂体","血浆","唾液","脂肪组织"],answer:[0],explanation:"维生素 C 含量最高的组织是垂体，其次为肾上腺、肾脏、脾脏和肝脏。",source:"教材第111页"},
  {id:"add-c-05",category:"维生素 C",type:"single",stem:"一次口服维生素 C 2-3 g 可能出现的反应是",options:["腹泻和腹胀","肾上腺皮质增生","严重甲状腺肿","神经脱髓鞘"],answer:[0],explanation:"维生素 C 毒性较低，但一次口服 2-3 g 可能出现腹泻、腹胀；结石患者长期过量还可能增加风险。",source:"教材第112页"},
  {id:"add-c-06",category:"维生素 C",type:"single",stem:"尿负荷试验中，4 小时尿维生素 C 排出量低于多少提示不足",options:["1 mg","5 mg","13 mg","50 mg"],answer:[1],explanation:"口服 500 mg 后，4 小时尿排出 >13 mg 为充足，5-13 mg 为正常，<5 mg 为不足。",source:"教材第112页"},
  {id:"add-c-07",category:"维生素 C",type:"multiple",stem:"减少蔬菜烹调中维生素 C 损失的方法包括",options:["急火快炒","用淀粉勾芡","加醋烹调","长时间浸泡后再烹调"],answer:[0,1,2],explanation:"急火快炒、淀粉勾芡和加醋可减少维生素 C 损失，长时间浸泡会增加水溶性维生素流失。",source:"教材第113页"},
  {id:"add-c-08",category:"维生素 C",type:"single",stem:"中国营养学会推荐成人维生素 C 的 RNI 是",options:["50 mg/d","100 mg/d","200 mg/d","2000 mg/d"],answer:[1],explanation:"成人维生素 C RNI 为 100 mg/d，PI-NCD 为 200 mg/d，UL 为 2000 mg/d。",source:"教材第113页"}
];
