// 题库依据《营养学基础》教材第 65-113 页整理。每题只设置一个主考点。
window.QUESTION_BANK = [
  {id:"m-p-01",category:"磷",type:"single",stem:"正常成人血清无机磷的参考范围是",options:["0.20-0.50 mmol/L","0.87-1.45 mmol/L","1.80-2.50 mmol/L","2.80-3.45 mmol/L"],answer:[1],explanation:"血清无机磷水平可用于评价磷营养状况，正常成人范围为 0.87-1.45 mmol/L。",source:"教材第65页"},
  {id:"m-p-02",category:"磷",type:"multiple",stem:"关于膳食磷，下列说法正确的是",options:["动物性和植物性食物中都含有磷","谷类中的磷主要以植酸磷形式存在","谷类植酸磷与钙结合后不易吸收","成人磷的 RNI 为 720 mg/d"],answer:[0,1,2,3],explanation:"教材指出磷广泛存在于动植物食物中；谷类磷多为植酸磷，与钙结合后吸收较差。成人 RNI 为 720 mg/d。",source:"教材第65页"},
  {id:"m-mg-01",category:"镁",type:"single",stem:"正常成人摄入的镁，约有多少在小肠吸收",options:["5%-10%","30%-50%","60%-70%","80%-95%"],answer:[1],explanation:"镁在小肠的吸收率约为 30%-50%，摄入量较低时吸收率会提高。",source:"教材第66页"},
  {id:"m-mg-02",category:"镁",type:"single",stem:"血清镁低于何值可诊断为低镁血症",options:["0.30 mmol/L","0.50 mmol/L","0.70 mmol/L","1.20 mmol/L"],answer:[2],explanation:"血清镁低于 0.7 mmol/L 即可诊断为低镁血症。",source:"教材第66页"},
  {id:"m-mg-03",category:"镁",type:"multiple",stem:"镁缺乏可能出现的表现包括",options:["肌肉震颤和手足搐搦","低钾血症和低钙血症","反射亢进和共济失调","膝腱反射减弱、肌麻痹"],answer:[0,1,2],explanation:"镁缺乏常导致神经肌肉兴奋性亢进、低钾和低钙；膝腱反射减弱、肌麻痹主要见于镁过量。",source:"教材第66页"},
  {id:"m-mg-04",category:"镁",type:"single",stem:"成人膳食镁的 RNI 是",options:["120 mg/d","220 mg/d","330 mg/d","600 mg/d"],answer:[2],explanation:"中国营养学会推荐成人膳食镁 RNI 为 330 mg/d，2013 版暂不制定镁的 UL。",source:"教材第67页"},
  {id:"m-mg-05",category:"镁",type:"multiple",stem:"关于镁的食物来源，正确的是",options:["绿叶蔬菜含镁较丰富","糙粮和坚果含镁较丰富","硬水中的镁通常高于软水","精加工食物的镁含量通常最低"],answer:[0,1,2,3],explanation:"绿叶蔬菜、糙粮、坚果和硬水都是镁的来源；精加工会使食物镁含量降低。",source:"教材第67页"},
  {id:"m-fe-01",category:"铁",type:"single",stem:"人体内铁的主要功能性储存形式是",options:["血红蛋白中的铁","肌红蛋白中的铁","铁蛋白和含铁血黄素","运铁蛋白受体中的铁"],answer:[2],explanation:"剩余的 25%-30% 铁为储存铁，主要以铁蛋白和含铁血黄素形式储存在肝、脾和骨髓。",source:"教材第67页"},
  {id:"m-fe-02",category:"铁",type:"single",stem:"食物中的铁主要在哪一部位吸收",options:["胃底和胃体","十二指肠和空肠上端","回肠末端","结肠"],answer:[1],explanation:"铁的吸收主要发生在十二指肠和空肠上端。",source:"教材第68页"},
  {id:"m-fe-03",category:"铁",type:"multiple",stem:"关于血红素铁和非血红素铁，正确的是",options:["血红素铁主要来自动物性食物","非血红素铁常以 Fe3+ 形式存在","非血红素铁需还原为 Fe2+ 后吸收","血红素铁受膳食因素影响相对较小"],answer:[0,1,2,3],explanation:"血红素铁吸收率较高且受膳食因素影响较小；非血红素铁通常须先还原为 Fe2+，受膳食因素影响较大。",source:"教材第68页"},
  {id:"m-fe-04",category:"铁",type:"single",stem:"血红素铁的有效吸收率约为",options:["1%-5%","2%-20%","15%-35%","50%-80%"],answer:[2],explanation:"教材给出的血红素铁有效吸收率为 15%-35%，非血红素铁为 2%-20%。",source:"教材第68页"},
  {id:"m-fe-05",category:"铁",type:"single",stem:"维生素 C 促进非血红素铁吸收的关键作用是",options:["把 Fe2+ 氧化为 Fe3+","把 Fe3+ 还原为 Fe2+","抑制胃酸分泌","促进铁以离子形式自由通过细胞"],answer:[1],explanation:"非血红素铁需先还原为二价铁，维生素 C 是这一过程的重要促进因子。",source:"教材第68页"},
  {id:"m-fe-06",category:"铁",type:"single",stem:"缺铁性贫血的典型红细胞指标组合是",options:["高 MCV、高 RDW","低 MCV、低 RDW","低 MCV、高 RDW","高 MCV、正常 RDW"],answer:[2],explanation:"缺铁性贫血通常表现为 MCV <80 fL、RDW >15%，即红细胞体积偏小且大小不均。",source:"教材第70页"},
  {id:"m-fe-07",category:"铁",type:"multiple",stem:"关于铁营养评价，正确的是",options:["血清铁蛋白可反映体内铁储存","sTfR 不受感染或炎症影响，早期缺铁即可升高","血红蛋白是缺铁的晚期指标","成年人的运铁蛋白饱和度低于 16% 提示缺铁"],answer:[0,1,2,3],explanation:"这四项均为教材列出的铁评价要点。血清铁本身受进食、生理状态和溶血等影响，临床价值相对有限。",source:"教材第69-70页"},
  {id:"m-fe-08",category:"铁",type:"single",stem:"体内铁过量时最主要的靶器官是",options:["肝脏","甲状腺","骨骼肌","皮肤"],answer:[0],explanation:"铁过量可引起肝纤维化和肝细胞瘤，肝脏是主要受损靶器官。",source:"教材第69页"},
  {id:"m-zn-01",category:"锌",type:"single",stem:"锌参与维持下列哪类酶的活性",options:["RNA 和 DNA 聚合酶","胃蛋白酶","凝血因子","胆汁酸合成酶"],answer:[0],explanation:"锌是维持 RNA 聚合酶、DNA 聚合酶和反转录酶活性所必需的微量元素。",source:"教材第71页"},
  {id:"m-zn-02",category:"锌",type:"multiple",stem:"锌缺乏可能导致",options:["食欲减退和异食癖","儿童生长发育停滞","成人性功能减退","免疫力降低"],answer:[0,1,2,3],explanation:"锌参与蛋白质合成、细胞生长分化和免疫功能，缺乏可出现这些表现。",source:"教材第71-72页"},
  {id:"m-zn-03",category:"锌",type:"single",stem:"下列食物中，锌含量最高的是",options:["生蚝","苹果","精白米","牛奶"],answer:[0],explanation:"教材表 1-22 中生蚝含锌量约 71.20 mg/100g，是列举食物中很高的来源。",source:"教材第73页"},
  {id:"m-se-01",category:"硒",type:"single",stem:"缺硒与下列哪种疾病的发生关系最密切",options:["克山病","脚气病","夜盲症","坏血病"],answer:[0],explanation:"我国研究首先证实缺硒是克山病的重要原因，克山病主要表现为心肌病变。",source:"教材第74页"},
  {id:"m-se-02",category:"硒",type:"single",stem:"硒营养评价中，红细胞 GSH-Px 活性主要反映",options:["硒在体内的活性形式","近期蛋白质摄入量","体内铁储存量","尿碘排出量"],answer:[0],explanation:"谷胱甘肽过氧化物酶是含硒酶，测定其活性可直接反映硒营养状况，但在正常硒水平以上会饱和。",source:"教材第74页"},
  {id:"m-se-03",category:"硒",type:"multiple",stem:"关于硒摄入与来源，正确的是",options:["成人硒 RNI 为 60 μg/d","成人硒 UL 为 400 μg/d","海产品和动物内脏是良好来源","植物性食物的硒含量受土壤硒水平影响"],answer:[0,1,2,3],explanation:"教材列出的硒 RNI、UL、主要食物来源和地域差异均是考点。",source:"教材第75页"},
  {id:"m-cr-01",category:"铬、碘与其他矿物质",type:"single",stem:"铬作为葡萄糖耐量因子的重要组成成分，主要作用是",options:["增强胰岛素作用","抑制甲状腺素合成","促进维生素 C 排出","直接合成血红蛋白"],answer:[0],explanation:"铬是葡萄糖耐量因子的重要组成成分，在糖代谢中可增强胰岛素作用。",source:"教材第75页"},
  {id:"m-cr-02",category:"铬、碘与其他矿物质",type:"single",stem:"关于铬的价态，正确的是",options:["三价铬主要存在于天然食物，毒性较低","六价铬是人体必需的主要形式","三价铬主要来自工业污染，毒性最大","膳食铬过量中毒已有明确普遍报道"],answer:[0],explanation:"天然食物和生物体中主要是低毒的三价铬；六价铬主要来自工业生产，毒性较大。",source:"教材第76页"},
  {id:"m-i-01",category:"铬、碘与其他矿物质",type:"single",stem:"成人体内的碘约有多少存在于甲状腺组织",options:["5%-10%","20%-30%","40%-50%","70%-80%"],answer:[3],explanation:"成人体内含碘约 15-20 mg，其中 70%-80% 存在于甲状腺组织。",source:"教材第76页"},
  {id:"m-i-02",category:"铬、碘与其他矿物质",type:"single",stem:"两分子 DIT 偶联生成的是",options:["MIT","T3","T4","TSH"],answer:[2],explanation:"两分子二碘酪氨酸（DIT）偶联生成四碘甲腺原氨酸 T4；MIT 与 DIT 偶联生成 T3。",source:"教材第77页"},
  {id:"m-i-03",category:"铬、碘与其他矿物质",type:"multiple",stem:"关于碘缺乏和碘评价，正确的是",options:["碘缺乏的典型症状是甲状腺肿大","胎儿和婴幼儿缺碘可影响智力发育","尿碘可评价近期碘摄入","儿童尿碘中位数低于 100 μg/L 提示人群碘营养不良"],answer:[0,1,2,3],explanation:"碘缺乏可导致甲状腺代偿性肿大；孕期和儿童期缺碘会影响神经发育；尿碘是近期摄入评价指标。",source:"教材第77-78页"},
  {id:"m-i-04",category:"铬、碘与其他矿物质",type:"single",stem:"中国营养学会推荐成人碘的 RNI 和 UL 分别是",options:["60 μg/d 和 400 μg/d","100 μg/d 和 200 μg/d","120 μg/d 和 600 μg/d","200 μg/d 和 1000 μg/d"],answer:[2],explanation:"成人碘 RNI 为 120 μg/d，UL 为 600 μg/d。海带、海藻、鱼虾和贝类是常见富碘食物。",source:"教材第78页"},
  {id:"m-cu-01",category:"铬、碘与其他矿物质",type:"single",stem:"铜蓝蛋白在铁代谢中的关键作用是",options:["催化 Fe2+ 氧化为 Fe3+","催化 Fe3+ 还原为 Fe2+","阻断铁吸收","把铁直接转化为血红素"],answer:[0],explanation:"铜蓝蛋白可催化二价铁氧化为三价铁，有助于运铁蛋白形成并促进铁吸收和转运。",source:"教材第78页"},
  {id:"m-cu-02",category:"铬、碘与其他矿物质",type:"multiple",stem:"铜的生理功能包括",options:["维持正常造血","维护中枢神经系统完整性","促进骨骼、血管和皮肤健康","作为 SOD 的重要组成成分参与抗氧化"],answer:[0,1,2,3],explanation:"铜参与造血、神经髓鞘和递质合成、胶原交联以及 SOD 抗氧化。",source:"教材第78页"},
  {id:"m-mn-01",category:"铬、碘与其他矿物质",type:"single",stem:"锰的吸收率一般约为",options:["2%-15%","20%-35%","50%-65%","75%-90%"],answer:[0],explanation:"锰在小肠吸收率较低，约为 2%-15%；摄入高时吸收率下降。",source:"教材第80页"},
  {id:"m-f-01",category:"铬、碘与其他矿物质",type:"single",stem:"氟预防龋齿的主要机制是",options:["形成抗酸性的氟磷灰石保护层","促进牙菌斑产酸","抑制钙磷利用","使牙釉质完全脱矿"],answer:[0],explanation:"氟可与牙釉质羟磷灰石作用形成抗酸性的氟磷灰石保护层，减少酸性损伤。",source:"教材第80页"},
  {id:"v-general-01",category:"维生素总论",type:"multiple",stem:"关于脂溶性维生素，正确的是",options:["包括维生素 A、D、E、K","吸收与肠道脂类密切相关","通常易储存于体内而不易排出","摄入过多更易蓄积产生毒性"],answer:[0,1,2,3],explanation:"脂溶性维生素与脂类共存、依赖脂类吸收，易在体内储存，因此过量蓄积风险较高。",source:"教材第83页"},
  {id:"v-general-02",category:"维生素总论",type:"single",stem:"下列哪种维生素虽然属于水溶性维生素，却较易储存于体内",options:["维生素 B1","维生素 B2","维生素 B12","维生素 C"],answer:[2],explanation:"水溶性维生素通常易随尿排出，但维生素 B12 是重要例外，体内储存能力较强。",source:"教材第83页"},
  {id:"v-general-03",category:"维生素总论",type:"single",stem:"维生素缺乏由膳食供给不足或生物利用率过低直接引起，称为",options:["原发性维生素缺乏","继发性维生素缺乏","临床过量","亚临床中毒"],answer:[0],explanation:"原发性缺乏来自膳食供给不足或生物利用率过低；吸收、利用障碍或需要量增加导致继发性缺乏。",source:"教材第83-84页"},
  {id:"v-a-01",category:"维生素 A",type:"single",stem:"下列哪一种类胡萝卜素不具有维生素 A 活性",options:["β-胡萝卜素","α-胡萝卜素","β-隐黄素","番茄红素"],answer:[3],explanation:"番茄红素、叶黄素和玉米黄素等不能分解形成维生素 A；β-胡萝卜素是重要的维生素 A 原。",source:"教材第84页"},
  {id:"v-a-02",category:"维生素 A",type:"single",stem:"膳食中视黄醇的吸收率约为",options:["5%以下","20%-50%","70%-90%","接近100%"],answer:[2],explanation:"教材给出的视黄醇吸收率约为 70%-90%，类胡萝卜素约为 20%-50%且随摄入增加而下降。",source:"教材第85页"},
  {id:"v-a-03",category:"维生素 A",type:"single",stem:"肝脏储存维生素 A 的主要细胞是",options:["肝星状细胞","胰岛 β 细胞","肾小管细胞","甲状腺滤泡细胞"],answer:[0],explanation:"视黄醇主要以棕榈酸视黄酯形式储存在肝星状细胞（约 80%-95%）和肝主细胞。",source:"教材第86页"},
  {id:"v-a-04",category:"维生素 A",type:"single",stem:"维生素 A 缺乏最早出现的视觉表现是",options:["失明","眼干燥症","暗适应能力下降","角膜溃疡"],answer:[2],explanation:"维生素 A 缺乏最早是暗适应能力下降，随后可发展为夜盲、眼干燥症甚至失明。",source:"教材第88页"},
  {id:"v-a-05",category:"维生素 A",type:"single",stem:"儿童维生素 A 缺乏的重要临床诊断体征是",options:["毕脱氏斑","肋骨串珠","地图舌","反甲"],answer:[0],explanation:"毕脱氏斑表现为角膜两侧和结膜外侧的泡沫样白斑，是儿童维生素 A 缺乏的重要体征。",source:"教材第88页"},
  {id:"v-a-06",category:"维生素 A",type:"multiple",stem:"关于维生素 A 过量，正确的是",options:["长期摄入 RNI 10 倍以上可发生慢性中毒","孕早期大剂量摄入会增加出生缺陷风险","普通食物一般不易造成维生素 A 过量","类胡萝卜素过量通常不会产生同样的毒性"],answer:[0,1,2,3],explanation:"维生素 A 浓缩制剂是过量的常见来源；类胡萝卜素转化慢且吸收会下降，通常只导致可逆的高胡萝卜素血症。",source:"教材第88页"},
  {id:"v-a-07",category:"维生素 A",type:"single",stem:"血清维生素 A 低于下列哪一值可提示缺乏或边缘性缺乏",options:["0.10 μmol/L","0.70 μmol/L","1.50 μmol/L","3.00 μmol/L"],answer:[2],explanation:"成人血清维生素 A 正常范围为 1.5-3 μmol/L，低于相应界值可结合其他资料判断缺乏。",source:"教材第88-89页"},
  {id:"v-d-01",category:"维生素 D",type:"single",stem:"维生素 D 在血液中的主要存在形式，也是评价其营养状况的首选指标是",options:["1,25-(OH)2-D3","25-(OH)-D3","维生素 D 结合蛋白","24,25-(OH)2-D3"],answer:[1],explanation:"25-(OH)-D3 半衰期约 3 周、受调节影响较小，可反映数周至数月的储存状况。",source:"教材第93页"},
  {id:"v-d-02",category:"维生素 D",type:"single",stem:"维生素 D 的活性形式是",options:["维生素 D2","维生素 D3","25-(OH)-D3","1,25-(OH)2-D3"],answer:[3],explanation:"1,25-(OH)2-D3 是维生素 D 的活性形式，作用于肠、肾、骨等靶器官。",source:"教材第91页"},
  {id:"v-d-03",category:"维生素 D",type:"multiple",stem:"活性维生素 D 的作用包括",options:["促进小肠钙吸收","促进肾小管钙、磷重吸收","低血钙时动员骨钙磷入血","调节血钙平衡"],answer:[0,1,2,3],explanation:"活性维生素 D 通过肠、肾、骨等器官参与钙磷代谢和血钙稳态。",source:"教材第92页"},
  {id:"v-d-04",category:"维生素 D",type:"single",stem:"婴儿维生素 D 缺乏主要导致",options:["骨质疏松症","佝偻病","坏血病","脚气病"],answer:[1],explanation:"婴儿缺乏维生素 D 可发生佝偻病；成人尤其是孕妇、乳母和老人可发生骨质软化或骨质疏松。",source:"教材第92页"},
  {id:"v-d-05",category:"维生素 D",type:"single",stem:"维生素 D 的廉价有效来源是",options:["经常晒太阳","大量饮用牛奶","只吃蔬菜水果","服用高剂量补充剂"],answer:[0],explanation:"经常接触阳光可促进皮肤合成维生素 D，成年人通常不会因此发生缺乏。",source:"教材第93页"},
  {id:"v-e-01",category:"维生素 E",type:"single",stem:"维生素 E 中生物活性最高、常作为代表的是",options:["α-生育酚","β-生育酚","γ-生育三烯酚","δ-生育三烯酚"],answer:[0],explanation:"维生素 E 包括四种生育酚和四种生育三烯酚，其中 α-生育酚生物活性最高。",source:"教材第93页"},
  {id:"v-e-02",category:"维生素 E",type:"single",stem:"维生素 E 在体内主要储存在",options:["脂肪细胞","红骨髓","甲状腺滤泡","肾小球"],answer:[0],explanation:"大部分维生素 E 以非酯化形式储存在脂肪细胞，少量储存在肝、肺、心脏、肌肉等组织。",source:"教材第94页"},
  {id:"v-e-03",category:"维生素 E",type:"multiple",stem:"关于维生素 E，正确的是",options:["是重要的脂质抗氧化剂","可与维生素 C、谷胱甘肽等协同再生","缺乏可出现溶血性贫血和肌无力","大剂量可干扰维生素 K 的吸收和利用"],answer:[0,1,2,3],explanation:"维生素 E 参与抗氧化系统；缺乏可损伤红细胞和神经肌肉；大剂量时可能影响维生素 K。",source:"教材第94-95页"},
  {id:"v-e-04",category:"维生素 E",type:"single",stem:"红细胞溶血试验中，维生素 E 缺乏通常表现为溶血百分比",options:["小于 10%","10%-20%","大于 20%","等于 0%"],answer:[2],explanation:"红细胞溶血试验中，正常 <10%，偏低 10%-20%，缺乏 >20%。",source:"教材第95页"},
  {id:"v-b1-01",category:"维生素 B1",type:"single",stem:"维生素 B1 的主要活性形式是",options:["FMN","FAD","TPP","PLP"],answer:[2],explanation:"焦磷酸硫胺素（TPP）是维生素 B1 的主要活性形式，参与 α-酮酸氧化脱羧和转酮醇反应。",source:"教材第96-97页"},
  {id:"v-b1-02",category:"维生素 B1",type:"multiple",stem:"TPP 参与的关键反应包括",options:["α-酮酸氧化脱羧","磷酸戊糖途径的转酮醇反应","丙酮酸转化为乙酰辅酶 A","直接催化脂肪酸水解"],answer:[0,1,2],explanation:"TPP 参与 α-酮酸氧化脱羧及磷酸戊糖途径转酮醇反应，不直接催化脂肪酸水解。",source:"教材第97页"},
  {id:"v-b1-03",category:"维生素 B1",type:"single",stem:"湿性脚气病的主要表现是",options:["多发性周围神经炎","水肿和心脏症状","夜盲和眼干燥","皮炎、腹泻和痴呆"],answer:[1],explanation:"湿性脚气病以水肿和心血管症状为主；干性脚气病以多发性周围神经炎为主。",source:"教材第97页"},
  {id:"v-b1-04",category:"维生素 B1",type:"single",stem:"维生素 B1 尿负荷试验中，4 小时尿排出量低于多少提示缺乏",options:["40 μg","100 μg","200 μg","400 μg"],answer:[1],explanation:"口服 5 mg 后收集 4 小时尿液，排出维生素 B1 <100 μg（约摄入量 2%）提示缺乏。",source:"教材第97-98页"},
  {id:"v-b1-05",category:"维生素 B1",type:"single",stem:"维生素 B1 在日常膳食中的主要来源是",options:["谷类食物","纯牛奶","柑橘类水果","精炼植物油"],answer:[0],explanation:"维生素 B1 主要来自谷类，且多存在于表皮和胚芽，过度碾磨会造成损失。",source:"教材第98页"},
  {id:"v-b2-01",category:"维生素 B2",type:"single",stem:"维生素 B2 在体内主要以哪两种辅酶形式发挥作用",options:["TPP 和 TTP","FMN 和 FAD","PLP 和 PMP","NAD 和 NADP"],answer:[1],explanation:"核黄素在体内形成 FMN 和 FAD，参与多种氧化还原反应和能量代谢。",source:"教材第99页"},
  {id:"v-b2-02",category:"维生素 B2",type:"single",stem:"维生素 B2 缺乏的典型综合征主要累及",options:["眼、口腔和皮肤","骨、肾和肌肉","胃、肝和胰腺","脑、心和肺"],answer:[0],explanation:"核黄素缺乏主要表现为眼、口腔和皮肤的炎症反应，常称口腔生殖系统综合征。",source:"教材第99-100页"},
  {id:"v-b2-03",category:"维生素 B2",type:"single",stem:"EGRAC 小于何值通常提示核黄素营养状况正常",options:["0.8","1.2","1.4","2.0"],answer:[1],explanation:"红细胞谷胱甘肽还原酶活性系数 EGRAC <1.2 为正常，1.2-1.4 为不足，>1.4 为缺乏。",source:"教材第100页"},
  {id:"v-b2-04",category:"维生素 B2",type:"multiple",stem:"会增加维生素 B2 需要量或造成损失的情况包括",options:["能量需要量增加","生长加速或创伤修复","碱性环境和光照","食物加工时加碱"],answer:[0,1,2,3],explanation:"B2 需要量与能量代谢相关；其在碱性环境中易被热和紫外线破坏。",source:"教材第100页"},
  {id:"v-niacin-01",category:"烟酸",type:"single",stem:"烟酸缺乏症的经典“三 D”是",options:["皮炎、腹泻、痴呆","头痛、脱发、贫血","夜盲、干眼、失明","水肿、心悸、麻木"],answer:[0],explanation:"烟酸缺乏可出现 dermatitis、diarrhea、dementia，即皮炎、腹泻和痴呆。",source:"教材第101页"},
  {id:"v-niacin-02",category:"烟酸",type:"single",stem:"平均约多少色氨酸可转化为 1 mg 烟酸",options:["6 mg","20 mg","60 mg","600 mg"],answer:[2],explanation:"平均约 60 mg 色氨酸可转化为 1 mg 烟酸，因此烟酸摄入以烟酸当量表示。",source:"教材第102页"},
  {id:"v-niacin-03",category:"烟酸",type:"single",stem:"烟酸当量的计算式是",options:["烟酸 + 60×色氨酸","烟酸 + 色氨酸/60","烟酸 - 色氨酸/60","烟酸 × 色氨酸"],answer:[1],explanation:"烟酸当量（mg NE）= 烟酸（mg）+ 色氨酸（mg）/60。",source:"教材第102页"},
  {id:"v-niacin-04",category:"烟酸",type:"multiple",stem:"烟酸的生理作用包括",options:["构成 NAD 和 NADP 参与氢的传递","降低血胆固醇水平","参与葡萄糖耐量因子组成","参与物质和能量代谢"],answer:[0,1,2,3],explanation:"烟酸以烟酰胺形式参与 NAD/NADP、物质能量代谢、胆固醇调节及葡萄糖耐量因子。",source:"教材第101页"},
  {id:"v-pan-01",category:"泛酸",type:"single",stem:"泛酸的主要生理作用是构成",options:["辅酶 A 和酰基载体蛋白","视紫红质和 RBP","血红蛋白和肌红蛋白","甲状腺素和降钙素"],answer:[0],explanation:"泛酸构成辅酶 A 和酰基载体蛋白，并参与糖、脂肪和蛋白质代谢。",source:"教材第103页"},
  {id:"v-pan-02",category:"泛酸",type:"single",stem:"成人全血泛酸浓度低于何值可提示摄入不足或缺乏",options:["0.1 mg/L","1 mg/L","5 mg/L","10 mg/L"],answer:[1],explanation:"正常全血泛酸约 2 mg/L，低于 1 mg/L 可认为摄入不足或缺乏。",source:"教材第103页"},
  {id:"v-b6-01",category:"维生素 B6",type:"single",stem:"维生素 B6 在体内的主要活性形式是",options:["PLP","TPP","FAD","NADP"],answer:[0],explanation:"磷酸吡哆醛（PLP）是维生素 B6 在体内的主要活性形式。",source:"教材第104页"},
  {id:"v-b6-02",category:"维生素 B6",type:"multiple",stem:"维生素 B6 参与的过程包括",options:["氨基酸转氨和脱氨","烟酸合成","血红素合成","神经递质合成"],answer:[0,1,2,3],explanation:"PLP 参与氨基酸、脂肪、烟酸、血红素、抗体、神经递质及同型半胱氨酸代谢。",source:"教材第104页"},
  {id:"v-b6-03",category:"维生素 B6",type:"single",stem:"长期大剂量服用维生素 B6（约 500 mg/d）可能导致",options:["神经毒性和光敏感性","严重碘缺乏","佝偻病","坏血病"],answer:[0],explanation:"食物来源的 B6 通常安全，但大剂量补充可导致神经毒性和光敏感性反应。",source:"教材第105页"},
  {id:"v-biotin-01",category:"生物素",type:"single",stem:"生蛋清导致生物素吸收受阻的主要原因是含有",options:["抗生物素蛋白","胰蛋白酶抑制剂","植酸","单宁"],answer:[0],explanation:"生蛋清中的抗生物素蛋白可结合生物素，使其不能在肠道吸收；加热可破坏该蛋白。",source:"教材第106页"},
  {id:"v-biotin-02",category:"生物素",type:"multiple",stem:"关于生物素，正确的是",options:["是多种羧化酶的辅酶","参与糖、脂肪、蛋白质和核酸代谢","成人 AI 为 40 μg/d","目前未见明确生物素毒性反应报道"],answer:[0,1,2,3],explanation:"生物素参与多种羧化反应；成人 AI 为 40 μg/d，毒性很低。",source:"教材第106页"},
  {id:"v-folate-01",category:"叶酸",type:"single",stem:"叶酸在体内具有生理功能的主要形式是",options:["叶酸多谷氨酸","二氢叶酸","四氢叶酸","叶酸钠盐"],answer:[2],explanation:"天然叶酸多为还原形式，但只有四氢叶酸具有主要生理功能。",source:"教材第107页"},
  {id:"v-folate-02",category:"叶酸",type:"single",stem:"叶酸最重要的代谢功能是作为何种基团的载体",options:["一碳单位","硫酸根","磷酸根","脂肪酸"],answer:[0],explanation:"四氢叶酸携带甲酰基、亚甲基和甲基等一碳基团，参与核苷酸合成和甲基化反应。",source:"教材第107页"},
  {id:"v-folate-03",category:"叶酸",type:"single",stem:"孕早期叶酸缺乏最需要警惕的胎儿结局是",options:["神经管畸形","氟斑牙","佝偻病","克山病"],answer:[0],explanation:"孕早期叶酸缺乏可导致胎儿神经管畸形，主要表现为脊柱裂和无脑畸形。",source:"教材第108页"},
  {id:"v-folate-04",category:"叶酸",type:"multiple",stem:"关于膳食叶酸当量 DFE，正确的是",options:["DFE = 膳食叶酸 + 1.7 × 叶酸补充剂","成人叶酸 RNI 为 400 μg DFE/d","孕妇叶酸 RNI 为 600 μg DFE/d","叶酸 UL 为 1000 μg DFE/d"],answer:[0,1,2,3],explanation:"DFE 公式和成人、孕妇 RNI 以及 UL 均为教材给出的参考值。",source:"教材第108页"},
  {id:"v-b12-01",category:"维生素 B12",type:"single",stem:"维生素 B12 吸收必须依赖胃黏膜分泌的",options:["内因子","胆盐","胰脂酶","运铁蛋白"],answer:[0],explanation:"B12 从食物释放后需与胃黏膜分泌的内因子结合，复合物在回肠被吸收。",source:"教材第109页"},
  {id:"v-b12-02",category:"维生素 B12",type:"single",stem:"维生素 B12 的主要转运蛋白是",options:["TC I","TC II","RBP","DBP"],answer:[1],explanation:"TC II 是维生素 B12 的主要转运蛋白，将其运至肝、肾、骨髓等组织。",source:"教材第109页"},
  {id:"v-b12-03",category:"维生素 B12",type:"multiple",stem:"维生素 B12 缺乏可能导致",options:["巨幼红细胞贫血","进行性脱髓鞘和神经系统损害","高同型半胱氨酸血症","甲基丙二酸增高"],answer:[0,1,2,3],explanation:"B12 参与核酸合成、同型半胱氨酸甲基化和甲基丙二酸代谢，缺乏可同时造成造血和神经损害。",source:"教材第110页"},
  {id:"v-b12-04",category:"维生素 B12",type:"single",stem:"维生素 B12 的主要膳食来源是",options:["动物性食品","精制谷物","新鲜水果","植物油"],answer:[0],explanation:"B12 主要来自肉类、动物内脏、鱼、禽和蛋类，植物性食品基本不含。",source:"教材第111页"},
  {id:"v-c-01",category:"维生素 C",type:"single",stem:"天然维生素 C 中具有生物活性的是",options:["L 型","D 型","两者均无","只有合成型"],answer:[0],explanation:"天然维生素 C 有 L 型和 D 型，L 型具有生物活性，D 型无生物活性。",source:"教材第111页"},
  {id:"v-c-02",category:"维生素 C",type:"single",stem:"维生素 C 促进铁吸收的机制是",options:["把 Fe3+ 还原成 Fe2+","把 Fe2+ 氧化成 Fe3+","抑制小肠主动转运","促进植酸与铁结合"],answer:[0],explanation:"维生素 C 可将难以吸收利用的三价铁还原成二价铁，促进肠道吸收。",source:"教材第112页"},
  {id:"v-c-03",category:"维生素 C",type:"multiple",stem:"维生素 C 的生理功能包括",options:["抗氧化和清除自由基","参与胶原蛋白羟基化","促进铁、钙和叶酸利用","参与去甲肾上腺素等神经递质合成"],answer:[0,1,2,3],explanation:"维生素 C 既是抗氧化剂，也是胶原羟化过程辅助因子，并参与多种营养素利用和神经递质合成。",source:"教材第112页"},
  {id:"v-c-04",category:"维生素 C",type:"single",stem:"维生素 C 缺乏的主要疾病是",options:["坏血病","佝偻病","脚气病","糙皮病"],answer:[0],explanation:"体内维生素 C 储存低于约 300 mg 可出现缺乏症状，主要引起坏血病。",source:"教材第112页"},
  {id:"v-c-05",category:"维生素 C",type:"single",stem:"血浆维生素 C 浓度低于何值可视为缺乏",options:["4 mg/L","3.9 mg/L","2 mg/L","0.5 mg/L"],answer:[2],explanation:"血浆维生素 C ≥4 mg/L 为正常，2.0-3.9 mg/L 为不足，<2 mg/L 为缺乏。",source:"教材第113页"},

  {id:"add-p-01",category:"磷",type:"single",stem:"膳食钙磷比例理论上维持在何值较为理想",options:["1:3","1:1","2:1","4:1"],answer:[2],explanation:"教材指出膳食钙磷比例维持在 2:1 之间较好，不宜低于 0.5。",source:"教材第65页"},
  {id:"add-p-02",category:"磷",type:"single",stem:"中国营养学会推荐成人膳食磷的 UL 是",options:["720 mg/d","1200 mg/d","2000 mg/d","3500 mg/d"],answer:[3],explanation:"成人膳食磷的 RNI 为 720 mg/d，UL 为 3500 mg/d。",source:"教材第65页"},
  {id:"add-p-03",category:"磷",type:"single",stem:"磷摄入过量可能引起的非骨性后果是",options:["非骨组织钙化","视紫红质减少","胶原蛋白合成增加","甲状腺素分泌增加"],answer:[0],explanation:"过量磷可能造成非骨组织钙化，并可引起低血钙和神经肌肉兴奋性增强。",source:"教材第65页"},
  {id:"add-p-04",category:"磷",type:"multiple",stem:"容易出现磷缺乏的情况包括",options:["早产儿仅喂磷含量较低的母乳","长期大量使用抗酸药","肾小管重吸收障碍","长期禁食"],answer:[0,1,2,3],explanation:"这些情况均被教材列为磷缺乏的特殊原因。",source:"教材第65页"},

  {id:"add-mg-01",category:"镁",type:"single",stem:"正常成人体内镁主要分布在何处",options:["细胞外液","细胞内，尤其骨骼和组织细胞内","血浆白蛋白","胆汁"],answer:[1],explanation:"镁主要分布在细胞内，60%-65% 存在于骨骼，细胞外液中的镁不超过 1%。",source:"教材第65页"},
  {id:"add-mg-02",category:"镁",type:"single",stem:"镁参与体内大约多少种酶促反应",options:["30 多种","100 多种","300 多种","1000 多种"],answer:[2],explanation:"教材指出镁作为多种酶的激活剂，参与体内 300 多种酶促反应。",source:"教材第65页"},
  {id:"add-mg-03",category:"镁",type:"multiple",stem:"镁的生理作用包括",options:["激活 Na-K-ATP 酶","促进骨骼生长","碱性镁盐可中和胃酸","硫酸镁可松弛奥狄括约肌"],answer:[0,1,2,3],explanation:"镁既参与酶反应和骨骼功能，也影响胃肠道功能与胆汁排空。",source:"教材第65-66页"},
  {id:"add-mg-04",category:"镁",type:"single",stem:"镁的主要排泄途径是",options:["肾脏","皮肤汗液","肺呼气","乳汁"],answer:[0],explanation:"肾脏是镁排泄的主要途径，汗液和粪便排出的量较少。",source:"教材第66页"},
  {id:"add-mg-05",category:"镁",type:"single",stem:"24 小时尿镁排出量低于多少可诊断为镁缺乏症",options:["0.5 mmol","1.0 mmol","1.5 mmol","3.0 mmol"],answer:[2],explanation:"半定量尿负荷实验中，24 小时尿镁低于 1.5 mmol 可诊断为镁缺乏症。",source:"教材第66页"},
  {id:"add-mg-06",category:"镁",type:"multiple",stem:"镁过量更容易发生于",options:["肾功能不全者","接受镁剂治疗者","正常健康人摄入普通食物时","糖尿病酮症早期脱水者"],answer:[0,1,3],explanation:"肾功能不全、镁剂治疗以及糖尿病酮症早期均可能使血清镁升高；普通食物摄入通常不易导致镁中毒。",source:"教材第66页"},

  {id:"add-fe-01",category:"铁",type:"single",stem:"人体内铁总量约为",options:["3-4 mg/kg 体重","30-40 mg/kg 体重","300-400 mg/kg 体重","1-2 g/kg 体重"],answer:[1],explanation:"正常人体内含铁总量约为 30-40 mg/kg 体重。",source:"教材第67页"},
  {id:"add-fe-02",category:"铁",type:"single",stem:"人体铁中约有多少存在于血红蛋白",options:["5%-10%","25%-30%","65%-70%","90%-95%"],answer:[2],explanation:"约 65%-70% 的铁存在于血红蛋白，3% 在肌红蛋白，25%-30% 为储存铁。",source:"教材第67页"},
  {id:"add-fe-03",category:"铁",type:"single",stem:"运铁蛋白主要结合并转运哪种形式的铁",options:["Fe2+","Fe3+","游离铁原子","血红素铁颗粒"],answer:[1],explanation:"运铁蛋白是可逆结合 Fe3+ 的糖蛋白，负责将铁转运到需要铁的组织。",source:"教材第68页"},
  {id:"add-fe-04",category:"铁",type:"multiple",stem:"可促进铁吸收的膳食因素包括",options:["维生素 C","组氨酸、赖氨酸等氨基酸","蛋白质类食物","柠檬酸和乳酸"],answer:[0,1,2,3],explanation:"这些因素可通过还原、螯合成可溶性单体或促进胃酸分泌等方式促进铁吸收。",source:"教材第68页"},
  {id:"add-fe-05",category:"铁",type:"multiple",stem:"可阻碍铁吸收的因素包括",options:["植酸和单宁","多酚物质","过量铅、铬、锰","EDTA 等金属络合物"],answer:[0,1,2,3],explanation:"这些非营养素成分或矿物质可与铁结合或影响其吸收。",source:"教材第68页"},
  {id:"add-fe-06",category:"铁",type:"single",stem:"缺铁的第一阶段铁减少期首先表现为",options:["血红蛋白下降并出现贫血","储存铁减少、血清铁蛋白下降且无临床症状","血清铁升高、铁结合力下降","红细胞容积升高"],answer:[1],explanation:"第一阶段是铁减少期，储存铁减少、血清铁蛋白下降，但尚无临床症状。",source:"教材第69页"},
  {id:"add-fe-07",category:"铁",type:"single",stem:"缺铁第二阶段红细胞生成缺铁期的变化是",options:["血清铁降低、铁结合力上升","血清铁升高、铁结合力下降","血红蛋白先明显升高","血清铁蛋白恢复正常"],answer:[0],explanation:"第二阶段除血清铁蛋白下降外，还出现血清铁降低、铁结合力上升和游离原卟啉升高。",source:"教材第69页"},
  {id:"add-fe-08",category:"铁",type:"single",stem:"成年女性每天铁的生理性流失量约为",options:["0.15 mg","1.5 mg","15 mg","150 mg"],answer:[1],explanation:"女性因生理原因失铁较多，每天铁的流失约为 1.5 mg。",source:"教材第68页"},
  {id:"add-fe-09",category:"铁",type:"single",stem:"血清铁蛋白最适合反映机体的哪一方面",options:["近期铁摄入","体内铁储存","肠道铁吸收瞬时速度","红细胞平均体积"],answer:[1],explanation:"血清铁蛋白反映人体内铁储存，是诊断隐性缺铁性贫血较可靠的指标。",source:"教材第69页"},
  {id:"add-fe-10",category:"铁",type:"single",stem:"成年男性运铁蛋白饱和度低于多少通常认为存在铁缺乏",options:["5%","10%","16%","30%"],answer:[2],explanation:"一般成年人运铁蛋白饱和度低于 16% 认为是铁缺乏。",source:"教材第70页"},

  {id:"add-zn-01",category:"锌",type:"single",stem:"锌缺乏对儿童生长的直接影响主要是",options:["促进细胞分裂","造成生长发育停滞","使骨钙化过快","提高食欲"],answer:[1],explanation:"锌参与蛋白质合成、细胞生长分裂和分化，缺乏可导致儿童生长发育停滞。",source:"教材第71-72页"},
  {id:"add-zn-02",category:"锌",type:"single",stem:"成人摄入多少以上的锌可能观察到毒性症状",options:["40-80 mg","400-800 mg","4-8 g","40-80 g"],answer:[2],explanation:"教材指出成人摄入 4-8 g 以上锌可出现发热、腹泻、恶心、呕吐和嗜睡等毒性表现。",source:"教材第72页"},
  {id:"add-zn-03",category:"锌",type:"multiple",stem:"锌过量可能造成的影响包括",options:["干扰铜和铁的吸收利用","损害中性粒细胞和巨噬细胞功能","抑制细胞杀伤能力","损害免疫功能"],answer:[0,1,2,3],explanation:"锌过量不仅影响其他微量元素利用，还会损害吞噬细胞和免疫功能。",source:"教材第72页"},
  {id:"add-zn-04",category:"锌",type:"single",stem:"下列哪项可用于评价锌营养状况",options:["血清锌浓度和发锌浓度等指标综合判断","只看一次尿糖","只测血清钙","只测血红蛋白"],answer:[0],explanation:"教材的锌营养评价强调结合膳食调查、临床表现、血清锌、发锌和锌负荷试验等综合判断。",source:"教材第72页"},

  {id:"add-se-01",category:"硒",type:"single",stem:"缺硒导致克山病时，主要受损的器官是",options:["心脏","肝脏","甲状腺","小肠"],answer:[0],explanation:"克山病是以多发性灶状坏死为主要病变的心肌病，伴心脏扩大、心功能不全和心律失常。",source:"教材第74页"},
  {id:"add-se-02",category:"硒",type:"single",stem:"慢性硒中毒的典型表现不包括",options:["头发和指甲脱落","皮肤损伤","肢端麻木和抽搐","夜盲症"],answer:[3],explanation:"硒中毒可表现为脱发、脱甲、皮肤和神经系统异常，夜盲症属于维生素 A 缺乏表现。",source:"教材第74页"},
  {id:"add-se-03",category:"硒",type:"single",stem:"硒摄入量增加时，GSH-Px 活性在血硒达到何值后趋于饱和",options:["0.127 μmol/L","1.27 μmol/L","12.7 μmol/L","127 μmol/L"],answer:[1],explanation:"血硒达到 1.27 μmol/L（0.1 mg/L）时，GSH-Px 活性达饱和。",source:"教材第74页"},
  {id:"add-se-04",category:"硒",type:"single",stem:"膳食硒摄入量在不同地区差异较大，最重要的环境原因是",options:["土壤硒含量不同","空气湿度不同","日照时长不同","饮水温度不同"],answer:[0],explanation:"尤其是植物性食物的硒含量与地表土壤硒水平密切相关。",source:"教材第75页"},

  {id:"add-cr-01",category:"铬、碘与其他矿物质",type:"single",stem:"铬进入血液后主要与哪种蛋白结合运输",options:["运铁蛋白","视黄醇结合蛋白","内因子","胶原蛋白"],answer:[0],explanation:"铬进入血液后主要与运铁蛋白结合，部分与白蛋白结合。",source:"教材第75页"},
  {id:"add-cr-02",category:"铬、碘与其他矿物质",type:"single",stem:"摄入体内的铬约有多少以上从尿中排出",options:["25%","50%","75%","95%"],answer:[3],explanation:"摄入的铬约 95% 以上从尿中排出，少量从胆汁、毛发和皮肤排出。",source:"教材第75页"},
  {id:"add-cr-03",category:"铬、碘与其他矿物质",type:"single",stem:"目前成人膳食铬的参考摄入量形式和数值是",options:["RNI 30 μg/d","AI 30 μg/d","RNI 300 μg/d","UL 30 μg/d"],answer:[1],explanation:"目前资料不足以制定 UL，中国营养学会推荐成人铬 AI 为 30 μg/d。",source:"教材第76页"},
  {id:"add-cr-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"铬营养评价的特点包括",options:["目前缺乏可靠的评价指标","尿铬只适宜评价接受补铬者","血铬浓度很低且难检测","评价时需结合摄入调查、病史和临床表现"],answer:[0,1,2,3],explanation:"铬的营养评价较困难，不能仅依赖单一血、尿或发铬指标。",source:"教材第76页"},

  {id:"add-i-01",category:"铬、碘与其他矿物质",type:"single",stem:"在 TSH 刺激下，碘参与甲状腺激素合成时首先形成",options:["MIT 和 DIT","T3 和 T4 直接进入血液","TSH 和 PTH","尿碘和血碘"],answer:[0],explanation:"碘化酪氨酸残基形成一碘酪氨酸（MIT）和二碘酪氨酸（DIT），随后发生偶联。",source:"教材第77页"},
  {id:"add-i-02",category:"铬、碘与其他矿物质",type:"single",stem:"人体摄入的碘约有多少经尿排出",options:["10%","30%","60%","90%"],answer:[3],explanation:"体内碘主要经肾脏排泄，约 90% 随尿排出，10% 由粪便排出。",source:"教材第77页"},
  {id:"add-i-03",category:"铬、碘与其他矿物质",type:"single",stem:"长期大量摄入十字花科植物中的抗甲状腺素因子，可能导致",options:["碘缺乏和甲状腺肿","铁过量","坏血病","维生素 E 中毒"],answer:[0],explanation:"萝卜、甘蓝、花菜等十字花科植物中的相关成分可干扰甲状腺对碘的吸收利用。",source:"教材第77页"},
  {id:"add-i-04",category:"铬、碘与其他矿物质",type:"single",stem:"甲状腺肿大率超过多少可提示人群碘营养不良",options:["1%","5%","15%","25%"],answer:[1],explanation:"长期碘缺乏或过量均可增加甲状腺肿大率，甲状腺肿大率 >5% 提示人群碘营养不良。",source:"教材第78页"},
  {id:"add-i-05",category:"铬、碘与其他矿物质",type:"multiple",stem:"关于碘的食物来源，正确的是",options:["海产品含碘通常高于陆地食物","陆地动物性食物通常高于植物性食物","海带和海藻是富碘食物","鱼虾和贝类是常见来源"],answer:[0,1,2,3],explanation:"海产品、特别是海带、海藻、鱼虾和贝类，是教材列出的主要富碘食物。",source:"教材第78页"},

  {id:"add-cu-01",category:"铬、碘与其他矿物质",type:"single",stem:"铜主要在小肠的哪个部位吸收",options:["十二指肠","回肠末端","结肠","胃底"],answer:[0],explanation:"铜主要在十二指肠吸收，小肠末端和胃也可吸收少量。",source:"教材第78页"},
  {id:"add-cu-02",category:"铬、碘与其他矿物质",type:"single",stem:"铜的吸收率与摄入量的关系是",options:["正相关，摄入越多吸收越高","负相关，摄入越多吸收率越低","完全无关","只受年龄影响"],answer:[1],explanation:"铜吸收率与摄入量成负相关，教材给出的波动范围为 12%-75%。",source:"教材第78页"},
  {id:"add-cu-03",category:"铬、碘与其他矿物质",type:"single",stem:"出生后头两个月新生儿体内铜浓度约为成人的",options:["相同水平","1.5-2 倍","6-10 倍","20-30 倍"],answer:[2],explanation:"为满足婴儿期需要，出生后头两个月新生儿铜浓度约为成人的 6-10 倍。",source:"教材第78页"},
  {id:"add-cu-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"铜缺乏可能影响的功能包括",options:["铁转运和造血","神经髓鞘形成","胶原蛋白和弹性蛋白交联","抗氧化防御"],answer:[0,1,2,3],explanation:"铜通过铜蓝蛋白、含铜氧化酶、赖氨酰氧化酶和 SOD 等参与这些功能。",source:"教材第78页"},

  {id:"add-mn-01",category:"铬、碘与其他矿物质",type:"single",stem:"下列哪种膳食成分可促进锰吸收",options:["植酸盐","高铁摄入","膳食纤维","以上都不能"],answer:[2],explanation:"膳食纤维、钙和磷浓度增高可促进锰吸收，植酸盐和铁浓度增高则抑制吸收。",source:"教材第80页"},
  {id:"add-mn-02",category:"铬、碘与其他矿物质",type:"single",stem:"体内锰有多少以上主要由肠道排出",options:["10%","30%","60%","90%"],answer:[3],explanation:"锰除少量吸收利用外，90% 以上由肠道排出。",source:"教材第80页"},
  {id:"add-mn-03",category:"铬、碘与其他矿物质",type:"single",stem:"成人锰的 AI 和 UL 分别是",options:["4.5 mg/d 和 11 mg/d","11 mg/d 和 4.5 mg/d","0.45 mg/d 和 1.1 mg/d","45 mg/d 和 110 mg/d"],answer:[0],explanation:"中国营养学会推荐成人锰 AI 为 4.5 mg/d，UL 为 11 mg/d。",source:"教材第80页"},
  {id:"add-mn-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"锰摄入过量可能损害",options:["中枢神经系统","生殖内分泌功能","视紫红质合成","肠道吸收铁的全部功能"],answer:[0,1],explanation:"锰过量主要损害中枢神经系统，并可引起生殖内分泌功能紊乱。",source:"教材第80页"},

  {id:"add-f-01",category:"铬、碘与其他矿物质",type:"single",stem:"膳食氟约有多少由胃肠道迅速吸收入血",options:["10%-20%","30%-40%","50%-60%","75%-90%"],answer:[3],explanation:"膳食氟约 75%-90% 由胃肠道迅速吸收入血。",source:"教材第80页"},
  {id:"add-f-02",category:"铬、碘与其他矿物质",type:"single",stem:"氟的主要排泄器官是",options:["肾脏","肺脏","皮肤","肝脏"],answer:[0],explanation:"肾脏是无机氟的主要排泄途径，每天摄入氟约有 50% 从肾脏排出。",source:"教材第80页"},
  {id:"add-f-03",category:"铬、碘与其他矿物质",type:"single",stem:"慢性氟中毒对牙齿的典型危害是",options:["氟斑牙","毕脱氏斑","地图舌","反甲"],answer:[0],explanation:"慢性氟中毒可出现氟斑牙，表现为牙齿失去光泽、出现斑点、凹陷剥落和变脆。",source:"教材第80页"},
  {id:"add-f-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"慢性氟中毒的骨骼表现可能包括",options:["腰腿及关节疼痛","脊柱畸形","骨软化","骨质疏松"],answer:[0,1,2,3],explanation:"高氟地区长期摄入高氟饮水可发生氟骨症，出现这些骨骼表现。",source:"教材第80页"},

  {id:"add-vg-01",category:"维生素总论",type:"single",stem:"下列哪种维生素可由肠道细菌合成，但合成量不能完全满足需要",options:["维生素 K","维生素 A","维生素 E","维生素 C"],answer:[0],explanation:"维生素 K 和生物素可由肠道细菌合成，但不能完全替代食物来源。",source:"教材第83页"},
  {id:"add-vg-02",category:"维生素总论",type:"multiple",stem:"维生素缺乏的常见原因包括",options:["摄入不足","吸收利用降低","需要量相对增高","食物加工、烹调或储藏造成损失"],answer:[0,1,2,3],explanation:"维生素缺乏既可能来自摄入和食物处理，也可能来自吸收利用障碍或生理需要量增加。",source:"教材第83页"},
  {id:"add-vg-03",category:"维生素总论",type:"single",stem:"维生素缺乏从轻到重的一般发展顺序是",options:["临床症状→储存下降→生化异常","储存下降→生化和功能异常→组织病理改变及临床体征","食物中断→立即出现严重症状","生化异常→储存增加→临床恢复"],answer:[1],explanation:"教材强调维生素缺乏是渐进过程，先是组织储存降低，再出现生化和功能异常，最后出现病理和临床体征。",source:"教材第84页"},
  {id:"add-vg-04",category:"维生素总论",type:"single",stem:"轻度维生素缺乏但尚无明显临床症状的状态称为",options:["临床缺乏","亚临床缺乏或边缘缺乏","急性中毒","遗传性缺乏"],answer:[1],explanation:"亚临床缺乏常不出现明显症状，但可降低劳动效率和疾病抵抗力。",source:"教材第84页"},

  {id:"add-a-01",category:"维生素 A",type:"multiple",stem:"维生素 A 的活性形式包括",options:["视黄醇","视黄醛","视黄酸","视黄基棕榈酸酯"],answer:[0,1,2],explanation:"机体内维生素 A 的活性形式包括视黄醇、视黄醛和视黄酸；视黄基酯主要是储存形式。",source:"教材第84页"},
  {id:"add-a-02",category:"维生素 A",type:"single",stem:"约多少膳食 β-胡萝卜素可产生 1 mg 视黄醇活性",options:["1 mg","6 mg","12 mg","24 mg"],answer:[2],explanation:"教材提示约 12 mg 膳食 β-胡萝卜素可产生 1 mg 视黄醇活性，其他维生素 A 原类胡萝卜素约需 24 mg。",source:"教材第85页"},
  {id:"add-a-03",category:"维生素 A",type:"single",stem:"维生素 A 在小肠吸收时需要与脂肪酸等形成何种结构",options:["胶团","血红素","尿素循环","氟磷灰石"],answer:[0],explanation:"胆汁、胰脂酶和肠脂酶参与释放维生素 A，游离视黄醇和类胡萝卜素与脂溶性成分形成胶团后被吸收。",source:"教材第85页"},
  {id:"add-a-04",category:"维生素 A",type:"single",stem:"视黄醇与 RBP 结合后，在血浆中还会与哪种蛋白形成复合体",options:["转甲状腺素蛋白 TTR","运铁蛋白 Tf","维生素 D 结合蛋白 DBP","内因子 IF"],answer:[0],explanation:"视黄醇与 RBP 按 1:1 结合，并在血浆中与 TTR 形成视黄醇-RBP-TTR 复合体。",source:"教材第86页"},
  {id:"add-a-05",category:"维生素 A",type:"single",stem:"维生素 A 参与暗视觉的关键感光物质是",options:["视紫红质","血红蛋白","氟磷灰石","谷胱甘肽过氧化物酶"],answer:[0],explanation:"11-顺式视黄醛与视蛋白结合形成视紫红质，对暗视觉十分重要。",source:"教材第86页"},
  {id:"add-a-06",category:"维生素 A",type:"multiple",stem:"维生素 A 的生理功能包括",options:["维持视觉","调节细胞生长和分化","维护上皮组织屏障","增强免疫功能"],answer:[0,1,2,3],explanation:"维生素 A 通过视紫红质、RAR/RXR 受体、上皮组织和免疫调节发挥这些作用。",source:"教材第86-87页"},
  {id:"add-a-07",category:"维生素 A",type:"single",stem:"维生素 A 在体内主要通过哪条途径排泄",options:["代谢产物经胆汁入粪便","原形经肺呼出","全部经汗液排出","全部经尿液排出"],answer:[0],explanation:"约 70% 的维生素 A 代谢产物经胆汁进入粪便排泄，约 30% 由肾脏排泄。",source:"教材第86页"},
  {id:"add-a-08",category:"维生素 A",type:"single",stem:"评价人群维生素 A 缺乏程度常用的血清视黄醇界值是",options:["<0.07 μmol/L","<0.70 μmol/L","<7.0 μmol/L","<70 μmol/L"],answer:[1],explanation:"6-72 月龄婴幼儿、儿童及孕妇血清视黄醇 <0.70 μmol/L 的比例可用于评价人群缺乏程度。",source:"教材第89页"},

  {id:"add-d-01",category:"维生素 D",type:"single",stem:"食物维生素 D 在小肠的吸收率大约为",options:["5%-10%","20%-30%","50%-80%","90%-100%"],answer:[2],explanation:"食物中约 50%-80% 的维生素 D 在小肠吸收。",source:"教材第91页"},
  {id:"add-d-02",category:"维生素 D",type:"single",stem:"维生素 D3 在肝脏首先被转化为",options:["25-(OH)-D3","1,25-(OH)2-D3","24,25-(OH)2-D3","胆钙化醇结合蛋白"],answer:[0],explanation:"肝脏 D3-25-羟化酶将维生素 D3 转化为 25-(OH)-D3，随后在肾脏进一步活化。",source:"教材第91页"},
  {id:"add-d-03",category:"维生素 D",type:"multiple",stem:"可刺激肾脏 25-(OH)-D3-1α-羟化酶活性的因素包括",options:["甲状旁腺素升高","血钙降低","活性维生素 D 浓度降低","低磷膳食摄入"],answer:[0,1,2,3],explanation:"PTH、低钙、低活性维生素 D 和低磷膳食可刺激该羟化酶，促进活性维生素 D 生成。",source:"教材第91页"},
  {id:"add-d-04",category:"维生素 D",type:"single",stem:"血中 25-(OH)-D3 低于多少可认为维生素 D 严重缺乏",options:["<5 ng/ml","<10 ng/ml","<20 ng/ml","<30 ng/ml"],answer:[1],explanation:"教材给出的分级为 <10 ng/ml 严重缺乏，<20 ng/ml 缺乏，21-29 ng/ml 不足，≥30 ng/ml 充足。",source:"教材第93页"},
  {id:"add-d-05",category:"维生素 D",type:"single",stem:"维生素 D 的单位换算正确的是",options:["1 IU=0.025 μg","1 IU=0.25 μg","1 μg=4 IU","1 μg=400 IU"],answer:[0],explanation:"1 IU 维生素 D = 0.025 μg，即 1 μg = 40 IU。",source:"教材第93页"},
  {id:"add-d-06",category:"维生素 D",type:"single",stem:"11 岁及以上人群维生素 D 的 UL 是",options:["20 μg/d","30 μg/d","45 μg/d","50 μg/d"],answer:[3],explanation:"11 岁及以上人群（包括孕妇、乳母）的 UL 为 50 μg/d。",source:"教材第93页"},
  {id:"add-d-07",category:"维生素 D",type:"multiple",stem:"维生素 D 中毒可能出现",options:["血清钙、磷升高","软组织转移性钙化","肾结石","多尿、烦渴和恶心呕吐"],answer:[0,1,2,3],explanation:"维生素 D 过量会导致高钙高磷及相关胃肠、泌尿和软组织钙化表现。",source:"教材第93页"},

  {id:"add-e-01",category:"维生素 E",type:"single",stem:"维生素 E 的吸收需要胆汁帮助形成",options:["胶团","胆红素","内因子复合物","含铁血黄素"],answer:[0],explanation:"生育酚与脂类消化产物在胆汁作用下形成胶团，被动扩散吸收。",source:"教材第94页"},
  {id:"add-e-02",category:"维生素 E",type:"single",stem:"维生素 E 在血液中主要由哪类脂蛋白运输",options:["LDL","HDL 以外的乳酸","纤维蛋白原","运铁蛋白"],answer:[0],explanation:"维生素 E 可由多种脂蛋白运输，其中主要由 LDL 运输，并保护 LDL 免受氧化。",source:"教材第94页"},
  {id:"add-e-03",category:"维生素 E",type:"single",stem:"维生素 E 的吸收率与摄入量增加的关系是",options:["吸收率随摄入量增加而降低","吸收率随摄入量增加而无限升高","完全不受摄入量影响","只在儿童中降低"],answer:[0],explanation:"维生素 E 一般吸收率为 20%-50%，最高约 80%，摄入量增加时吸收率降低。",source:"教材第94页"},
  {id:"add-e-04",category:"维生素 E",type:"single",stem:"维生素 E 缺乏在人群中较常见于",options:["低体重早产儿和脂肪吸收障碍者","所有健康成年人","只吃水果者但无吸收障碍","短期高脂膳食者"],answer:[0],explanation:"维生素 E 缺乏在人类较少见，低体重早产儿、脂蛋白缺乏和脂肪吸收障碍者风险较高。",source:"教材第95页"},
  {id:"add-e-05",category:"维生素 E",type:"single",stem:"成人维生素 E 的 AI 是",options:["7 mg α-TE/d","14 mg α-TE/d","17 mg α-TE/d","40 mg α-TE/d"],answer:[1],explanation:"我国成人（包括孕妇）维生素 E AI 为 14 mg α-TE/d，乳母为 17 mg α-TE/d。",source:"教材第95页"},
  {id:"add-e-06",category:"维生素 E",type:"multiple",stem:"维生素 E 含量较丰富的食物包括",options:["植物油","麦胚和谷类胚芽","坚果和种子","豆类"],answer:[0,1,2,3],explanation:"植物油、麦胚、坚果、种子、豆类和谷类胚芽是维生素 E 的主要食物来源。",source:"教材第96页"},

  {id:"add-b1-01",category:"维生素 B1",type:"single",stem:"维生素 B1 在低浓度时主要通过何种方式吸收",options:["主动转运","简单扩散","吞噬作用","胆汁排泄"],answer:[0],explanation:"B1 浓度低（≤2 μmol/L）时主要主动转运，需要 Na+ 并消耗 ATP；浓度高时可被动扩散。",source:"教材第96页"},
  {id:"add-b1-02",category:"维生素 B1",type:"single",stem:"成人体内维生素 B1 约有多少分布在肌肉中",options:["10%","25%","50%","80%"],answer:[2],explanation:"成人体内维生素 B1 总量约 25-30 mg，约 50% 分布在肌肉中。",source:"教材第96页"},
  {id:"add-b1-03",category:"维生素 B1",type:"single",stem:"维生素 B1 的生物半衰期约为",options:["9-18 小时","9-18 天","9-18 周","9-18 个月"],answer:[1],explanation:"维生素 B1 在体内的生物半衰期为 9-18 天，缺乏膳食 1-2 周后组织含量即可下降。",source:"教材第96页"},
  {id:"add-b1-04",category:"维生素 B1",type:"single",stem:"成人干性脚气病主要表现为",options:["多发性周围神经炎","严重水肿和心衰","皮炎腹泻痴呆","牙龈出血"],answer:[0],explanation:"干性脚气病以多发性周围神经炎为主；湿性脚气病以水肿和心脏症状为主。",source:"教材第97页"},
  {id:"add-b1-05",category:"维生素 B1",type:"single",stem:"婴儿脚气病多发生于哪个年龄阶段",options:["出生后 1-2 周","2-5 月龄","1-2 岁","学龄期"],answer:[1],explanation:"婴儿脚气病多发生于 2-5 月龄，常与乳母维生素 B1 缺乏有关。",source:"教材第97页"},
  {id:"add-b1-06",category:"维生素 B1",type:"single",stem:"红细胞转酮醇酶 TPP 效应越高，通常说明",options:["维生素 B1 越充足","维生素 B1 缺乏越严重","铁储存越多","叶酸吸收越好"],answer:[1],explanation:"加入 TPP 前后转酮醇酶活性差异越大，说明体内酶对 TPP 越依赖，维生素 B1 缺乏越严重。",source:"教材第98页"},
  {id:"add-b1-07",category:"维生素 B1",type:"multiple",stem:"导致食物中维生素 B1 损失的操作包括",options:["米面碾磨过于精细","过分淘米","烹调中加碱","高温烹调"],answer:[0,1,2,3],explanation:"B1 多存在于谷类表皮和胚芽，易溶于水且在碱性和高温条件下损失。",source:"教材第98页"},

  {id:"add-b2-01",category:"维生素 B2",type:"single",stem:"动物来源的维生素 B2 与植物来源相比通常",options:["更容易吸收","更难吸收","完全不能吸收","只在肝脏吸收"],answer:[0],explanation:"教材指出动物来源的维生素 B2 比植物来源的维生素 B2 更容易吸收。",source:"教材第99页"},
  {id:"add-b2-02",category:"维生素 B2",type:"single",stem:"血浆中运输维生素 B2、FMN 和 FAD 的主要蛋白是",options:["白蛋白","运铁蛋白","RBP","TTR"],answer:[0],explanation:"血浆白蛋白、免疫球蛋白和纤维蛋白原可运输 B2，白蛋白是主要运输载体。",source:"教材第99页"},
  {id:"add-b2-03",category:"维生素 B2",type:"single",stem:"维生素 B2 缺乏时典型的舌部表现是",options:["地图舌","草莓舌伴牙龈出血","蓝舌","舌乳头完全增生"],answer:[0],explanation:"B2 缺乏可出现舌炎、舌乳头萎缩，典型表现为地图舌。",source:"教材第100页"},
  {id:"add-b2-04",category:"维生素 B2",type:"single",stem:"口服 5 mg 维生素 B2 后，4 小时尿排出量低于多少提示缺乏",options:["40 μg","200 μg","400 μg","800 μg"],answer:[2],explanation:"B2 尿负荷试验中，4 小时尿排出量 ≤400 μg 为缺乏，400-799 μg 为不足。",source:"教材第100页"},
  {id:"add-b2-05",category:"维生素 B2",type:"single",stem:"维生素 B2 含量较丰富的动物性食物是",options:["动物肝脏、肾脏和心脏","精制植物油","苹果和梨","白砂糖"],answer:[0],explanation:"动物肝、肾、心、乳汁和蛋类含 B2 较丰富，绿色蔬菜和豆类也是植物来源。",source:"教材第100页"},
  {id:"add-b2-06",category:"维生素 B2",type:"multiple",stem:"影响维生素 B2 吸收或稳定性的因素包括",options:["抗酸制剂干扰释放","酒精干扰消化吸收","碱性环境易破坏","光照可造成损失"],answer:[0,1,2,3],explanation:"B2 的释放和吸收受胃酸、胆盐、抗酸制剂和酒精影响，游离 B2 对光敏感，碱性环境中易受破坏。",source:"教材第99-100页"},

  {id:"add-niacin-01",category:"烟酸",type:"single",stem:"烟酸和烟酰胺在体内的生理活性关系是",options:["二者具有相同生理活性","只有烟酸有活性","只有烟酰胺有活性","二者均无活性"],answer:[0],explanation:"烟酸在体内易转变为烟酰胺，两者总称维生素 PP，具有相同生理活性。",source:"教材第101页"},
  {id:"add-niacin-02",category:"烟酸",type:"single",stem:"烟酸在体内构成的主要辅酶是",options:["NAD 和 NADP","FMN 和 FAD","TPP 和 TTP","PLP 和 PMP"],answer:[0],explanation:"烟酸以烟酰胺形式构成辅酶 I（NAD）和辅酶 II（NADP），参与氢的传递。",source:"教材第101页"},
  {id:"add-niacin-03",category:"烟酸",type:"single",stem:"烟酸是维生素中较稳定的一种，通常烹调损失较小，但容易随什么流失",options:["水","脂肪","蛋白质","矿物质沉淀"],answer:[0],explanation:"烟酸对酸、碱、光、氧和加热较稳定，一般烹调损失小，但可随水流失。",source:"教材第101页"},
  {id:"add-niacin-04",category:"烟酸",type:"single",stem:"尿中 2-吡啶酮/N-甲基烟酰胺比值低于多少提示潜在烟酸缺乏",options:["0.3","1.3","2.0","4.0"],answer:[1],explanation:"该比值 1.3-4.0 为正常，低于 1.3 表示有潜在性缺乏。",source:"教材第102页"},
  {id:"add-niacin-05",category:"烟酸",type:"single",stem:"成年男性烟酸的 RNI 是",options:["5 mg NE/d","12 mg NE/d","15 mg NE/d","35 mg NE/d"],answer:[2],explanation:"成年男性烟酸 RNI 为 15 mg NE/d，女性为 12 mg NE/d，UL 为 35 mg NE/d。",source:"教材第102页"},
  {id:"add-niacin-06",category:"烟酸",type:"multiple",stem:"烟酸过量可能产生的副作用包括",options:["皮肤发红","恶心呕吐","高尿酸血症","糖耐量异常"],answer:[0,1,2,3],explanation:"大剂量烟酸可能出现皮肤潮红、胃肠道反应、高尿酸血症和糖耐量异常，长期更大剂量可损伤肝脏。",source:"教材第101页"},

  {id:"add-pan-01",category:"泛酸",type:"single",stem:"低浓度泛酸主要通过何种方式吸收",options:["主动转运","简单扩散","吞噬作用","肾小管重吸收"],answer:[0],explanation:"泛酸在低浓度时主动转运，高浓度时以简单扩散吸收。",source:"教材第102页"},
  {id:"add-pan-02",category:"泛酸",type:"single",stem:"正常膳食成年人尿中泛酸排出量约为",options:["0.2-0.7 mg/d","2-7 mg/d","20-70 mg/d","200-700 mg/d"],answer:[1],explanation:"正常膳食成年人尿中泛酸排出量约 2-7 mg/d，低于 1 mg/d 可提示不足或缺乏。",source:"教材第103页"},
  {id:"add-pan-03",category:"泛酸",type:"single",stem:"泛酸又被称为抗应激维生素的原因是",options:["可减少应激反应中的能量消耗","可直接降低体温","可阻断所有神经冲动","可提高尿钙排出"],answer:[0],explanation:"应激反应伴随大量能量消耗，泛酸参与辅酶 A 代谢并可减少应激时的能量消耗。",source:"教材第103页"},
  {id:"add-pan-04",category:"泛酸",type:"single",stem:"泛酸 AI 的人群差异正确的是",options:["成人 5.0、孕妇 6.0、乳母 7.0 mg/d","成人 7.0、孕妇 6.0、乳母 5.0 mg/d","三者均为 1.0 mg/d","三者均无 AI"],answer:[0],explanation:"2013 版成人 AI 为 5.0 mg/d，孕妇 6.0 mg/d，乳母 7.0 mg/d。",source:"教材第103页"},

  {id:"add-b6-01",category:"维生素 B6",type:"single",stem:"维生素 B6 在肝脏中可转化为多种磷酸化形式，其中主要活性形式是",options:["PLP","PNP","PMP","三者均无活性"],answer:[0],explanation:"维生素 B6 包括吡哆醇、吡哆醛和吡哆胺，PLP 是体内主要活性形式。",source:"教材第104页"},
  {id:"add-b6-02",category:"维生素 B6",type:"single",stem:"维生素 B6 的主要储存部位是",options:["肌肉组织","皮肤角质层","甲状腺","胃腔"],answer:[0],explanation:"组织中维生素 B6 以 PLP 形式储存，肌肉约占储存量的 75%-80%。",source:"教材第104页"},
  {id:"add-b6-03",category:"维生素 B6",type:"single",stem:"异烟肼可诱发维生素 B6 缺乏的原因是",options:["与 PLP 形成复合物","促进 B6 从尿中完全排出","抑制维生素 C 合成","使 B6 转化为维生素 D"],answer:[0],explanation:"异烟肼、环丝氨酸等药物可与 PLP 形成复合物，诱发 B6 缺乏。",source:"教材第104页"},
  {id:"add-b6-04",category:"维生素 B6",type:"single",stem:"色氨酸负荷试验中，维生素 B6 缺乏时尿中哪种物质增加",options:["黄尿酸","甲基丙二酸","FIGLU","尿碘"],answer:[0],explanation:"B6 缺乏时色氨酸代谢受影响，尿中黄尿酸增加，可计算黄尿酸指数评价营养状况。",source:"教材第105页"},
  {id:"add-b6-05",category:"维生素 B6",type:"single",stem:"成人维生素 B6 的 RNI 是",options:["0.4 mg/d","1.4 mg/d","2.4 mg/d","14 mg/d"],answer:[1],explanation:"2013 版成人 B6 RNI 为 1.4 mg/d，妊娠期为 2.4 mg/d。",source:"教材第105页"},
  {id:"add-b6-06",category:"维生素 B6",type:"multiple",stem:"维生素 B6 含量较高的食物包括",options:["鸡肉和鱼肉等白色肉类","肝脏","豆类和坚果","香蕉和卷心菜"],answer:[0,1,2,3],explanation:"白色肉类最丰富，肝脏、豆类、坚果、蛋黄以及部分水果蔬菜也是来源。",source:"教材第105页"},

  {id:"add-biotin-01",category:"生物素",type:"single",stem:"生物素在低浓度时主要以何种方式吸收",options:["主动转运","简单扩散","胆汁乳化","肾小球滤过"],answer:[0],explanation:"生物素在低浓度时主动转运，高浓度时以简单扩散吸收，主要吸收部位是小肠近端。",source:"教材第106页"},
  {id:"add-biotin-02",category:"生物素",type:"single",stem:"长期服用抗生素可能导致生物素缺乏的原因是",options:["抑制肠道细菌合成生物素","破坏肝脏储存蛋白","增加视黄醇排出","促进铁吸收过快"],answer:[0],explanation:"抗生素可抑制肠道细菌合成生物素，当膳食摄入不足时可能导致缺乏。",source:"教材第106页"},
  {id:"add-biotin-03",category:"生物素",type:"single",stem:"生物素缺乏时尿中哪种代谢物会增加",options:["3-羟基异戊酸","甲基丙二酸","2-吡啶酮","尿素"],answer:[0],explanation:"生物素缺乏时尿 3-羟基异戊酸排出量增加，正常成人约 77-195 μmol/24h。",source:"教材第106页"},
  {id:"add-biotin-04",category:"生物素",type:"single",stem:"生物素的成人 AI 是",options:["4 μg/d","40 μg/d","400 μg/d","4 mg/d"],answer:[1],explanation:"2013 版中国居民膳食营养素参考摄入量中，生物素成人 AI 为 40 μg/d。",source:"教材第106页"},
  {id:"add-biotin-05",category:"生物素",type:"multiple",stem:"生物素缺乏的风险因素包括",options:["长期生吃蛋清","长期全静脉营养未补生物素","长期服用苯妥因等抗惊厥药","母乳中生物素不足的婴儿"],answer:[0,1,2,3],explanation:"这些情况可分别通过抗生物素蛋白、缺少肠道来源或药物影响造成生物素缺乏。",source:"教材第106页"},

  {id:"add-folate-01",category:"叶酸",type:"single",stem:"叶酸在小肠吸收前，需要被水解为哪种形式",options:["单谷氨酸叶酸","多谷氨酸叶酸","视黄酸","甲基丙二酸"],answer:[0],explanation:"膳食多谷氨酸叶酸需经空肠刷状缘 γ-谷氨酰水解酶水解为单谷氨酸叶酸后吸收。",source:"教材第107页"},
  {id:"add-folate-02",category:"叶酸",type:"multiple",stem:"可影响叶酸吸收的因素包括",options:["维生素 C 和葡萄糖可促进吸收","锌缺乏可降低叶酸结合酶活性","酒精可抑制吸收","口服避孕药和抗惊厥药物可抑制吸收"],answer:[0,1,2,3],explanation:"这些因素均会影响叶酸的吸收或利用。",source:"教材第107页"},
  {id:"add-folate-03",category:"叶酸",type:"single",stem:"正常成人体内叶酸约有多少储存在肝脏",options:["5%","25%","50%","90%"],answer:[2],explanation:"正常成人叶酸储存量约 5-10 mg，其中约 50% 储存在肝脏。",source:"教材第107页"},
  {id:"add-folate-04",category:"叶酸",type:"single",stem:"红细胞叶酸含量主要反映",options:["近期膳食叶酸摄入","组织细胞内的长期叶酸储存","当日尿量","维生素 B12 的吸收"],answer:[1],explanation:"血清叶酸偏向反映近期摄入，红细胞叶酸反映组织细胞储存和长期营养状况。",source:"教材第108页"},
  {id:"add-folate-05",category:"叶酸",type:"single",stem:"血清总叶酸低于何值可判断为缺乏",options:["1 ng/ml","3 ng/ml","6 ng/ml","16 ng/ml"],answer:[1],explanation:"血清总叶酸 <3 ng/ml 为缺乏，3-6 ng/ml 为不足，>6 ng/ml 为正常。",source:"教材第108页"},
  {id:"add-folate-06",category:"叶酸",type:"single",stem:"叶酸缺乏时，组氨酸负荷试验中尿 FIGLU 排出量会",options:["减少至零","增加","保持不变且与 B12 无关","转化为尿碘"],answer:[1],explanation:"叶酸缺乏时 FIGLU 不能顺利转化为谷氨酸，尿中排出量增加，但 B12 缺乏也可导致增加。",source:"教材第108页"},
  {id:"add-folate-07",category:"叶酸",type:"multiple",stem:"大剂量叶酸可能带来的问题包括",options:["影响锌吸收并导致锌缺乏","掩盖维生素 B12 缺乏","干扰抗惊厥药物作用","可能增加胎儿发育异常风险"],answer:[0,1,2,3],explanation:"叶酸大剂量并非完全无风险，教材列出了这些潜在问题。",source:"教材第108页"},

  {id:"add-b12-01",category:"维生素 B12",type:"single",stem:"维生素 B12 的两种活性辅酶形式是",options:["甲基 B12 和辅酶 B12","TPP 和 TTP","FMN 和 FAD","NAD 和 NADP"],answer:[0],explanation:"B12 以甲基钴胺素和 5-脱氧腺苷钴胺素两种辅酶形式参与体内反应。",source:"教材第109页"},
  {id:"add-b12-02",category:"维生素 B12",type:"single",stem:"维生素 B12-内因子复合物主要在哪个部位被吸收",options:["胃","十二指肠","回肠","结肠"],answer:[2],explanation:"B12 与内因子结合后，复合物在回肠黏膜受体处被吸收。",source:"教材第109页"},
  {id:"add-b12-03",category:"维生素 B12",type:"single",stem:"人体内维生素 B12 主要储存于",options:["肝脏","皮肤","骨骼肌","肺脏"],answer:[0],explanation:"体内 B12 储存量约 2-3 mg，主要储存在肝脏，肝肠循环有利于重复利用。",source:"教材第109页"},
  {id:"add-b12-04",category:"维生素 B12",type:"single",stem:"血清维生素 B12 浓度通常反映",options:["体内储存状况","当日膳食纤维摄入","近期尿碘","骨密度"],answer:[0],explanation:"血清 B12 浓度是反映体内储存的指标，教材给出的正常范围为 120-180 pmol/L。",source:"教材第110页"},
  {id:"add-b12-05",category:"维生素 B12",type:"single",stem:"holoTC II 主要反映维生素 B12 的哪种状态",options:["负平衡的早期状态","严重中毒","骨骼储存","维生素 C 吸收"],answer:[0],explanation:"血清全钴胺传递蛋白 II（holoTC II）是 B12 负平衡的早期指标。",source:"教材第110页"},
  {id:"add-b12-06",category:"维生素 B12",type:"single",stem:"维生素 B12 缺乏时，下列哪两种物质会升高",options:["同型半胱氨酸和甲基丙二酸","尿碘和血钙","血清铁和视黄醇","FIGLU 和尿素"],answer:[0],explanation:"B12 缺乏时同型半胱氨酸和甲基丙二酸含量均可升高。",source:"教材第110页"},
  {id:"add-b12-07",category:"维生素 B12",type:"single",stem:"成人维生素 B12 的 RNI 是",options:["0.24 μg/d","2.4 μg/d","24 μg/d","240 μg/d"],answer:[1],explanation:"成人 B12 RNI 为 2.4 μg/d，孕妇 2.9 μg/d，乳母 3.2 μg/d。",source:"教材第110页"},

  {id:"add-c-01",category:"维生素 C",type:"single",stem:"维生素 C 主要在小肠以何种方式吸收",options:["主动转运","被动滤过","胆汁乳化后吞噬","胃内扩散"],answer:[0],explanation:"维生素 C 主要通过主动转运由小肠上段吸收。",source:"教材第111页"},
  {id:"add-c-02",category:"维生素 C",type:"single",stem:"下列哪种动物与人一样不能在体内合成维生素 C",options:["豚鼠","牛","羊","鸡"],answer:[0],explanation:"人、猴和豚鼠体内不能利用葡萄糖合成维生素 C，需要由食物供给。",source:"教材第111页"},
  {id:"add-c-03",category:"维生素 C",type:"single",stem:"正常成人体内维生素 C 的储存量约为",options:["12-20 mg","120-200 mg","1.2-2.0 g","12-20 g"],answer:[2],explanation:"正常成人体内可储存维生素 C 约 1.2-2.0 g，最高约 3.0 g。",source:"教材第111页"},
  {id:"add-c-04",category:"维生素 C",type:"single",stem:"维生素 C 在体内含量最高的组织是",options:["垂体","血浆","唾液","脂肪组织"],answer:[0],explanation:"维生素 C 含量最高的组织是垂体，其次为肾上腺、肾脏、脾脏和肝脏。",source:"教材第111页"},
  {id:"add-c-05",category:"维生素 C",type:"single",stem:"一次口服维生素 C 2-3 g 可能出现的反应是",options:["腹泻和腹胀","肾上腺皮质增生","严重甲状腺肿","神经脱髓鞘"],answer:[0],explanation:"维生素 C 毒性较低，但一次口服 2-3 g 可能出现腹泻、腹胀；结石患者长期过量还可能增加风险。",source:"教材第112页"},
  {id:"add-c-06",category:"维生素 C",type:"single",stem:"尿负荷试验中，4 小时尿维生素 C 排出量低于多少提示不足",options:["1 mg","5 mg","13 mg","50 mg"],answer:[1],explanation:"口服 500 mg 后，4 小时尿排出 >13 mg 为充足，5-13 mg 为正常，<5 mg 为不足。",source:"教材第112页"},
  {id:"add-c-07",category:"维生素 C",type:"multiple",stem:"减少蔬菜烹调中维生素 C 损失的方法包括",options:["急火快炒","用淀粉勾芡","加醋烹调","长时间浸泡后再烹调"],answer:[0,1,2],explanation:"急火快炒、淀粉勾芡和加醋可减少维生素 C 损失，长时间浸泡会增加水溶性维生素流失。",source:"教材第113页"},
  {id:"add-c-08",category:"维生素 C",type:"single",stem:"中国营养学会推荐成人维生素 C 的 RNI 是",options:["50 mg/d","100 mg/d","200 mg/d","2000 mg/d"],answer:[1],explanation:"成人维生素 C RNI 为 100 mg/d，PI-NCD 为 200 mg/d，UL 为 2000 mg/d。",source:"教材第113页"},

  {id:"deep-p-01",category:"磷",type:"single",stem:"膳食磷摄入量最直接影响哪项血液指标",options:["血清无机磷","血清视黄醇","血清泛酸","血清维生素 C"],answer:[0],explanation:"膳食磷的摄入量直接影响血清无机磷水平，因此可测定血清无机磷评价磷营养。",source:"教材第65页"},
  {id:"deep-p-02",category:"磷",type:"single",stem:"成熟母乳的钙磷比例约为",options:["0.5:1","1:1","1.5:1","3:1"],answer:[2],explanation:"成熟母乳钙磷比例约为 1.5:1，教材认为其钙磷比例优于牛奶。",source:"教材第65页"},
  {id:"deep-p-03",category:"磷",type:"single",stem:"牛奶的钙磷比例约为",options:["1:1","1.5:1","2:1","3:1"],answer:[0],explanation:"牛奶钙磷比约为 1:1，成熟母乳约为 1.5:1。",source:"教材第65页"},
  {id:"deep-p-04",category:"磷",type:"multiple",stem:"磷过量导致低血钙后可能出现",options:["神经兴奋性增强","手足抽搐","惊厥","夜盲症"],answer:[0,1,2],explanation:"过量磷可引起低血钙，进而导致神经兴奋性增强、手足抽搐和惊厥。",source:"教材第65页"},
  {id:"deep-p-05",category:"磷",type:"single",stem:"下列哪类食物是磷的良好来源",options:["瘦肉、禽、蛋和鱼","精制糖","纯植物油","白开水"],answer:[0],explanation:"瘦肉、禽、蛋、鱼、坚果、海带、紫菜、油料种子和豆类均是磷的良好来源。",source:"教材第65页"},

  {id:"deep-mg-01",category:"镁",type:"single",stem:"正常成人体内镁的总量约为",options:["2-3 g","20-38 g","200-380 g","0.2-0.38 g"],answer:[1],explanation:"正常成人体内含镁约 20-38 g。",source:"教材第65页"},
  {id:"deep-mg-02",category:"镁",type:"single",stem:"人体镁约有多少存在于骨骼",options:["5%-10%","27%-30%","60%-65%","90%-95%"],answer:[2],explanation:"镁约 60%-65% 存在于骨骼，约 27% 存在于肌肉、肝脏、心脏和胰腺等组织。",source:"教材第65页"},
  {id:"deep-mg-03",category:"镁",type:"single",stem:"低镁时 Na-K-ATP 酶活性降低，可使哪种细胞兴奋性增高",options:["心肌细胞","肝细胞","脂肪细胞","胃黏膜细胞"],answer:[0],explanation:"Na-K-ATP 酶是镁依赖性酶，细胞内游离镁降低时其活性下降，可使心肌兴奋性增高。",source:"教材第65页"},
  {id:"deep-mg-04",category:"镁",type:"single",stem:"镁作为钙阻断剂时，镁浓度降低会导致",options:["钙进入细胞增多","钙进入细胞减少","钙完全不能进入细胞","血磷必然升高"],answer:[0],explanation:"镁浓度降低时对钙通道的抑制作用减弱，钙进入细胞增多。",source:"教材第65页"},
  {id:"deep-mg-05",category:"镁",type:"single",stem:"硫酸镁溶液对胆道平滑肌的作用是",options:["使奥狄括约肌松弛并促胆汁排空","使奥狄括约肌持续收缩","抑制胆汁形成","使胆汁完全停止排出"],answer:[0],explanation:"硫酸镁可使奥狄括约肌松弛，促使胆囊排空，具有利胆作用。",source:"教材第66页"},
  {id:"deep-mg-06",category:"镁",type:"single",stem:"镁离子在肠道中吸收缓慢、促使水分滞留，可产生什么作用",options:["导泻作用","止泻作用","止吐作用","促凝血作用"],answer:[0],explanation:"镁离子在肠道中吸收缓慢，使水分滞留，具有导泻作用。",source:"教材第66页"},
  {id:"deep-mg-07",category:"镁",type:"single",stem:"血浆镁增加时，对甲状旁腺激素分泌的影响是",options:["抑制分泌","促进分泌","没有任何影响","先完全抑制再持续升高"],answer:[0],explanation:"血浆镁增加可抑制甲状旁腺激素分泌，镁水平下降则可促进其分泌。",source:"教材第66页"},
  {id:"deep-mg-08",category:"镁",type:"multiple",stem:"下列哪些情况可造成镁摄入或体内镁不足",options:["饥饿","蛋白质-能量营养不良","长期肠外营养","慢性酒精中毒"],answer:[0,1,2,3],explanation:"教材将这些情况列为镁摄入不足或体内不足的原因。",source:"教材第66页"},
  {id:"deep-mg-09",category:"镁",type:"single",stem:"镁缺乏时常见的神经肌肉表现是",options:["反射亢进和共济失调","反射消失且无肌肉症状","视力突然下降","皮肤色素沉着"],answer:[0],explanation:"镁缺乏可引起神经肌肉兴奋性亢进，出现肌肉震颤、手足搐搦、反射亢进和共济失调。",source:"教材第66页"},
  {id:"deep-mg-10",category:"镁",type:"single",stem:"静脉内镁负荷试验中，输入镁有多少以上保留在体内可提示缺镁",options:["10%","30%","50%","90%"],answer:[2],explanation:"12 小时内输入含 30 mmol 硫酸镁的葡萄糖液，若输入镁 >50% 保留在体内，提示缺镁。",source:"教材第66页"},

  {id:"deep-fe-01",category:"铁",type:"single",stem:"铁在组织呼吸中参与电子传递的主要蛋白是",options:["细胞色素酶类","白蛋白","胶原蛋白","肌动蛋白"],answer:[0],explanation:"细胞色素酶类参与氧化还原过程中的电子传递，并在三羧酸循环中参与能量生成。",source:"教材第67页"},
  {id:"deep-fe-02",category:"铁",type:"single",stem:"肌红蛋白中铁的主要作用是",options:["在肌肉组织中转运和储存氧","参与肠道铁吸收","合成胆汁酸","调节甲状腺激素"],answer:[0],explanation:"肌红蛋白由血红素和珠蛋白组成，主要在肌肉组织中转运和储存氧。",source:"教材第67页"},
  {id:"deep-fe-03",category:"铁",type:"single",stem:"铁缺乏对造血的直接影响是",options:["血红蛋白合成受阻","血红蛋白合成增加","白细胞全部转为红细胞","红细胞寿命必然延长"],answer:[0],explanation:"铁在骨髓中参与血红素和血红蛋白合成，缺铁可影响血红蛋白和 DNA 合成。",source:"教材第67页"},
  {id:"deep-fe-04",category:"铁",type:"single",stem:"血红素铁主要来自动物性食物，并以何种复合物形式被吸收",options:["含铁卟啉复合物","铁蛋白复合物","运铁蛋白复合物","植酸铁复合物"],answer:[0],explanation:"血红素铁以含铁卟啉复合物形式进入小肠黏膜细胞，随后释放游离铁。",source:"教材第68页"},
  {id:"deep-fe-05",category:"铁",type:"single",stem:"非血红素铁的吸收主要由哪种转运蛋白介导",options:["DMT-1","RBP","DBP","TC II"],answer:[0],explanation:"二价金属离子转运蛋白 DMT-1 介导二价铁进入小肠黏膜细胞。",source:"教材第68页"},
  {id:"deep-fe-06",category:"铁",type:"single",stem:"铁不能以游离离子形式在肠黏膜细胞内转运，主要是因为会导致",options:["自由基生成和膜结构损伤","维生素 C 合成增加","碘被快速吸收","胆汁完全停止分泌"],answer:[0],explanation:"游离铁可促进自由基生成，破坏细胞膜，因此需要细胞内蛋白参与储存和转运。",source:"教材第68页"},
  {id:"deep-fe-07",category:"铁",type:"single",stem:"体内过量铁主要储存为铁蛋白时，Fe2+ 会被氧化为",options:["Fe3+","Fe0","Fe4+","硫化铁"],answer:[0],explanation:"脱铁铁蛋白可摄取 Fe2+，并将其氧化为 Fe3+ 沉淀在蛋白质外壳内。",source:"教材第68页"},
  {id:"deep-fe-08",category:"铁",type:"single",stem:"女性储存性铁一般约为",options:["0.3-1.0 g","3-10 g","30-100 g","0.03-0.10 mg"],answer:[0],explanation:"一般女性存储性铁约 0.3-1.0 g，男性可达 0.5-1.5 g。",source:"教材第68页"},
  {id:"deep-fe-09",category:"铁",type:"multiple",stem:"机体铁吸收可因哪些情况增加",options:["贫血","妊娠","生长发育","月经过多造成铁丢失"],answer:[0,1,2,3],explanation:"铁需要增加或铁丢失增加时，机体可通过提高吸收率进行调节。",source:"教材第68页"},
  {id:"deep-fe-10",category:"铁",type:"single",stem:"下列哪项属于血红蛋白是缺铁晚期指标的含义",options:["血红蛋白正常不能排除缺铁","只要血红蛋白正常就绝对不缺铁","血红蛋白是最早变化指标","血红蛋白不能用于判断贫血"],answer:[0],explanation:"血红蛋白低可诊断贫血，但处于正常范围不能排除早期缺铁，血红蛋白属于晚期指标。",source:"教材第70页"},
  {id:"deep-fe-11",category:"铁",type:"single",stem:"平均红细胞容量 MCV 主要反映",options:["红细胞整体体积大小","红细胞内铁蛋白含量","血浆总铁含量","血小板聚集力"],answer:[0],explanation:"MCV 反映整体红细胞体积大小，RDW 反映周围红细胞大小的异质性。",source:"教材第70页"},
  {id:"deep-fe-12",category:"铁",type:"single",stem:"下列哪项可使血清铁测量结果受到影响",options:["进食状况和溶血","只受身高影响","只受视力影响","与任何生理状态无关"],answer:[0],explanation:"血清铁易受进食、生理状态、溶血和环境中铁的影响，不能全面反映储存与代谢。",source:"教材第70页"},
  {id:"deep-fe-13",category:"铁",type:"single",stem:"缺铁性贫血患者常见的指甲变化是",options:["反甲和指甲脆薄","指甲完全变黑且增厚","指甲出现氟斑","指甲生长明显加快"],answer:[0],explanation:"缺铁性贫血可出现指甲脆薄、反甲等表现。",source:"教材第69-70页"},
  {id:"deep-fe-14",category:"铁",type:"multiple",stem:"儿童缺铁可能影响",options:["注意力和记忆力","学习能力","免疫功能","生长发育"],answer:[0,1,2,3],explanation:"儿童缺铁可造成发育受阻、注意力和记忆力调节障碍、学习能力下降及免疫功能障碍。",source:"教材第69-70页"},
  {id:"deep-fe-15",category:"铁",type:"single",stem:"反复输血导致的铁过量属于",options:["继发性铁过量","原发性铁过量","铁减少期","亚临床缺铁"],answer:[0],explanation:"铁剂治疗和反复输血属于继发性铁过量；遗传性血色素沉积症属于原发性铁过量。",source:"教材第69页"},

  {id:"deep-zn-01",category:"锌",type:"single",stem:"锌参与下列哪种抗氧化酶的组成",options:["超氧化物歧化酶","胃蛋白酶","胰脂酶","乳糖酶"],answer:[0],explanation:"超氧化物歧化酶、苹果酸脱氢酶、碱性磷酸酶和乳酸脱氢酶等均属于重要含锌酶。",source:"教材第71页"},
  {id:"deep-zn-02",category:"锌",type:"single",stem:"锌缺乏可造成 RNA、DNA 和蛋白质合成障碍，首先影响的是",options:["细胞生长、分裂和分化","胆汁排泄","维生素 D 皮肤合成","氟的肾排泄"],answer:[0],explanation:"锌参与核酸和蛋白质合成，缺乏时细胞分裂减少，导致生长停止。",source:"教材第71页"},
  {id:"deep-zn-03",category:"锌",type:"single",stem:"锌缺乏导致儿童长期生长障碍，可表现为",options:["侏儒症样生长停滞","肢端肥大","骨骼过度钙化","甲状腺肿大"],answer:[0],explanation:"儿童长期缺锌可导致侏儒症样的生长发育障碍。",source:"教材第72页"},
  {id:"deep-zn-04",category:"锌",type:"single",stem:"成人锌中毒的消化道表现不包括",options:["发热","腹泻","恶心呕吐","牙龈出血"],answer:[3],explanation:"锌摄入 4-8 g 以上可出现发热、腹泻、恶心、呕吐和嗜睡；牙龈出血不是教材所列锌中毒表现。",source:"教材第72页"},

  {id:"deep-se-01",category:"硒",type:"single",stem:"硒参与谷胱甘肽过氧化物酶时，主要发挥的是",options:["抗氧化作用","促进脂肪储存","直接合成胆汁","阻止所有蛋白质分解"],answer:[0],explanation:"硒是 GSH-Px 的组成成分，参与机体抗氧化防御。",source:"教材第74页"},
  {id:"deep-se-02",category:"硒",type:"single",stem:"缺硒除克山病外，还被认为与哪种疾病有关",options:["大骨节病","坏血病","脚气病","夜盲症"],answer:[0],explanation:"缺硒被认为是大骨节病的重要原因，该病主要发生在青少年期。",source:"教材第74页"},
  {id:"deep-se-03",category:"硒",type:"multiple",stem:"硒缺乏可能影响的免疫功能包括",options:["细胞免疫","体液免疫","抗体应答","补体应答"],answer:[0,1,2,3],explanation:"缺硒可影响细胞免疫和体液免疫，补硒可提高抗体和补体应答能力。",source:"教材第74页"},
  {id:"deep-se-04",category:"硒",type:"single",stem:"硒摄入量高时，可在肝内甲基化生成挥发性化合物并从何处排出",options:["肺部呼气","肾小球滤过","皮肤角质脱落","胆汁完全排出"],answer:[0],explanation:"高硒摄入时可生成挥发性二甲基硒化合物，经肺部呼气排出。",source:"教材第74页"},
  {id:"deep-se-05",category:"硒",type:"single",stem:"评价低硒人群时，GSH-Px 活性指标的局限是",options:["正常硒水平以上会达到平台","只能评价近期铁摄入","只能评价维生素 C","始终与血硒无关"],answer:[0],explanation:"GSH-Px 活性随硒增加而升高，但血硒达到 1.27 μmol/L 后趋于饱和，适合评价低于正常硒水平者。",source:"教材第74页"},
  {id:"deep-se-06",category:"硒",type:"single",stem:"硒含量丰富的动物性食物是",options:["海产品和动物内脏","精白糖和植物油","苹果和梨","土豆和白米"],answer:[0],explanation:"海产品和动物内脏，如鱼子酱、海参、牡蛎和猪肾，是硒的良好食物来源。",source:"教材第75页"},
  {id:"deep-se-07",category:"硒",type:"single",stem:"恩施地区居民慢性硒中毒的主要环境原因是",options:["水土中硒含量高导致食物含硒量高","长期饮用低氟水","膳食中完全没有动物性食物","长期缺乏阳光"],answer:[0],explanation:"恩施地区水土含硒量高，植物含硒量大，居民膳食硒摄入过高而发生慢性中毒。",source:"教材第74页"},

  {id:"deep-cr-01",category:"铬、碘与其他矿物质",type:"single",stem:"铬在人体内主要以哪种价态存在",options:["三价铬","六价铬","零价铬","四价铬"],answer:[0],explanation:"铬在体内分布广泛，主要以三价铬形式存在。",source:"教材第75页"},
  {id:"deep-cr-02",category:"铬、碘与其他矿物质",type:"single",stem:"有机物结合可提高铬的吸收率，下列哪种形式吸收率可达 10%-25%",options:["啤酒酵母中的葡萄糖耐量因子形式","六价铬工业粉尘","铬与植酸结合形式","游离金属铬"],answer:[0],explanation:"啤酒酵母中的铬以葡萄糖耐量因子形式存在，吸收率可达 10%-25%。",source:"教材第75页"},
  {id:"deep-cr-03",category:"铬、碘与其他矿物质",type:"multiple",stem:"铬缺乏可能出现的表现包括",options:["生长停滞","血脂增高","葡萄糖耐量异常","高血糖和尿糖"],answer:[0,1,2,3],explanation:"长期铬摄入不足可出现生长停滞、血脂增高、葡萄糖耐量异常，并伴高血糖和尿糖。",source:"教材第76页"},
  {id:"deep-cr-04",category:"铬、碘与其他矿物质",type:"single",stem:"职业性接触六价铬可能导致",options:["急慢性中毒和致癌性","维生素 D 缺乏","单纯低血糖","坏血病"],answer:[0],explanation:"六价铬毒性较大，主要来源于工业生产，职业性接触可导致急性中毒、慢性中毒和致癌性。",source:"教材第76页"},

  {id:"deep-i-01",category:"铬、碘与其他矿物质",type:"single",stem:"甲状腺之外的组织中，碘主要以什么形式存在于血液",options:["蛋白结合碘","游离碘气体","碘化钙晶体","甲基碘挥发物"],answer:[0],explanation:"血液中的碘主要为蛋白结合碘（PBI），浓度约 30-60 μg/L。",source:"教材第76页"},
  {id:"deep-i-02",category:"铬、碘与其他矿物质",type:"single",stem:"一分子 MIT 与一分子 DIT 偶联形成",options:["T3","T4","TSH","PBI"],answer:[0],explanation:"一分子 MIT 与一分子 DIT 偶联生成三碘甲腺原氨酸 T3。",source:"教材第77页"},
  {id:"deep-i-03",category:"铬、碘与其他矿物质",type:"single",stem:"甲状腺素主要以何种形式储存在甲状腺滤泡腔胶质中",options:["甲状腺球蛋白形式","游离 T3 形式","血红蛋白形式","与 RBP 结合形式"],answer:[0],explanation:"甲状腺球蛋白通过胞饮进入甲状腺细胞，蛋白酶分解后释放 T3、T4。",source:"教材第77页"},
  {id:"deep-i-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"碘缺乏对胎儿和儿童的影响包括",options:["胎儿神经肌肉发育受影响","围生期死亡率上升","生长发育迟缓","严重时发生呆小症"],answer:[0,1,2,3],explanation:"严重孕期缺碘和儿童期缺碘均会损害生长、神经和智力发育。",source:"教材第77页"},
  {id:"deep-i-05",category:"铬、碘与其他矿物质",type:"single",stem:"中国从 1995 年开始在全国实施的碘缺乏病干预策略是",options:["普遍食盐加碘","普遍食盐加氟","全部取消海产品","只给孕妇补铁"],answer:[0],explanation:"我国 1995 年开始实施普遍食盐加碘（USI）策略，以改善人群碘缺乏。",source:"教材第77页"},
  {id:"deep-i-06",category:"铬、碘与其他矿物质",type:"single",stem:"长期高碘摄入可能导致",options:["高碘性甲状腺肿","只会导致缺铁","必然导致夜盲","只会导致坏血病"],answer:[0],explanation:"长期高碘摄入可导致高碘性甲状腺肿，也可能引起甲亢、甲减和桥本氏甲状腺炎。",source:"教材第77页"},
  {id:"deep-i-07",category:"铬、碘与其他矿物质",type:"single",stem:"尿碘评价个体近期碘营养时，24 小时尿样的优点是",options:["可反映近期碘摄入","能直接反映多年骨碘储存","不受摄入量影响","只适合评价维生素 C"],answer:[0],explanation:"24 小时尿碘排出量评价个体近期碘营养效果较好，随机尿常用尿碘/肌酐比值提高可靠性。",source:"教材第77-78页"},
  {id:"deep-i-08",category:"铬、碘与其他矿物质",type:"single",stem:"评价孕妇群体碘营养时，不能简单用儿童尿碘中位数代替，主要因为",options:["孕妇与普通成人及儿童的碘需要和状态有差异","孕妇完全不排碘","儿童没有甲状腺","尿碘只能测血糖"],answer:[0],explanation:"儿童尿碘中位数与普通成人较接近，但与孕妇这一特殊人群相差较大，孕妇需单独评价。",source:"教材第78页"},

  {id:"deep-cu-01",category:"铬、碘与其他矿物质",type:"single",stem:"成人体内铜总量约为",options:["5-12 mg","50-120 mg","500-1200 mg","5-12 g"],answer:[1],explanation:"成人体内含铜量约为 50-120 mg。",source:"教材第78页"},
  {id:"deep-cu-02",category:"铬、碘与其他矿物质",type:"single",stem:"成人各组织中铜含量最高的部位之一是",options:["肝脏","脑垂体","甲状腺滤泡腔","胃液"],answer:[0],explanation:"肝脏、脑、肾脏、心脏和头发中铜含量较高，脑垂体、甲状腺和胸腺较低。",source:"教材第78页"},
  {id:"deep-cu-03",category:"铬、碘与其他矿物质",type:"single",stem:"铜蓝蛋白由何处合成",options:["肝脏","胃黏膜","甲状腺","骨骼肌"],answer:[0],explanation:"铜蓝蛋白在肝脏合成，可催化 Fe2+ 氧化为 Fe3+。",source:"教材第78页"},
  {id:"deep-cu-04",category:"铬、碘与其他矿物质",type:"single",stem:"含铜的赖氨酰氧化酶主要促进",options:["胶原蛋白和弹性蛋白交联","铁还原为 Fe2+","碘化酪氨酸脱碘","维生素 C 氧化"],answer:[0],explanation:"赖氨酰氧化酶促进骨髓、皮肤和血管中胶原蛋白及弹性蛋白的交联。",source:"教材第78页"},
  {id:"deep-cu-05",category:"铬、碘与其他矿物质",type:"single",stem:"铜缺乏可引起哪种类型的贫血",options:["缺铁性贫血样表现","巨幼红细胞贫血必然出现","溶血性贫血必然出现","再生障碍性贫血必然出现"],answer:[0],explanation:"铜蓝蛋白参与铁的吸收和转运，缺铜可引起缺铁性贫血。",source:"教材第78页"},
  {id:"deep-cu-06",category:"铬、碘与其他矿物质",type:"multiple",stem:"铜参与的生理功能包括",options:["儿茶酚胺合成","胶原蛋白交联","胆固醇代谢","激素分泌调节"],answer:[0,1,2,3],explanation:"铜参与神经递质、胶原和弹性蛋白、胆固醇、心脏、免疫和激素等功能。",source:"教材第78页"},

  {id:"deep-mn-01",category:"铬、碘与其他矿物质",type:"single",stem:"锰在小肠吸收时，膳食铁浓度增高会使吸收",options:["受到抑制","明显增加","完全不受影响","转变为铜吸收"],answer:[0],explanation:"植酸盐和铁浓度增高抑制锰吸收，膳食纤维、钙和磷浓度增高可促进吸收。",source:"教材第80页"},
  {id:"deep-mn-02",category:"铬、碘与其他矿物质",type:"single",stem:"评价锰营养状况目前的主要困难是",options:["缺乏可靠的生物学指标","锰不能进入血液","锰只能在骨骼中测量","所有锰均从肺排出"],answer:[0],explanation:"目前没有可靠的锰营养评价生物学指标，尿锰也不能反映膳食锰摄入量。",source:"教材第80页"},
  {id:"deep-mn-03",category:"铬、碘与其他矿物质",type:"single",stem:"锰含量较丰富的食物是",options:["糙米、米糠和麦芽","精制谷类和奶类","鱼肉和脂肪","精制糖"],answer:[0],explanation:"糙米、米糠、麦芽、麦麸、核桃、河蚌、茶叶和咖啡含锰丰富。",source:"教材第80页"},
  {id:"deep-mn-04",category:"铬、碘与其他矿物质",type:"multiple",stem:"下列食物中锰含量通常较低的是",options:["精制谷类","脂肪","鱼禽肉","奶类"],answer:[0,1,2,3],explanation:"教材指出精制谷类、脂肪、鱼、禽、肉和奶类中锰含量较低。",source:"教材第80页"},

  {id:"deep-f-01",category:"铬、碘与其他矿物质",type:"single",stem:"人体内氟总量约为",options:["0.26 g","2.6 g","26 g","260 g"],answer:[1],explanation:"正常人体内含氟总量约 2.6 g，主要存在于骨骼和牙齿。",source:"教材第80页"},
  {id:"deep-f-02",category:"铬、碘与其他矿物质",type:"single",stem:"适量氟对骨骼的作用是",options:["有利于钙磷利用和骨质坚硬","完全阻止骨形成","使骨盐全部溶解","直接合成胶原蛋白"],answer:[0],explanation:"适量氟有利于钙和磷利用，促进骨形成并增强骨质坚硬性。",source:"教材第80页"},
  {id:"deep-f-03",category:"铬、碘与其他矿物质",type:"single",stem:"氟在骨骼中的沉积与年龄的关系是",options:["随年龄增加而减少","与年龄完全无关","随年龄增加而增加","只在出生前沉积"],answer:[0],explanation:"氟在骨骼中的沉积与年龄呈负相关，年龄越大沉积倾向越低。",source:"教材第80页"},
  {id:"deep-f-04",category:"铬、碘与其他矿物质",type:"single",stem:"目前人类尚未发现氟的哪种情况",options:["确切或特异的氟缺乏症","氟中毒","氟斑牙","氟骨症"],answer:[0],explanation:"高等动物和人类尚未发现确切或特异的氟缺乏症，但低氟地区龋齿率可升高。",source:"教材第80页"},
  {id:"deep-f-05",category:"铬、碘与其他矿物质",type:"single",stem:"慢性氟中毒主要发生在",options:["长期饮用高氟水的地区","所有低氟地区","只吃海产品地区","完全无水地区"],answer:[0],explanation:"慢性氟中毒主要因高氟地区居民长期摄入高氟饮水所致。",source:"教材第80页"},

  {id:"deep-vg-01",category:"维生素总论",type:"single",stem:"维生素按溶解性通常分为",options:["脂溶性和水溶性两类","酸性和碱性两类","动物性和植物性两类","宏量和微量两类"],answer:[0],explanation:"教材按溶解性将维生素分为脂溶性维生素和水溶性维生素。",source:"教材第83页"},
  {id:"deep-vg-02",category:"维生素总论",type:"multiple",stem:"脂溶性维生素的共同特点包括",options:["不溶于水而溶于脂肪和有机溶剂","常与食物脂类共存","吸收与肠道脂类密切相关","摄入不足时缺乏症状通常较慢出现"],answer:[0,1,2,3],explanation:"脂溶性维生素包括 A、D、E、K，依赖脂类吸收、易储存，缺乏通常发展较慢。",source:"教材第83页"},
  {id:"deep-vg-03",category:"维生素总论",type:"single",stem:"下列哪组全部属于水溶性维生素",options:["B1、B2、烟酸、C","A、D、E、K","A、C、D、E","D、E、B12、K"],answer:[0],explanation:"水溶性维生素包括 B 族维生素和维生素 C。",source:"教材第83页"},
  {id:"deep-vg-04",category:"维生素总论",type:"single",stem:"大多数水溶性维生素在体内主要以何种形式参与代谢",options:["辅酶形式","结构脂肪形式","胆汁盐形式","游离胆固醇形式"],answer:[0],explanation:"大多数水溶性维生素以辅酶形式参与物质和能量代谢。",source:"教材第83页"},
  {id:"deep-vg-05",category:"维生素总论",type:"single",stem:"水溶性维生素组织耗竭时，尿负荷试验通常表现为尿中排出量",options:["减少","增加到无限大","完全不变","先增加后消失且不受储存影响"],answer:[0],explanation:"当组织耗竭时，摄入的水溶性维生素会被组织大量摄取利用，尿中排出量减少。",source:"教材第83页"},

  {id:"deep-a-09",category:"维生素 A",type:"single",stem:"植物性食物中通常不含有哪类维生素 A 物质",options:["已形成的维生素 A","维生素 A 原类胡萝卜素","β-胡萝卜素","α-胡萝卜素"],answer:[0],explanation:"植物中不含已形成的维生素 A，但有些有色植物含可转化为维生素 A 的类胡萝卜素。",source:"教材第84页"},
  {id:"deep-a-10",category:"维生素 A",type:"single",stem:"下列类胡萝卜素中属于重要维生素 A 原的是",options:["β-胡萝卜素","玉米黄素","叶黄素","番茄红素"],answer:[0],explanation:"β-胡萝卜素是最重要的维生素 A 原类胡萝卜素之一，其他三者不具有维生素 A 活性。",source:"教材第84页"},
  {id:"deep-a-11",category:"维生素 A",type:"multiple",stem:"维生素 A 和胡萝卜素的稳定性特点包括",options:["对酸和碱相对稳定","氧、光和高温可造成破坏","脂肪酸败可严重破坏","维生素 E 和 C 等抗氧化剂可提高稳定性"],answer:[0,1,2,3],explanation:"A 和胡萝卜素对酸碱相对稳定，但对氧化、高温、光照和脂肪酸败敏感，抗氧化环境有保护作用。",source:"教材第85页"},
  {id:"deep-a-12",category:"维生素 A",type:"single",stem:"膳食中类胡萝卜素吸收率随摄入量增加通常会",options:["降低","升高到 100%","完全不变","只在孕妇中降低"],answer:[0],explanation:"类胡萝卜素吸收率随摄入量增加而降低，有时甚至低于 5%。",source:"教材第85页"},
  {id:"deep-a-13",category:"维生素 A",type:"single",stem:"视黄醛转变为视黄酸的反应特点是",options:["不可逆","可无限逆转","必须由内因子催化","只在肾脏发生"],answer:[0],explanation:"视黄醇和视黄醛可相互转化，但视黄醛转变为视黄酸是不可逆反应。",source:"教材第85页"},
  {id:"deep-a-14",category:"维生素 A",type:"single",stem:"血浆胡萝卜素水平主要反映",options:["近期胡萝卜素摄入","肝脏维生素 A 长期储存","骨钙储存","维生素 B12 负平衡"],answer:[0],explanation:"血浆胡萝卜素水平一般反映近期摄入情况，不能反映体内储存水平。",source:"教材第85页"},
  {id:"deep-a-15",category:"维生素 A",type:"single",stem:"肝脏储存维生素 A 的主要化学形式是",options:["棕榈酸视黄酯","游离视黄酸","视紫红质","β-隐黄素"],answer:[0],explanation:"肝脏中视黄醇主要以棕榈酸视黄酯形式储存在肝星状细胞和肝主细胞。",source:"教材第86页"},
  {id:"deep-a-16",category:"维生素 A",type:"single",stem:"视黄醇-RBP-TTR 复合体的比例约为",options:["1:1:1","1:2:1","2:1:1","1:1:2"],answer:[0],explanation:"视黄醇与 RBP 按 1:1 结合，再与 TTR 形成 1:1:1 的循环复合体。",source:"教材第86页"},
  {id:"deep-a-17",category:"维生素 A",type:"single",stem:"维生素 A 参与视觉时，11-顺式视黄醛与哪种蛋白结合形成视紫红质",options:["视蛋白","白蛋白","RBP","运铁蛋白"],answer:[0],explanation:"视紫红质由 11-顺式视黄醛的醛基与视蛋白赖氨酸的氨基形成的结构组成。",source:"教材第86页"},
  {id:"deep-a-18",category:"维生素 A",type:"single",stem:"暗适应时间延长首先提示可能缺乏",options:["维生素 A","维生素 B1","维生素 B12","维生素 C"],answer:[0],explanation:"维生素 A 缺乏时视紫红质再生受影响，暗适应时间延长。",source:"教材第86页"},
  {id:"deep-a-19",category:"维生素 A",type:"single",stem:"维生素 A 通过 RAR/RXR 主要调节",options:["基因转录和细胞分化","肾脏排碘","铁的氧化还原","氟的骨沉积"],answer:[0],explanation:"视黄酸与 RAR/RXR 结合并影响 DNA 转录，调节多种组织细胞的生长和分化。",source:"教材第87页"},
  {id:"deep-a-20",category:"维生素 A",type:"multiple",stem:"维生素 A 缺乏可造成的上皮变化包括",options:["上皮基底层增生变厚","表层角化","皮肤干燥","机体天然屏障功能减弱"],answer:[0,1,2,3],explanation:"A 缺乏可使糖蛋白合成异常，出现上皮增生、角化和干燥，削弱抗感染屏障。",source:"教材第87页"},
  {id:"deep-a-21",category:"维生素 A",type:"single",stem:"维生素 A 也被称为抗感染维生素，主要因为它能增强",options:["巨噬细胞和自然杀伤细胞功能","肾小球滤过","尿酸排出","骨骼氟沉积"],answer:[0],explanation:"维生素 A 可调节细胞和体液免疫，增强巨噬细胞和自然杀伤细胞活力。",source:"教材第87页"},
  {id:"deep-a-22",category:"维生素 A",type:"single",stem:"维生素 A 急性毒性通常发生于成人摄入约为 RNI 的",options:["1 倍","5 倍","100 倍","1000 倍以下"],answer:[2],explanation:"成人一次或连续多次摄入约为 RNI 100 倍以上可发生急性毒性，儿童约为 20 倍。",source:"教材第88页"},
  {id:"deep-a-23",category:"维生素 A",type:"single",stem:"维生素 A 慢性中毒一般可在摄入达到 RNI 多少倍以上时发生",options:["2 倍","5 倍","10 倍","100 倍"],answer:[2],explanation:"维生素 A 使用剂量达到 RNI 10 倍以上可发生慢性中毒。",source:"教材第88页"},
  {id:"deep-a-24",category:"维生素 A",type:"multiple",stem:"维生素 A 过量的早期急性症状包括",options:["恶心呕吐","头痛和眩晕","视觉模糊","婴儿囟门突起"],answer:[0,1,2,3],explanation:"教材列出的急性毒性早期症状包括这些表现，极大剂量还可能致命。",source:"教材第88页"},
  {id:"deep-a-25",category:"维生素 A",type:"single",stem:"大量摄入类胡萝卜素通常首先造成的可逆表现是",options:["高胡萝卜素血症和皮肤黄染","严重肝衰竭","神经脱髓鞘","低血糖昏迷"],answer:[0],explanation:"类胡萝卜素过量通常毒性较低，可出现类似黄疸的皮肤改变，停止摄入后慢慢消失。",source:"教材第88页"},
  {id:"deep-a-26",category:"维生素 A",type:"single",stem:"相对剂量反应试验 RDR 主要用于间接估计",options:["肝脏维生素 A 储备","近期维生素 C 摄入","铁吸收率","尿碘排出量"],answer:[0],explanation:"RDR 是间接估计肝脏维生素 A 储备相对充足程度的方法。",source:"教材第89页"},

  {id:"deep-d-08",category:"维生素 D",type:"single",stem:"食物维生素 D 进入小肠后与脂溶性物质形成胶团，主要依赖",options:["胆汁","内因子","胃蛋白酶","运铁蛋白"],answer:[0],explanation:"胆汁帮助维生素 D 与其他脂溶性物质形成胶团并被动吸收。",source:"教材第91页"},
  {id:"deep-d-09",category:"维生素 D",type:"single",stem:"吸收后的维生素 D 进入血液时可掺入",options:["乳糜微粒","血红蛋白","含铁血黄素","甲状腺球蛋白"],answer:[0],explanation:"食物来源维生素 D 吸收后掺入乳糜微粒，经淋巴入血。",source:"教材第91页"},
  {id:"deep-d-10",category:"维生素 D",type:"single",stem:"皮肤合成的维生素 D3 在血浆中约有多少与 DBP 结合运输",options:["10%","30%","60%","100%"],answer:[2],explanation:"皮肤产生的维生素 D3 中约 60% 在血浆中与维生素 D 结合蛋白 DBP 结合。",source:"教材第91页"},
  {id:"deep-d-11",category:"维生素 D",type:"single",stem:"活性维生素 D 促进肾小管重吸收时，对磷的作用相较于钙",options:["促进磷重吸收更明显","促进钙重吸收更明显","二者完全相同","只促进钠重吸收"],answer:[0],explanation:"1,25-(OH)2-D3 促进磷重吸收的作用比促进钙重吸收更明显。",source:"教材第92页"},
  {id:"deep-d-12",category:"维生素 D",type:"single",stem:"血钙降低时，血液中甲状旁腺素通常",options:["升高","降低","完全不变","转化为降钙素"],answer:[0],explanation:"血钙降低时 PTH 升高，促进活性维生素 D 生成并通过肠、肾、骨升高血钙。",source:"教材第92页"},
  {id:"deep-d-13",category:"维生素 D",type:"single",stem:"血钙过高时，降钙素分泌增加会使尿中钙磷排出",options:["增加","减少","完全停止","只增加钠排出"],answer:[0],explanation:"血钙过高时 PTH 降低、降钙素增加，尿中钙和磷排出增加。",source:"教材第92页"},
  {id:"deep-d-14",category:"维生素 D",type:"multiple",stem:"婴儿佝偻病可能出现",options:["X 形或 O 形腿","鸡胸","肋骨串珠","出牙推迟"],answer:[0,1,2,3],explanation:"维生素 D 缺乏影响骨钙化，幼儿可出现下肢弯曲、鸡胸、肋骨串珠、出牙推迟等。",source:"教材第92页"},

  {id:"deep-e-07",category:"维生素 E",type:"single",stem:"α-生育酚的理化性质正确的是",options:["对热和酸稳定、对氧敏感","对氧完全稳定","对碱稳定而对酸不稳定","不溶于脂肪和有机溶剂"],answer:[0],explanation:"α-生育酚对热及酸稳定，对碱不稳定，对氧极为敏感，油脂酸败会加速破坏。",source:"教材第94页"},
  {id:"deep-e-08",category:"维生素 E",type:"single",stem:"食物中的生育三烯酚在吸收前需要先经酶水解，主要包括",options:["胰酯酶和肠黏膜酯酶","胃蛋白酶和内因子","谷胱甘肽过氧化物酶和 SOD","DMT-1 和 RBP"],answer:[0],explanation:"生育三烯酚多以酯化形式存在，需经胰酯酶和肠黏膜酯酶水解后才能吸收。",source:"教材第94页"},
  {id:"deep-e-09",category:"维生素 E",type:"single",stem:"血浆维生素 E 浓度与血浆总脂浓度的关系是",options:["正相关","负相关","完全无关","只在儿童中正相关"],answer:[0],explanation:"维生素 E 溶于脂质并由脂蛋白运输，因此血浆浓度与总脂浓度呈正相关。",source:"教材第94页"},
  {id:"deep-e-10",category:"维生素 E",type:"single",stem:"维生素 E 缺乏时，肝脏和血浆中的维生素 E 通常",options:["下降较快","下降很慢而脂肪中先下降","完全不变","只会升高"],answer:[0],explanation:"维生素 E 缺乏时肝脏和血浆中的水平下降较快，而脂肪组织中的下降相对缓慢。",source:"教材第94页"},
  {id:"deep-e-11",category:"维生素 E",type:"single",stem:"维生素 E 抗氧化后形成的氧化型物质是",options:["生育酚氧自由基","视黄酸","甲基丙二酸","尿 FIGLU"],answer:[0],explanation:"生育酚与自由基反应后形成生育酚氧自由基，随后可在维生素 C、谷胱甘肽和 NADPH 参与下还原。",source:"教材第94页"},
  {id:"deep-e-12",category:"维生素 E",type:"single",stem:"维生素 E 缺乏可使血小板聚集和凝血作用",options:["增强","减弱","完全停止","只在缺铁时增强"],answer:[0],explanation:"维生素 E 缺乏时血小板聚集和凝血增强，可能增加心肌梗死和脑卒中风险。",source:"教材第94页"},
  {id:"deep-e-13",category:"维生素 E",type:"single",stem:"维生素 E 抑制血小板聚集的机制与减少哪种物质释放有关",options:["血栓素 A2","胆红素","甲状腺素","尿酸"],answer:[0],explanation:"维生素 E 可抑制磷脂酶 A2 活性，减少血小板血栓素 A2 释放，从而抑制聚集。",source:"教材第94页"},
  {id:"deep-e-14",category:"维生素 E",type:"single",stem:"补充维生素 E 制剂一般建议每天不超过",options:["40 mg","100 mg","400 mg","4000 mg"],answer:[2],explanation:"教材建议补充维生素 E 制剂时每天不超过 400 mg。",source:"教材第95页"},
  {id:"deep-e-15",category:"维生素 E",type:"multiple",stem:"维生素 E 缺乏可能出现的表现包括",options:["视网膜退行性病变","溶血性贫血","肌无力","小脑共济失调"],answer:[0,1,2,3],explanation:"维生素 E 缺乏可导致视网膜、红细胞和神经肌肉系统受损。",source:"教材第95页"},
  {id:"deep-e-16",category:"维生素 E",type:"single",stem:"红细胞 H2O2 溶血试验中，溶血百分比超过多少提示维生素 E 缺乏",options:["5%","10%","20%","50%"],answer:[2],explanation:"维生素 E 正常时比值 <10%，偏低 10%-20%，缺乏时 >20%。",source:"教材第95页"},
  {id:"deep-e-17",category:"维生素 E",type:"single",stem:"人工合成 dl-α-生育酚的活性约相当于天然 d-α-生育酚的",options:["25%","50%","74%","100%"],answer:[2],explanation:"人工合成 dl-α-生育酚活性约为天然 d-α-生育酚的 74%。",source:"教材第95页"},
  {id:"deep-e-18",category:"维生素 E",type:"single",stem:"成人维生素 E 的 UL 是",options:["70 mg α-TE/d","140 mg α-TE/d","400 mg α-TE/d","700 mg α-TE/d"],answer:[3],explanation:"成人（包括孕妇、乳母）维生素 E UL 为 700 mg α-TE/d。",source:"教材第95页"},
  {id:"deep-e-19",category:"维生素 E",type:"single",stem:"每摄入 1 g 多不饱和脂肪酸，专家建议摄入维生素 E 约",options:["0.04 mg α-TE","0.4 mg α-TE","4 mg α-TE","40 mg α-TE"],answer:[1],explanation:"教材提到每摄入 1 g 多不饱和脂肪酸，应摄入约 0.4 mg α-TE。",source:"教材第96页"},

  {id:"deep-b1-08",category:"维生素 B1",type:"single",stem:"维生素 B1 主要在小肠的哪个部位吸收后被磷酸化",options:["空肠黏膜细胞","胃底细胞","回肠末端细胞","结肠细胞"],answer:[0],explanation:"B1 在小肠吸收，吸收后在空肠黏膜细胞内经磷酸化转变为焦磷酸酯。",source:"教材第96页"},
  {id:"deep-b1-09",category:"维生素 B1",type:"single",stem:"成人体内维生素 B1 约有多少以 TPP 形式存在",options:["10%","50%","80%","100%"],answer:[2],explanation:"体内 B1 约 80% 为 TPP，约 10% 为 TTP，其余为 TMP 等形式。",source:"教材第96页"},
  {id:"deep-b1-10",category:"维生素 B1",type:"single",stem:"维生素 B1 缺乏时，体内容易堆积的代谢物是",options:["丙酮酸和乳酸","尿酸和肌酐","甲基丙二酸和 FIGLU","胆红素和胆汁酸"],answer:[0],explanation:"B1 严重缺乏时 ATP 生成障碍，丙酮酸和乳酸在体内堆积。",source:"教材第97页"},
  {id:"deep-b1-11",category:"维生素 B1",type:"single",stem:"转酮醇反应对核酸合成的重要意义在于提供",options:["戊糖","胆盐","血红素铁","维生素 D"],answer:[0],explanation:"转酮醇作用是磷酸戊糖途径的重要反应，可提供核酸合成所需的戊糖。",source:"教材第97页"},
  {id:"deep-b1-12",category:"维生素 B1",type:"single",stem:"维生素 B1 缺乏可使乙酰胆碱分解加速，主要因为胆碱酯酶活性",options:["增强","降低","完全消失","只在肝脏增强"],answer:[0],explanation:"B1 是胆碱酯酶的抑制剂，缺乏时胆碱酯酶活性增强，使乙酰胆碱分解加速。",source:"教材第97页"},
  {id:"deep-b1-13",category:"维生素 B1",type:"single",stem:"成人维生素 B1 的 RNI 男性和女性分别为",options:["1.4 和 1.2 mg/d","1.2 和 1.4 mg/d","2.4 和 2.9 mg/d","0.5 和 0.6 mg/d"],answer:[0],explanation:"2013 版成人维生素 B1 RNI：男性 1.4 mg/d，女性 1.2 mg/d。",source:"教材第98页"},
  {id:"deep-b1-14",category:"维生素 B1",type:"single",stem:"维生素 B1 的需要量通常与哪项关系最密切",options:["总能量需要量","血清钙浓度","膳食碘含量","骨密度"],answer:[0],explanation:"B1 需要量与体内能量代谢密切相关，参考摄入量可按总能量需要推算。",source:"教材第98页"},
  {id:"deep-b1-15",category:"维生素 B1",type:"single",stem:"高温烹调时维生素 B1 的损失可达",options:["3%-4%","10%-15%","30%-40%","80%-90%"],answer:[2],explanation:"一般温度烹调损失不多，高温烹调时 B1 损失可达 30%-40%。",source:"教材第98页"},

  {id:"deep-b2-07",category:"维生素 B2",type:"single",stem:"维生素 B2 主要在胃肠道上部以何种转运方式吸收",options:["主动转运","被动滤过","吞噬作用","胆汁重吸收"],answer:[0],explanation:"B2 主要在胃肠道上部主动转运吸收，需要 Na+ 和 ATP。",source:"教材第98-99页"},
  {id:"deep-b2-08",category:"维生素 B2",type:"single",stem:"肝脏中的维生素 B2 可转变为作为辅酶的",options:["FMN 和 FAD","TPP 和 TTP","NAD 和 NADP","PLP 和 PMP"],answer:[0],explanation:"B2 在肝脏再转变为 FMN 和 FAD，发挥辅酶作用。",source:"教材第99页"},
  {id:"deep-b2-09",category:"维生素 B2",type:"single",stem:"成年人体内储存的维生素 B2 大致可维持多少周代谢需要",options:["2-6 天","2-6 周","2-6 月","2-6 年"],answer:[1],explanation:"成人体内维生素 B2 可维持机体约 2-6 周的代谢需要。",source:"教材第99页"},
  {id:"deep-b2-10",category:"维生素 B2",type:"single",stem:"视网膜、尿和乳汁中的维生素 B2 主要为",options:["游离型","结合型","酯化型","血红素型"],answer:[0],explanation:"视网膜、尿和奶中的 B2 主要为游离型；肝、肾和心脏中主要为结合型。",source:"教材第99页"},
  {id:"deep-b2-11",category:"维生素 B2",type:"single",stem:"FMN 和 FAD 参与代谢时，主要承担的功能是",options:["氧化还原反应中的辅酶作用","直接运输氧","形成骨盐","结合胆汁酸"],answer:[0],explanation:"FMN 和 FAD 参与多种酶系统的氧化还原反应与能量代谢。",source:"教材第99页"},
  {id:"deep-b2-12",category:"维生素 B2",type:"single",stem:"维生素 B2 参与色氨酸转变为烟酸时，主要以哪种形式参与",options:["FAD 和 FMN","TPP 和 TTP","RBP 和 TTR","DBP 和 IF"],answer:[0],explanation:"FAD 和 FMN 分别参与色氨酸转变为烟酸及维生素 B6 转变为磷酸吡哆醛。",source:"教材第99页"},
  {id:"deep-b2-13",category:"维生素 B2",type:"single",stem:"维生素 B2 缺乏的眼部表现可能是",options:["睑缘炎、畏光和流泪","暗适应延长","视紫红质完全缺失","毕脱氏斑"],answer:[0],explanation:"B2 缺乏可出现结膜充血、角膜周围血管增生、睑缘炎、畏光、视物模糊和流泪。",source:"教材第99-100页"},
  {id:"deep-b2-14",category:"维生素 B2",type:"single",stem:"维生素 B2 缺乏时皮肤常见表现是",options:["脂溢性皮炎","氟斑牙","反甲","黏液性水肿"],answer:[0],explanation:"B2 缺乏可在鼻唇沟、耳后、腋下等皮脂分泌旺盛部位出现脂溢性皮炎。",source:"教材第100页"},
  {id:"deep-b2-15",category:"维生素 B2",type:"single",stem:"维生素 B2 缺乏可能干扰哪种矿物质的吸收、储存和动员",options:["铁","碘","氟","铬"],answer:[0],explanation:"B2 缺乏可干扰铁的吸收、储存和动员，严重时可造成缺铁性贫血。",source:"教材第100页"},
  {id:"deep-b2-16",category:"维生素 B2",type:"single",stem:"尿中维生素 B2 与肌酐比值低于多少提示缺乏",options:["10","27","80","270"],answer:[1],explanation:"尿 B2/肌酐比值 <27 为缺乏，27-79 为不足，80-269 为正常，≥270 为充足。",source:"教材第100页"},
  {id:"deep-b2-17",category:"维生素 B2",type:"single",stem:"成人维生素 B2 的 RNI 男性和女性分别为",options:["1.4 和 1.2 mg/d","1.2 和 1.4 mg/d","2.4 和 2.9 mg/d","5.0 和 7.0 mg/d"],answer:[0],explanation:"成人 B2 RNI 男性为 1.4 mg/d，女性为 1.2 mg/d。",source:"教材第100页"},
  {id:"deep-b2-18",category:"维生素 B2",type:"multiple",stem:"维生素 B2 需要量增加的情况包括",options:["能量需要量增加","生长加速","创伤修复期","高原或寒冷环境"],answer:[0,1,2,3],explanation:"B2 需要量与能量代谢、蛋白质摄入和特殊环境或特殊作业有关。",source:"教材第100页"},
  {id:"deep-b2-19",category:"维生素 B2",type:"single",stem:"用捞饭而不是碗蒸米饭，维生素 B2 损失通常",options:["更多","更少","完全没有差异且不受水影响","只在生米中增加"],answer:[0],explanation:"教材指出碗蒸米饭比捞饭维生素 B2 损失少，捞饭会增加水溶性维生素损失。",source:"教材第100页"},

  {id:"deep-niacin-07",category:"烟酸",type:"single",stem:"膳食烟酸主要以哪两种辅酶形式存在",options:["NAD 和 NADP","FMN 和 FAD","TPP 和 TTP","PLP 和 PMP"],answer:[0],explanation:"膳食烟酸主要以辅酶 I（NAD）和辅酶 II（NADP）形式存在，经消化后吸收。",source:"教材第101页"},
  {id:"deep-niacin-08",category:"烟酸",type:"single",stem:"烟酸吸收后主要在哪个器官转化为 NAD 和 NADP",options:["肝脏","肺脏","骨髓","甲状腺"],answer:[0],explanation:"吸收后的烟酸经门静脉进入肝脏，在肝内转化为 NAD 和 NADP。",source:"教材第101页"},
  {id:"deep-niacin-09",category:"烟酸",type:"single",stem:"色氨酸转化为烟酸需要哪组维生素参与",options:["B1、B2 和 B6","A、D 和 E","C、D 和 B12","K、叶酸和 C"],answer:[0],explanation:"色氨酸转化为烟酸需要维生素 B1、B2 和 B6 参与。",source:"教材第101页"},
  {id:"deep-niacin-10",category:"烟酸",type:"single",stem:"烟酸在细胞生物氧化中主要发挥什么作用",options:["可逆传递氢","直接结合钙离子","形成骨胶原","催化脂肪乳化"],answer:[0],explanation:"NAD 和 NADP 中的烟酰胺部分具有可逆加氢和脱氢特性，承担氢传递。",source:"教材第101页"},
  {id:"deep-niacin-11",category:"烟酸",type:"single",stem:"烟酸缺乏的皮炎通常具有哪种分布特点",options:["暴露部位对称性皮炎","只发生于脚趾","只发生在头皮且不对称","只发生于口腔内部"],answer:[0],explanation:"烟酸缺乏皮炎多发生于面颊、手背、足背等暴露部位，呈对称性日晒斑样改变。",source:"教材第101页"},
  {id:"deep-niacin-12",category:"烟酸",type:"single",stem:"烟酸缺乏的消化道表现主要是",options:["食欲减退、消化不良和腹泻","便秘和胃酸过多","黄疸和肝硬化","肾结石和多尿"],answer:[0],explanation:"烟酸缺乏可出现食欲减退、消化不良、腹泻，并可伴口腔黏膜和舌部损害。",source:"教材第101页"},
  {id:"deep-niacin-13",category:"烟酸",type:"single",stem:"口服 50 mg 烟酸后，4 小时尿排出低于多少提示缺乏",options:["0.2 mg","2.0 mg","3.0 mg","5.0 mg"],answer:[1],explanation:"烟酸尿负荷试验中，4 小时尿排出 <2.0 mg 为缺乏，2.0-2.9 mg 为不足。",source:"教材第102页"},
  {id:"deep-niacin-14",category:"烟酸",type:"single",stem:"N-甲基烟酰胺与肌酐比值达到多少以上可认为烟酸充足",options:["0.5","1.6","4.3","10"],answer:[2],explanation:"该比值 <0.5 为缺乏，0.5-1.59 为不足，1.6-4.2 为正常，≥4.3 为充足。",source:"教材第102页"},
  {id:"deep-niacin-15",category:"烟酸",type:"single",stem:"成年女性烟酸的 RNI 是",options:["12 mg NE/d","15 mg NE/d","35 mg NE/d","60 mg NE/d"],answer:[0],explanation:"成年女性烟酸 RNI 为 12 mg NE/d，男性为 15 mg NE/d。",source:"教材第102页"},
  {id:"deep-niacin-16",category:"烟酸",type:"multiple",stem:"烟酸含量较丰富的食物包括",options:["肝和肾","瘦禽肉和鱼","全谷和坚果","乳和蛋中的色氨酸"],answer:[0,1,2,3],explanation:"肝、肾、瘦禽肉、鱼、全谷和坚果含烟酸丰富；乳和蛋虽烟酸低但色氨酸较高。",source:"教材第102页"},

  {id:"deep-pan-01",category:"泛酸",type:"single",stem:"泛酸在红细胞内主要以哪种形式存在",options:["辅酶A","游离泛酸","NADP","磷酸吡哆醛"],answer:[0],explanation:"泛酸进入红细胞后主要以辅酶A形式存在，而血浆中主要是游离型泛酸。",source:"教材第102-103页"},
  {id:"deep-pan-02",category:"泛酸",type:"single",stem:"泛酸进入细胞时主要依赖的转运体是",options:["钠依赖性多种维生素转运体 SMVT","DMT-1","RBP","内因子受体"],answer:[0],explanation:"泛酸进入细胞依靠钠依赖性多种维生素转运体 SMVT。",source:"教材第103页"},
  {id:"deep-pan-03",category:"泛酸",type:"single",stem:"泛酸在低浓度时的吸收方式主要是",options:["主动转运","简单扩散","吞噬作用","胆汁重吸收"],answer:[0],explanation:"低浓度泛酸主要通过主动转运吸收，高浓度时则以简单扩散为主。",source:"教材第102页"},
  {id:"deep-pan-04",category:"泛酸",type:"single",stem:"泛酸摄入量中约有多少可被完全氧化为二氧化碳并经肺排出",options:["1%","5%","15%","50%"],answer:[2],explanation:"部分泛酸可完全氧化为二氧化碳，经肺排出，约相当于每日摄入量的15%。",source:"教材第103页"},
  {id:"deep-pan-05",category:"泛酸",type:"multiple",stem:"泛酸参与的生理过程包括",options:["辅酶A参与三大营养物质代谢","乙酰胆碱合成","血红素合成","酰基载体蛋白参与脂肪酸合成"],answer:[0,1,2,3],explanation:"泛酸构成辅酶A和酰基载体蛋白，因而参与能量代谢、乙酰胆碱、血红素和脂肪酸合成。",source:"教材第103页"},
  {id:"deep-pan-06",category:"泛酸",type:"single",stem:"泛酸缺乏时，辅酶A和酰基载体蛋白的变化通常是",options:["辅酶A明显下降而酰基载体蛋白变化不明显","辅酶A升高而酰基载体蛋白下降","二者均完全不变","二者均明显升高"],answer:[0],explanation:"机体可利用辅酶A合成酰基载体蛋白，因此泛酸缺乏时辅酶A明显下降，而酰基载体蛋白变化不明显。",source:"教材第103页"},
  {id:"deep-pan-07",category:"泛酸",type:"single",stem:"正常膳食成年人尿中泛酸排出量通常约为",options:["0.02-0.07 mg/d","2-7 mg/d","20-70 mg/d","200-700 mg/d"],answer:[1],explanation:"正常膳食成年人尿中泛酸排出量约为2-7 mg/d，且与摄入水平呈正相关。",source:"教材第103页"},
  {id:"deep-pan-08",category:"泛酸",type:"single",stem:"泛酸成人适宜摄入量 AI、孕妇 AI 和乳母 AI 分别为",options:["5.0、6.0、7.0 mg/d","1.4、2.4、1.4 mg/d","12、15、20 mg/d","40、50、60 μg/d"],answer:[0],explanation:"教材给出的泛酸 AI 为成人5.0 mg/d、孕妇6.0 mg/d、乳母7.0 mg/d。",source:"教材第103页"},
  {id:"deep-pan-09",category:"泛酸",type:"multiple",stem:"膳食中泛酸含量较丰富的食物包括",options:["动物心、肝、肾","蘑菇","鸡蛋和坚果","精制糖和白酒"],answer:[0,1,2],explanation:"肉类内脏、蘑菇、鸡蛋和坚果是泛酸较丰富的来源，精制糖和白酒不是良好来源。",source:"教材第103页"},

  {id:"deep-b6-01",category:"维生素 B6",type:"multiple",stem:"天然存在并具有维生素 B6 活性的形式包括",options:["吡哆醇","吡哆醛","吡哆胺","叶酸"],answer:[0,1,2],explanation:"维生素B6包括吡哆醇、吡哆醛和吡哆胺三种天然形式，叶酸属于另一种维生素。",source:"教材第103-104页"},
  {id:"deep-b6-02",category:"维生素 B6",type:"single",stem:"维生素 B6 主要在小肠的哪个部位以被动扩散方式吸收",options:["空肠","胃底","回肠末端","结肠"],answer:[0],explanation:"维生素B6主要在空肠以被动扩散形式吸收。",source:"教材第104页"},
  {id:"deep-b6-03",category:"维生素 B6",type:"single",stem:"人体储存的维生素 B6 主要位于肌肉组织，约占储存量的",options:["5%-10%","25%-30%","50%-60%","75%-80%"],answer:[3],explanation:"维生素B6主要储存于肌肉组织，约占储存量的75%-80%。",source:"教材第104页"},
  {id:"deep-b6-04",category:"维生素 B6",type:"multiple",stem:"磷酸吡哆醛 PLP 参与的反应或功能包括",options:["氨基酸转氨、脱氨和脱羧","色氨酸转化及烟酸合成","血红素合成","部分神经递质合成"],answer:[0,1,2,3],explanation:"PLP是多种酶的辅酶，参与氨基酸、色氨酸、血红素及神经递质等代谢。",source:"教材第104页"},
  {id:"deep-b6-05",category:"维生素 B6",type:"single",stem:"维生素 B6 促进烟酸合成的主要底物转化是",options:["色氨酸转化为烟酸","胆固醇转化为胆酸","葡萄糖转化为糖原","铁转化为血红素"],answer:[0],explanation:"维生素B6参与色氨酸转化为烟酸的代谢过程。",source:"教材第104页"},
  {id:"deep-b6-06",category:"维生素 B6",type:"single",stem:"维生素 B6 参与血红素合成时，所涉及的两种原料是",options:["琥珀酰辅酶A和甘氨酸","乙酰辅酶A和胆碱","丙酮酸和乳酸","甲硫氨酸和叶酸"],answer:[0],explanation:"PLP参与琥珀酰辅酶A和甘氨酸合成血红素的过程。",source:"教材第104页"},
  {id:"deep-b6-07",category:"维生素 B6",type:"multiple",stem:"维生素 B6 缺乏可能造成的改变包括",options:["脂溢性皮炎、口炎和舌炎","体液和细胞免疫功能受损","高同型半胱氨酸血症","低色素小细胞性贫血"],answer:[0,1,2,3],explanation:"B6缺乏可影响皮肤黏膜、免疫、同型半胱氨酸代谢和造血。",source:"教材第104页"},
  {id:"deep-b6-08",category:"维生素 B6",type:"single",stem:"异烟肼诱发维生素 B6 缺乏的直接原因是",options:["与 PLP 形成复合物","促进 B6 从尿中重吸收","抑制内因子分泌","破坏肠道胆盐"],answer:[0],explanation:"异烟肼可与PLP形成复合物，使有活性的维生素B6减少。",source:"教材第104页"},
  {id:"deep-b6-09",category:"维生素 B6",type:"single",stem:"婴幼儿维生素 B6 缺乏较典型的表现是",options:["肌肉抽搐和癫痫样惊厥","鸡胸和肋骨串珠","牙龈出血和坏血病","甲状腺肿大"],answer:[0],explanation:"婴幼儿B6缺乏可出现烦躁、肌肉抽搐、癫痫样惊厥、呕吐和体重下降。",source:"教材第104-105页"},
  {id:"deep-b6-10",category:"维生素 B6",type:"single",stem:"短期每日服用约 500 mg 维生素 B6 可能引起",options:["神经毒性和光敏感性反应","严重低钠血症","佝偻病","牙龈增生"],answer:[0],explanation:"食物来源B6通常安全，但大剂量补充可出现神经毒性和光敏感性反应。",source:"教材第105页"},
  {id:"deep-b6-11",category:"维生素 B6",type:"single",stem:"色氨酸负荷试验评价维生素 B6 时，主要测定尿中的",options:["黄尿酸","FIGLU","甲基丙二酸","N-甲基烟酰胺"],answer:[0],explanation:"B6缺乏时色氨酸代谢异常，尿中黄尿酸增加，可用于色氨酸负荷试验评价。",source:"教材第105页"},
  {id:"deep-b6-12",category:"维生素 B6",type:"single",stem:"色氨酸负荷试验中，维生素 B6 营养状况良好时黄尿酸指数通常为",options:["0-0.15","0.5-1.5","1.6-4.2","大于12"],answer:[0],explanation:"黄尿酸指数0-0.15提示B6营养状况良好，缺乏时可大于1.2。",source:"教材第105页"},
  {id:"deep-b6-13",category:"维生素 B6",type:"single",stem:"血浆 PLP 评价维生素 B6 时需要注意其达到新平衡大约需要",options:["数小时","2天","10天","半年"],answer:[2],explanation:"血浆PLP反映组织储存，但反应较慢，约需10天才能达到新的平衡。",source:"教材第105页"},
  {id:"deep-b6-14",category:"维生素 B6",type:"single",stem:"维生素 B6 的最终代谢产物 4-吡哆酸主要反映",options:["近期膳食 B6 摄入水平","肝脏长期铁储备","近期维生素 C 摄入","骨骼钙化水平"],answer:[0],explanation:"尿中4-吡哆酸是B6的最终代谢产物，可反映近期膳食B6摄入量。",source:"教材第105页"},
  {id:"deep-b6-15",category:"维生素 B6",type:"single",stem:"妊娠期维生素 B6 的 RNI 是",options:["1.4 mg/d","2.4 mg/d","5.0 mg/d","12 mg/d"],answer:[1],explanation:"教材给出的成人B6 RNI为1.4 mg/d，妊娠期为2.4 mg/d，哺乳期为1.4 mg/d。",source:"教材第105页"},

  {id:"deep-biotin-01",category:"生物素",type:"multiple",stem:"生物素的别名包括",options:["维生素 H","维生素 B7","辅酶 R","抗坏血酸"],answer:[0,1,2],explanation:"生物素又称维生素H、维生素B7和辅酶R，抗坏血酸是维生素C。",source:"教材第105页"},
  {id:"deep-biotin-02",category:"生物素",type:"single",stem:"生物素吸收的主要部位是",options:["小肠近端","胃底","回肠末端","直肠"],answer:[0],explanation:"生物素主要在小肠近端吸收，结肠也可吸收一部分。",source:"教材第105页"},
  {id:"deep-biotin-03",category:"生物素",type:"single",stem:"高浓度生物素在肠道中主要通过何种方式吸收",options:["简单扩散","主动转运","受体介导吞噬","胆汁重吸收"],answer:[0],explanation:"低浓度生物素主要主动转运，高浓度时主要以简单扩散吸收。",source:"教材第105页"},
  {id:"deep-biotin-04",category:"生物素",type:"single",stem:"加热蛋清可以改善生物素利用，主要是因为加热会破坏",options:["抗生物素蛋白","胃蛋白酶","内因子","乳糖酶"],answer:[0],explanation:"生蛋清中的抗生物素蛋白能结合生物素，加热后该蛋白被破坏，生物素可重新利用。",source:"教材第106页"},
  {id:"deep-biotin-05",category:"生物素",type:"single",stem:"吸收后的生物素主要运送至哪些器官储存",options:["肝和肾","肺和脾","骨和牙","胃和胰腺"],answer:[0],explanation:"生物素经门静脉循环后主要运送至肝、肾储存。",source:"教材第106页"},
  {id:"deep-biotin-06",category:"生物素",type:"multiple",stem:"生物素作为羧化酶辅酶参与的代谢包括",options:["丙酮酸羧化","丙酰辅酶A羧化","乙酰辅酶A羧化","甲基巴豆酰辅酶A羧化"],answer:[0,1,2,3],explanation:"生物素是多种羧化酶辅酶，参与糖、脂肪和氨基酸代谢中的羧化反应。",source:"教材第106页"},
  {id:"deep-biotin-07",category:"生物素",type:"single",stem:"丙酰辅酶 A 羧化酶催化生成的产物是",options:["甲基丙二酰辅酶A","乙酰辅酶A","草酰乙酸","乳酸"],answer:[0],explanation:"生物素参与丙酰辅酶A羧化，生成甲基丙二酰辅酶A。",source:"教材第106页"},
  {id:"deep-biotin-08",category:"生物素",type:"single",stem:"乙酰辅酶 A 羧化酶中的生物素作用与哪项关系最直接",options:["脂肪酸合成","胆汁酸重吸收","血红蛋白运输氧","视紫红质合成"],answer:[0],explanation:"乙酰辅酶A羧化酶参与脂肪酸合成，生物素是该羧化酶的辅酶。",source:"教材第106页"},
  {id:"deep-biotin-09",category:"生物素",type:"single",stem:"全血生物素含量低于多少可认为存在生物素缺乏",options:["10 ng/L","100 ng/L","200 ng/L","320 ng/L"],answer:[1],explanation:"正常成人全血生物素约260 ng/L，低于100 ng/L可认为缺乏。",source:"教材第106页"},
  {id:"deep-biotin-10",category:"生物素",type:"multiple",stem:"生物素缺乏可能出现的表现包括",options:["口周皮炎和结膜炎","脱毛和头发颜色变浅","皮肤干燥、麻木和疲劳","共济失调"],answer:[0,1,2,3],explanation:"生物素缺乏可累及皮肤、毛发、神经和精神状态，严重时出现共济失调。",source:"教材第106页"},
  {id:"deep-biotin-11",category:"生物素",type:"single",stem:"生物素缺乏时，尿中 3-羟基异戊酸通常会",options:["增加","减少至零","完全不变","转化为 FIGLU"],answer:[0],explanation:"生物素缺乏时相关羧化反应受阻，尿中3-羟基异戊酸排出量增加。",source:"教材第106页"},
  {id:"deep-biotin-12",category:"生物素",type:"single",stem:"成人生物素的适宜摄入量 AI 是",options:["4 μg/d","40 μg/d","400 μg/d","4 mg/d"],answer:[1],explanation:"2013版膳食营养素参考摄入量中成人生物素AI为40 μg/d。",source:"教材第106页"},

  {id:"deep-folate-01",category:"叶酸",type:"multiple",stem:"叶酸分子由哪些部分组成",options:["蝶啶","对氨基苯甲酸","谷氨酸","钴元素"],answer:[0,1,2],explanation:"叶酸即蝶酰谷氨酸，由蝶啶、对氨基苯甲酸和谷氨酸结合而成，不含钴元素。",source:"教材第107页"},
  {id:"deep-folate-02",category:"叶酸",type:"single",stem:"叶酸在何种环境中相对耐热",options:["中性和碱性溶液","pH低于4的酸性溶液","强酸溶液","酸性且超过100°C"],answer:[0],explanation:"叶酸在酸性溶液中不稳定，而在中性和碱性溶液中相对耐热。",source:"教材第107页"},
  {id:"deep-folate-03",category:"叶酸",type:"single",stem:"膳食多谷氨酸叶酸被小肠吸收前需要先转化为",options:["单谷氨酸叶酸","甲基丙二酸","N-甲基烟酰胺","甲基钴胺素"],answer:[0],explanation:"膳食叶酸多与多个谷氨酸结合，需水解为单谷氨酸叶酸后才能被吸收。",source:"教材第107页"},
  {id:"deep-folate-04",category:"叶酸",type:"single",stem:"叶酸肠道主动转运的最适 pH 大约为",options:["1.0-2.0","3.0-4.0","5.0-6.0","8.0-9.0"],answer:[2],explanation:"载体介导的叶酸主动转运受pH影响，最适pH约为5.0-6.0。",source:"教材第107页"},
  {id:"deep-folate-05",category:"叶酸",type:"single",stem:"下列食物中叶酸生物利用率相对较高的是",options:["豆类","荞麦","精制白糖","动物油"],answer:[0],explanation:"教材举例显示豆类叶酸生物利用率可达96%，明显高于荞麦等食物。",source:"教材第107页"},
  {id:"deep-folate-06",category:"叶酸",type:"single",stem:"正常成人体内叶酸储存量约为多少，约一半位于肝脏",options:["0.05-0.1 mg","0.5-1 mg","5-10 mg","50-100 mg"],answer:[2],explanation:"成人体内叶酸储存量约5-10 mg，其中约50%储存于肝脏。",source:"教材第107页"},
  {id:"deep-folate-07",category:"叶酸",type:"single",stem:"血浆叶酸主要以哪种形式存在",options:["5-甲基四氢叶酸","叶酸多谷氨酸","FIGLU","甲基丙二酸"],answer:[0],explanation:"血浆中的叶酸大多以5-甲基四氢叶酸形式存在，进入细胞后重新成为多谷氨酸型。",source:"教材第107页"},
  {id:"deep-folate-08",category:"叶酸",type:"single",stem:"叶酸在体内发挥一碳单位载体作用的主要活性形式是",options:["四氢叶酸","叶酸多谷氨酸原型","叶酸氧化型","对氨基苯甲酸"],answer:[0],explanation:"天然叶酸可还原为二氢叶酸和四氢叶酸，主要是四氢叶酸具有生理活性。",source:"教材第107页"},
  {id:"deep-folate-09",category:"叶酸",type:"multiple",stem:"四氢叶酸携带的一碳基团包括",options:["甲酰基","亚甲基","甲基","磷酸基"],answer:[0,1,2],explanation:"叶酸携带甲酰基、亚甲基和甲基等一碳基团参与多种代谢，磷酸基不是此处所指的一碳单位。",source:"教材第107页"},
  {id:"deep-folate-10",category:"叶酸",type:"multiple",stem:"叶酸参与的合成或代谢过程包括",options:["嘌呤和嘧啶核苷酸合成","细胞分裂和增殖","二碳与三碳氨基酸相互转化","某些甲基化反应"],answer:[0,1,2,3],explanation:"叶酸通过携带一碳单位参与核苷酸合成、细胞增殖、氨基酸转化和甲基化反应。",source:"教材第107页"},
  {id:"deep-folate-11",category:"叶酸",type:"single",stem:"叶酸缺乏所致贫血的典型类型是",options:["巨幼红细胞贫血","小细胞低色素性贫血","再生障碍性贫血","溶血性贫血"],answer:[0],explanation:"叶酸缺乏使幼红细胞DNA合成和分裂受阻，形成巨幼红细胞贫血。",source:"教材第107页"},
  {id:"deep-folate-12",category:"叶酸",type:"multiple",stem:"孕早期叶酸缺乏可能导致胎儿",options:["脊柱裂","无脑畸形","宫内发育迟缓","神经管畸形风险增加"],answer:[0,1,2,3],explanation:"孕早期叶酸缺乏与神经管畸形以及胎儿生长发育不良有关。",source:"教材第108页"},
  {id:"deep-folate-13",category:"叶酸",type:"single",stem:"叶酸缺乏时血浆同型半胱氨酸通常会",options:["升高","降低至不可测","完全不变","转化为尿酸"],answer:[0],explanation:"叶酸缺乏阻碍同型半胱氨酸向胱氨酸的转化，可形成高同型半胱氨酸血症。",source:"教材第108页"},
  {id:"deep-folate-14",category:"叶酸",type:"multiple",stem:"大剂量服用叶酸可能造成的影响包括",options:["影响锌吸收","掩盖维生素 B12 缺乏表现","干扰抗惊厥药物作用","增加胎儿发育迟缓风险"],answer:[0,1,2,3],explanation:"教材提示大剂量叶酸可能影响锌吸收、掩盖B12缺乏、干扰抗惊厥药物并影响胎儿发育。",source:"教材第108页"},
  {id:"deep-folate-15",category:"叶酸",type:"single",stem:"血清叶酸和红细胞叶酸分别主要反映",options:["近期摄入和长期组织储存","长期储存和近期摄入","铁储存和锌储存","肝功能和肾功能"],answer:[0],explanation:"血清叶酸反映近期膳食摄入，红细胞叶酸反映组织细胞储存和长期营养状况。",source:"教材第108页"},
  {id:"deep-folate-16",category:"叶酸",type:"single",stem:"血清总叶酸低于多少可判断为叶酸缺乏",options:["1 ng/ml","3 ng/ml","6 ng/ml","16 ng/ml"],answer:[1],explanation:"血清总叶酸<3 ng/ml为缺乏，3-6 ng/ml为不足，>6 ng/ml为正常。",source:"教材第108页"},
  {id:"deep-folate-17",category:"叶酸",type:"single",stem:"红细胞叶酸低于多少提示叶酸缺乏",options:["40 ng/ml","140 ng/ml","160 ng/ml","400 ng/ml"],answer:[1],explanation:"红细胞叶酸<140 ng/ml为缺乏，140-160 ng/ml为不足，>160 ng/ml为正常。",source:"教材第108页"},
  {id:"deep-folate-18",category:"叶酸",type:"multiple",stem:"关于叶酸摄入量和食物特点，正确的是",options:["成人 RNI 为 400 μg DFE/d","孕妇 RNI 为 600 μg DFE/d","叶酸 UL 为 1000 μg DFE/d","天然食物叶酸烹调可损失 50%-90%"],answer:[0,1,2,3],explanation:"这些数值和烹调损失范围均见教材，叶酸当量DFE用于统一表达摄入量。",source:"教材第108页"},

  {id:"deep-b12-01",category:"维生素 B12",type:"single",stem:"维生素 B12 是唯一含有哪种金属元素的维生素",options:["钴","铁","锌","铜"],answer:[0],explanation:"维生素B12分子含钴元素，因此又称钴胺素，是唯一含金属元素的维生素。",source:"教材第109页"},
  {id:"deep-b12-02",category:"维生素 B12",type:"single",stem:"维生素 B12 在何种环境中相对稳定",options:["弱酸性条件","强酸条件","强碱条件","强氧化剂环境"],answer:[0],explanation:"B12在弱酸条件下稳定，强酸、强碱、日光和氧化还原剂均可使其破坏。",source:"教材第109页"},
  {id:"deep-b12-03",category:"维生素 B12",type:"single",stem:"维生素 B12 从食物蛋白质中释放并能在小肠吸收，必须依赖",options:["胃黏膜分泌的内因子","胆汁酸","RBP","DMT-1"],answer:[0],explanation:"B12需从食物蛋白中释放后与胃黏膜分泌的内因子结合，形成复合物才能被吸收。",source:"教材第109页"},
  {id:"deep-b12-04",category:"维生素 B12",type:"single",stem:"维生素 B12-内因子复合物主要在何处被吸收",options:["回肠黏膜","胃底黏膜","空肠起始部","结肠"],answer:[0],explanation:"B12-内因子复合物附着于回肠黏膜细胞受体，在肠道酶作用下释放并吸收B12。",source:"教材第109页"},
  {id:"deep-b12-05",category:"维生素 B12",type:"single",stem:"血液中维生素 B12 的主要转运蛋白是",options:["TC II","白蛋白","运铁蛋白","甲状腺素结合球蛋白"],answer:[0],explanation:"TC II是B12的主要转运蛋白，将B12运送至肝、肾和骨髓等组织。",source:"教材第109页"},
  {id:"deep-b12-06",category:"维生素 B12",type:"multiple",stem:"会影响维生素 B12 吸收的情况包括",options:["年龄增长","维生素 B6 或铁缺乏","甲状腺功能减退","妊娠期"],answer:[0,1,2],explanation:"年龄增长、B6或铁缺乏及甲状腺功能减退可使B12吸收率下降；妊娠期吸收率会升高。",source:"教材第109页"},
  {id:"deep-b12-07",category:"维生素 B12",type:"single",stem:"人体内维生素 B12 的储存量和主要储存器官是",options:["2-3 mg，肝脏","20-30 mg，肌肉","0.02-0.03 mg，肾脏","200-300 mg，骨髓"],answer:[0],explanation:"人体B12储存量约2-3 mg，主要储存在肝脏。",source:"教材第109页"},
  {id:"deep-b12-08",category:"维生素 B12",type:"single",stem:"维生素 B12 的肝肠循环主要有助于",options:["重复利用和维持体内稳定","促进钙沉积于骨","增加铁排出","将叶酸转成维生素 C"],answer:[0],explanation:"肝脏随胆汁排出的B12大部分可重新吸收，肝肠循环有助于重复利用和维持稳定。",source:"教材第109页"},
  {id:"deep-b12-09",category:"维生素 B12",type:"multiple",stem:"维生素 B12 在体内发挥作用的辅酶形式包括",options:["甲基钴胺素","5-脱氧腺苷钴胺素","NADP","FMN"],answer:[0,1],explanation:"B12以甲基钴胺素和5-脱氧腺苷钴胺素两种辅酶形式参与代谢。",source:"教材第109页"},
  {id:"deep-b12-10",category:"维生素 B12",type:"single",stem:"维生素 B12 参与同型半胱氨酸转变为蛋氨酸时，是哪种酶的辅酶",options:["蛋氨酸合成酶","丙酮酸羧化酶","谷胱甘肽还原酶","乳酸脱氢酶"],answer:[0],explanation:"甲基B12是蛋氨酸合成酶的辅酶，参与同型半胱氨酸甲基化为蛋氨酸。",source:"教材第109-110页"},
  {id:"deep-b12-11",category:"维生素 B12",type:"single",stem:"维生素 B12 缺乏时，5-甲基四氢叶酸上的甲基不能转移会导致",options:["四氢叶酸不能重新利用","维生素 C 合成增加","铁吸收完全停止","胆汁酸过量"],answer:[0],explanation:"B12缺乏导致甲基转移受阻，游离四氢叶酸减少并影响核酸合成。",source:"教材第110页"},
  {id:"deep-b12-12",category:"维生素 B12",type:"single",stem:"维生素 B12 缺乏时甲基丙二酰辅酶 A 的堆积主要影响",options:["脂肪酸正常合成和髓鞘更新","胆红素结合","视紫红质再生","钙磷沉积"],answer:[0],explanation:"甲基丙二酰辅酶A堆积会影响脂肪酸合成，进而造成髓鞘变性和脱髓鞘。",source:"教材第110页"},
  {id:"deep-b12-13",category:"维生素 B12",type:"multiple",stem:"维生素 B12 缺乏的高风险人群包括",options:["严格素食者","素食母亲的婴幼儿","老年人","回肠疾病患者"],answer:[0,1,2,3],explanation:"B12主要来自动物性食物，摄入不足、年龄增长和回肠疾病均会增加缺乏风险。",source:"教材第110页"},
  {id:"deep-b12-14",category:"维生素 B12",type:"multiple",stem:"维生素 B12 缺乏可能出现的表现包括",options:["巨幼红细胞贫血","进行性神经脱髓鞘","高同型半胱氨酸血症","记忆力下降和四肢震颤"],answer:[0,1,2,3],explanation:"B12缺乏同时影响核酸代谢、髓鞘更新和同型半胱氨酸代谢。",source:"教材第110页"},
  {id:"deep-b12-15",category:"维生素 B12",type:"single",stem:"血清维生素 B12 浓度通常反映的是",options:["体内储存水平","当天膳食摄入量","肠道菌群数量","血红蛋白合成速率"],answer:[0],explanation:"血清B12浓度是反映体内储存的指标之一。",source:"教材第110页"},
  {id:"deep-b12-16",category:"维生素 B12",type:"single",stem:"血清维生素 B12 的正常浓度范围通常为",options:["12-18 pmol/L","120-180 pmol/L","1200-1800 pmol/L","1.2-1.8 pmol/L"],answer:[1],explanation:"教材给出的血清B12正常范围为120-180 pmol/L。",source:"教材第110页"},
  {id:"deep-b12-17",category:"维生素 B12",type:"multiple",stem:"维生素 B12 缺乏时，血清中可能升高的代谢指标包括",options:["同型半胱氨酸","甲基丙二酸","血清铁蛋白必然升高","尿 FIGLU 必然下降"],answer:[0,1],explanation:"B12缺乏时同型半胱氨酸和甲基丙二酸均可升高，后两项不是B12缺乏的必然结果。",source:"教材第110页"},
  {id:"deep-b12-18",category:"维生素 B12",type:"single",stem:"乳母维生素 B12 的 RNI 是",options:["2.4 μg/d","2.9 μg/d","3.2 μg/d","32 μg/d"],answer:[2],explanation:"2013版成人B12 RNI为2.4 μg/d，孕妇2.9 μg/d，乳母3.2 μg/d。",source:"教材第110页"},

  {id:"deep-c-01",category:"维生素 C",type:"single",stem:"天然维生素 C 中具有生物活性的构型是",options:["L型","D型","仅脱氢型","仅氧化型"],answer:[0],explanation:"天然维生素C有L型和D型，只有L型具有生物活性。",source:"教材第111页"},
  {id:"deep-c-02",category:"维生素 C",type:"multiple",stem:"维生素 C 的理化特点包括",options:["易溶于水","是强还原剂","水溶液易被空气氧化","不溶于脂溶性溶剂"],answer:[0,1,2,3],explanation:"维生素C水溶性强、还原性强，水溶液易受空气等因素氧化，且不溶于脂溶性溶剂。",source:"教材第111页"},
  {id:"deep-c-03",category:"维生素 C",type:"single",stem:"食物中的还原型和氧化型维生素 C 的关系是",options:["可相互转变且均有生物活性","只能由还原型转成氧化型且氧化型无活性","只能由氧化型转成还原型","二者均无活性"],answer:[0],explanation:"食物中还原型和脱氢型维生素C可相互转变，二者均具有生物活性。",source:"教材第111页"},
  {id:"deep-c-04",category:"维生素 C",type:"single",stem:"正常人血浆中还原型与氧化型维生素 C 的比例约为",options:["1:15","15:1","1:1","60:1"],answer:[1],explanation:"血浆维生素C主要为还原型，还原型与氧化型比例约为15:1。",source:"教材第111页"},
  {id:"deep-c-05",category:"维生素 C",type:"single",stem:"维生素 C 主要在小肠上段以何种方式吸收",options:["主动转运","简单扩散","内因子介导转运","胆汁酸介导转运"],answer:[0],explanation:"维生素C主要通过主动转运由小肠上段吸收入血。",source:"教材第111页"},
  {id:"deep-c-06",category:"维生素 C",type:"single",stem:"维生素 C 吸收前被氧化为脱氢型后，进入细胞内会发生",options:["迅速还原为维生素 C","转化为维生素 B12","直接排出体外","形成胆汁酸"],answer:[0],explanation:"脱氢型抗坏血酸进入黏膜或组织细胞后，在还原酶作用下很快还原为维生素C。",source:"教材第111页"},
  {id:"deep-c-07",category:"维生素 C",type:"single",stem:"胃酸缺乏对维生素 C 吸收的影响是",options:["使吸收减少","使吸收增加","完全没有影响","只增加肾脏排泄而不影响吸收"],answer:[0],explanation:"胃酸缺乏会减少维生素C的吸收。",source:"教材第111页"},
  {id:"deep-c-08",category:"维生素 C",type:"multiple",stem:"人类不能在体内由葡萄糖合成维生素 C，仍需膳食供给的动物包括",options:["人","猴","豚鼠","牛"],answer:[0,1,2],explanation:"人、猴和豚鼠体内不能合成维生素C；许多其他动物可以利用葡萄糖合成。",source:"教材第111页"},
  {id:"deep-c-09",category:"维生素 C",type:"single",stem:"正常成人体内可储存的维生素 C 约为",options:["12-20 mg","120-200 mg","1.2-2.0 g","12-20 g"],answer:[2],explanation:"正常成人体内可储存维生素C约1.2-2.0 g，最高约3.0 g。",source:"教材第111页"},
  {id:"deep-c-10",category:"维生素 C",type:"single",stem:"人体内维生素 C 含量最高的组织是",options:["垂体","血浆","唾液","脂肪组织"],answer:[0],explanation:"维生素C在垂体含量最高，其次为肾上腺、肾脏、脾和肝。",source:"教材第111页"},
  {id:"deep-c-11",category:"维生素 C",type:"single",stem:"维生素 C 的主要排泄途径是",options:["尿液","呼出气体","胆汁为主","皮脂"],answer:[0],explanation:"维生素C主要随尿排出，其次可随汗液和粪便排出。",source:"教材第111页"},
  {id:"deep-c-12",category:"维生素 C",type:"multiple",stem:"维生素 C 的抗氧化作用包括",options:["使氧化型谷胱甘肽还原","还原超氧化物等活性氧","清除羟基自由基","逐级供给电子形成脱氢抗坏血酸"],answer:[0,1,2,3],explanation:"维生素C可还原谷胱甘肽和多种活性氧，并通过供给电子发挥自由基清除作用。",source:"教材第112页"},
  {id:"deep-c-13",category:"维生素 C",type:"single",stem:"维生素 C 缺乏导致创伤愈合延缓，主要因为影响了",options:["胶原蛋白中脯氨酸和赖氨酸的羟基化","血红蛋白四价铁还原","胆汁酸乳化","视紫红质合成"],answer:[0],explanation:"维生素C是胶原蛋白羟脯氨酸和羟赖氨酸形成所需的辅助因子。",source:"教材第112页"},
  {id:"deep-c-14",category:"维生素 C",type:"multiple",stem:"维生素 C 有助于改善哪些营养素的利用",options:["铁","钙","叶酸","维生素 B12"],answer:[0,1,2],explanation:"维生素C促进三价铁还原、钙吸收并将叶酸还原为活性四氢叶酸，教材未将B12列为此作用。",source:"教材第112页"},
  {id:"deep-c-15",category:"维生素 C",type:"single",stem:"维生素 C 参与胆固醇转变为胆酸、皮质激素和性激素时，主要参与的是",options:["类固醇羟基化反应","嘌呤合成","血红素脱铁","脂肪酸羧化"],answer:[0],explanation:"维生素C参与类固醇羟基化，促进胆固醇向胆酸、皮质激素和性激素的代谢。",source:"教材第112页"},
  {id:"deep-c-16",category:"维生素 C",type:"single",stem:"维生素 C 充足时可促进形成的神经递质包括",options:["去甲肾上腺素和 5-羟色胺","乙酰胆碱和多巴胺","谷氨酸和 GABA","甲状腺素和肾上腺素"],answer:[0],explanation:"教材指出维生素C充足时可促进去甲肾上腺素和5-羟色胺的产生。",source:"教材第112页"},
  {id:"deep-c-17",category:"维生素 C",type:"single",stem:"体内维生素 C 储存量低于多少时可能出现缺乏症状",options:["30 mg","100 mg","300 mg","3000 mg"],answer:[2],explanation:"当体内维生素C储存量低于300 mg时，可出现缺乏症状，主要表现为坏血病。",source:"教材第112页"},
  {id:"deep-c-18",category:"维生素 C",type:"multiple",stem:"维生素 C 缺乏的临床表现包括",options:["毛囊周围和牙龈出血","牙龈肿胀、松软","创伤愈合延缓","骨质疏松"],answer:[0,1,2,3],explanation:"胶原合成障碍可导致出血、牙龈炎、愈合延缓和骨有机质形成不良。",source:"教材第112页"},
  {id:"deep-c-19",category:"维生素 C",type:"single",stem:"长期过量摄入维生素 C 对结石患者可能增加的风险是",options:["尿草酸盐增加和尿路结石风险增加","胆红素降低","骨折风险完全消失","血钙持续升高"],answer:[0],explanation:"结石患者长期过量摄入维生素C可能增加尿草酸盐排出和尿路结石风险。",source:"教材第112页"},
  {id:"deep-c-20",category:"维生素 C",type:"single",stem:"维生素 C 尿负荷试验中，4 小时尿排出量超过多少提示充足",options:["1 mg","5 mg","13 mg","50 mg"],answer:[2],explanation:"口服500 mg维生素C后，4小时尿排出量>13 mg为充足，5-13 mg为正常，<5 mg为不足。",source:"教材第112页"},
  {id:"deep-c-21",category:"维生素 C",type:"single",stem:"血浆维生素 C 浓度低于多少可判定为缺乏",options:["0.2 mg/L","2 mg/L","4 mg/L","12 mg/L"],answer:[1],explanation:"血浆维生素C≥4 mg/L为正常，2.0-3.9 mg/L为不足，<2 mg/L为缺乏。",source:"教材第113页"},
  {id:"deep-c-22",category:"维生素 C",type:"single",stem:"白细胞中维生素 C 浓度低于多少通常提示缺乏",options:["0.2 μg/10^8个白细胞","2 μg/10^8个白细胞","20 μg/10^8个白细胞","200 μg/10^8个白细胞"],answer:[1],explanation:"白细胞维生素C浓度可反映组织储存，低于2 μg/10^8个白细胞通常认为缺乏。",source:"教材第113页"},

  {id:"deep-phos-01",category:"磷",type:"single",stem:"正常成人血清无机磷浓度范围约为",options:["0.07-0.15 mmol/L","0.87-1.45 mmol/L","8.7-14.5 mmol/L","87-145 mmol/L"],answer:[1],explanation:"教材给出的正常成人血清无机磷浓度为0.87-1.45 mmol/L。",source:"教材第65页"},
  {id:"deep-phos-02",category:"磷",type:"single",stem:"评价健康个体磷营养状况时，较合理的实验室指标是",options:["血清无机磷","尿 FIGLU","血浆 PLP","红细胞溶血率"],answer:[0],explanation:"膳食磷摄入直接影响血清无机磷水平，测定血清无机磷可评价磷营养状况。",source:"教材第65页"},
  {id:"deep-phos-03",category:"磷",type:"multiple",stem:"膳食中磷含量较丰富的食物包括",options:["瘦肉和禽蛋","鱼和豆类","坚果和海带","谷类及油料种子"],answer:[0,1,2,3],explanation:"磷广泛分布于动物和植物食物中，题中所列均是良好来源，但谷类植酸磷吸收较差。",source:"教材第65页"},
  {id:"deep-phos-04",category:"磷",type:"single",stem:"谷类食物中的磷主要以何种形式存在，吸收利用率较低",options:["植酸磷","血红素磷","磷酸肌酸","磷脂结合磷"],answer:[0],explanation:"谷类中的磷主要为植酸磷，因与钙结合而不易吸收。",source:"教材第65页"},
  {id:"deep-mag-01",category:"镁",type:"single",stem:"人体内镁主要分布在哪个部位",options:["骨骼","细胞外液","血浆白蛋白","脂肪组织"],answer:[0],explanation:"成人体内约60%-65%的镁存在于骨骼，细胞外液中的镁不超过1%。",source:"教材第66页"},
  {id:"deep-mag-02",category:"镁",type:"single",stem:"正常情况下，膳食镁约有多少在小肠吸收",options:["3%-5%","30%-50%","70%-90%","接近100%"],answer:[1],explanation:"人体摄入的镁约30%-50%在小肠吸收。",source:"教材第66页"},
  {id:"deep-mag-03",category:"镁",type:"single",stem:"血清镁低于多少可诊断为低镁血症",options:["0.07 mmol/L","0.7 mmol/L","7.0 mmol/L","70 mmol/L"],answer:[1],explanation:"教材以血清镁<0.7 mmol/L作为低镁血症的诊断界值。",source:"教材第67页"},
  {id:"deep-mag-04",category:"镁",type:"single",stem:"静脉内镁负荷试验中，输入镁有多少以上被机体保留可提示缺镁",options:["10%","30%","50%","90%"],answer:[2],explanation:"镁负荷试验中，输入的镁超过50%保留在体内可提示缺镁，低于30%保留可排除缺镁。",source:"教材第67页"},
  {id:"deep-mag-05",category:"镁",type:"multiple",stem:"镁缺乏可能引起的表现包括",options:["神经肌肉兴奋性亢进","肌肉震颤和手足搐搦","低钾血症和低钙血症","严重时惊厥或昏迷"],answer:[0,1,2,3],explanation:"镁缺乏可增加神经肌肉兴奋性，并影响钾、钙和神经系统，严重时可出现惊厥或昏迷。",source:"教材第67页"},
  {id:"deep-mag-06",category:"镁",type:"single",stem:"精加工食品消费量增加时，膳食镁的摄入量通常会",options:["减少","增加至原来的两倍","完全不变","只在饮水不足时增加"],answer:[0],explanation:"镁主要存在于粗粮、坚果和绿叶蔬菜等食物中，精加工会降低镁含量，相关食品消费增加会使膳食镁摄入减少。",source:"教材第67页"},
  {id:"deep-mag-07",category:"镁",type:"single",stem:"2013版参考摄入量中，膳食镁的 UL 状况是",options:["暂不制定","固定为100 mg/d","固定为330 mg/d","固定为3500 mg/d"],answer:[0],explanation:"从食物和水摄入的镁通常不会引起毒性反应，因此暂不制定镁的UL。",source:"教材第67页"},
  {id:"deep-mag-08",category:"镁",type:"multiple",stem:"膳食中镁含量较丰富的来源包括",options:["绿叶蔬菜和粗粮","坚果和豆类","木耳、香菇等菌类","精加工食品"],answer:[0,1,2],explanation:"绿叶蔬菜、粗粮、坚果、豆类和菌类含镁较丰富，精加工食品中的镁含量最低。",source:"教材第67页"},
  {id:"deep-iron-01",category:"铁",type:"single",stem:"人体内铁的最大功能性储存部位是血红蛋白，约占体内铁的",options:["1%","10%-15%","65%-70%","90%-95%"],answer:[2],explanation:"体内约65%-70%的铁存在于血红蛋白中，属于功能性铁。",source:"教材第67页"},
  {id:"deep-iron-02",category:"铁",type:"single",stem:"血红素铁的有效吸收率通常约为",options:["2%-5%","2%-20%","15%-35%","50%-80%"],answer:[2],explanation:"血红素铁受膳食因素影响小，有效吸收率约15%-35%；非血红素铁约2%-20%。",source:"教材第68页"},
  {id:"deep-iron-03",category:"铁",type:"single",stem:"血清铁蛋白在缺铁评价中的主要意义是反映",options:["体内铁储存","近期维生素C摄入","红细胞平均体积","肠道铁转运速度"],answer:[0],explanation:"血清铁蛋白反映体内铁储存，是诊断隐性缺铁性贫血的可靠指标。",source:"教材第69页"},
  {id:"deep-iron-04",category:"铁",type:"multiple",stem:"缺铁性贫血常见的红细胞指标改变包括",options:["MCV降低","RDW升高","红细胞体积均一性明显增加","MCV通常低于80 fL"],answer:[0,1,3],explanation:"缺铁性贫血特征为低MCV和高RDW，通常MCV<80 fL；RDW升高表示大小异质性增加。",source:"教材第70页"},
];
